import { randomInt, randomUUID } from "crypto";
import { FieldValue, type Firestore } from "firebase-admin/firestore";
import { deterministicId } from "@/lib/server/idempotency";
import { isConsumerRewardsEligible, rewardEntitlementPayload, type RewardEntitlementType } from "@/lib/server/reward-economy";

export type RewardSpinTier = "basic" | "standard" | "premium";
export type SpinCredits = Record<RewardSpinTier, number>;
const TIERS: RewardSpinTier[] = ["basic", "standard", "premium"];
export type RewardSettings = { id: string; rewardsEnabled: boolean; maintenanceMode: boolean; rewardEarningPaused: boolean; rewardFulfillmentPaused: boolean; tierEnabled: Record<RewardSpinTier, boolean>; thresholds: SpinCredits; spinCosts: SpinCredits; pointsPerDoroCoin: number; pointsAccumulate: boolean; maxSpinsPerDay: number; maxSpinsPerUser: number | null; spinCreditExpiryDays: number | null; rewardPointExpiryDays: number | null; animationDurationMs: number; resultDisplayDurationMs: number; primaryCampaignId: string | null; publicWheelRules: string; campaignTerms: string; supportContact: string; kycRequiredForHighValuePrizes: boolean; emailVerificationRequired: boolean; phoneVerificationRequired: boolean; addressVerificationRequiredForPhysicalPrizes: boolean; minimumAccountAgeDays: number; updatedAt?: string | null };
export type RewardCampaign = { id: string; campaignName: string; description: string; active: boolean; primary: boolean; startDate: string | null; endDate: string | null; associatedWheelTiers: RewardSpinTier[]; bannerImageUrl: string | null; terms: string; eligibleCountries: string[]; eligiblePlans: string[] };
export type RewardPrize = { id: string; prizeName: string; prizeDescription: string; prizeTier: RewardSpinTier; prizeType: string; rarity: "common" | "uncommon" | "rare" | "very_rare"; fulfillmentType: "automatic" | "manual"; probabilityWeight: number; quantityType: "limited" | "unlimited"; totalQuantity: number | null; remainingQuantity: number | null; maximumWinsPerUser: number | null; maximumWinsPerDay: number | null; enabled: boolean; status: string; startDate: string | null; endDate: string | null; expiresAt: string | null; displayOrder: number; terms: string; campaignId: string | null; imageUrl: string | null; rewardValue: number; unit: string | null; economicValueCents: number; budgetId: string | null; manualFulfillmentRequired: boolean; fulfillmentInstructions: string | null; createdByAdminId: string | null; winCount: number; cashOutEnabled: false };

export function emptySpinCredits(): SpinCredits { return { basic: 0, standard: 0, premium: 0 }; }
function n(value: unknown, fallback = 0) { const parsed = Math.floor(Number(value)); return Number.isFinite(parsed) ? Math.max(0, parsed) : fallback; }
function maybeNumber(value: unknown) { return value === undefined || value === null || value === "" ? null : n(value); }
function iso(value: unknown): string | null { if (!value) return null; if (typeof value === "string") return value; const timestamp = value as { toDate?: () => Date }; return typeof timestamp.toDate === "function" ? timestamp.toDate().toISOString() : null; }
function tier(value: unknown): RewardSpinTier { const candidate = String(value ?? "basic") as RewardSpinTier; return TIERS.includes(candidate) ? candidate : "basic"; }
function rarity(value: unknown): RewardPrize["rarity"] { const candidate = String(value ?? "common") as RewardPrize["rarity"]; return ["common", "uncommon", "rare", "very_rare"].includes(candidate) ? candidate : "common"; }
export function normalizeSpinCredits(value: unknown): SpinCredits { const out = emptySpinCredits(); if (value && typeof value === "object") { const row = value as Record<string, unknown>; TIERS.forEach((item) => { out[item] = n(row[item]); }); } return out; }

export const DEFAULT_REWARD_SETTINGS: RewardSettings = { id: "default", rewardsEnabled: true, maintenanceMode: false, rewardEarningPaused: false, rewardFulfillmentPaused: false, tierEnabled: { basic: true, standard: true, premium: true }, thresholds: { basic: 100, standard: 250, premium: 500 }, spinCosts: { basic: 100, standard: 250, premium: 500 }, pointsPerDoroCoin: 0, pointsAccumulate: false, maxSpinsPerDay: 0, maxSpinsPerUser: null, spinCreditExpiryDays: 30, rewardPointExpiryDays: null, animationDurationMs: 4200, resultDisplayDurationMs: 7000, primaryCampaignId: null, publicWheelRules: "Reward Points are earned from eligible server-confirmed activity. Spins may be repeated while your balance permits. Every completed Spin awards a reward.", campaignTerms: "Reward Points and DoroCoins are separate non-cash balances. DoroCoins are platform credits, not cash. Rewards cannot be cashed out. No DoroCoin-to-cash conversion. Rewards cannot be withdrawn as cash.", supportContact: "support@challengesuite.com", kycRequiredForHighValuePrizes: false, emailVerificationRequired: false, phoneVerificationRequired: false, addressVerificationRequiredForPhysicalPrizes: true, minimumAccountAgeDays: 0 };
export const DEFAULT_REWARD_CAMPAIGN: RewardCampaign = { id: "launch-rewards-v1", campaignName: "Challenge Suite Rewards", description: "Launch Rewards configuration.", active: true, primary: true, startDate: null, endDate: null, associatedWheelTiers: TIERS, bannerImageUrl: null, terms: DEFAULT_REWARD_SETTINGS.campaignTerms, eligibleCountries: [], eligiblePlans: [] };
function prize(id: string, name: string, prizeTier: RewardSpinTier, prizeType: string, prizeRarity: RewardPrize["rarity"], weight: number, value: number, unit: string | null = null): RewardPrize { return { id, prizeName: name, prizeDescription: `${name}. This reward has no cash-out value.`, prizeTier, prizeType, rarity: prizeRarity, fulfillmentType: "automatic", probabilityWeight: weight, quantityType: "unlimited", totalQuantity: null, remainingQuantity: null, maximumWinsPerUser: null, maximumWinsPerDay: null, enabled: true, status: "active", startDate: null, endDate: null, expiresAt: null, displayOrder: 0, terms: "Rewards are non-transferable and cannot be withdrawn as cash.", campaignId: null, imageUrl: null, rewardValue: value, unit, economicValueCents: prizeType === "dorocoin" ? Math.ceil(value / 100) : 0, budgetId: null, manualFulfillmentRequired: false, fulfillmentInstructions: null, createdByAdminId: null, winCount: 0, cashOutEnabled: false }; }
export const DEFAULT_REWARD_PRIZES: RewardPrize[] = [
  prize("launch-basic-20-dorocoins", "20 DoroCoins", "basic", "dorocoin", "common", 30, 20), prize("launch-basic-40-dorocoins", "40 DoroCoins", "basic", "dorocoin", "common", 24, 40), prize("launch-basic-25-points", "25 Reward Points", "basic", "reward_points", "common", 18, 25), prize("launch-basic-50-points", "50 Reward Points", "basic", "reward_points", "uncommon", 12, 50), prize("launch-basic-75-dorocoins", "75 DoroCoins", "basic", "dorocoin", "uncommon", 8, 75), prize("launch-basic-100-points", "100 Reward Points", "basic", "reward_points", "rare", 5, 100), prize("launch-basic-150-dorocoins", "150 DoroCoins", "basic", "dorocoin", "rare", 2, 150), prize("launch-basic-250-points", "250 Reward Points", "basic", "reward_points", "very_rare", 1, 250),
  prize("launch-standard-75-dorocoins", "75 DoroCoins", "standard", "dorocoin", "common", 26, 75), prize("launch-standard-100-dorocoins", "100 DoroCoins", "standard", "dorocoin", "common", 22, 100), prize("launch-standard-75-points", "75 Reward Points", "standard", "reward_points", "common", 16, 75), prize("launch-standard-150-dorocoins", "150 DoroCoins", "standard", "dorocoin", "uncommon", 12, 150), prize("launch-standard-125-points", "125 Reward Points", "standard", "reward_points", "uncommon", 9, 125), prize("launch-standard-250-points", "250 Reward Points", "standard", "reward_points", "rare", 6, 250), prize("launch-standard-2-discount", "$2 Entry Discount", "standard", "fixed_entry_discount", "rare", 4, 200, "cents"), prize("launch-standard-300-dorocoins", "300 DoroCoins", "standard", "dorocoin", "rare", 3, 300), prize("launch-standard-500-points", "500 Reward Points", "standard", "reward_points", "very_rare", 1, 500), prize("launch-standard-5-free-entry", "Free Entry Credit up to $5", "standard", "free_entry", "very_rare", 1, 500, "cents"),
  prize("launch-premium-150-dorocoins", "150 DoroCoins", "premium", "dorocoin", "common", 22, 150), prize("launch-premium-250-dorocoins", "250 DoroCoins", "premium", "dorocoin", "common", 18, 250), prize("launch-premium-150-points", "150 Reward Points", "premium", "reward_points", "common", 14, 150), prize("launch-premium-300-dorocoins", "300 DoroCoins", "premium", "dorocoin", "uncommon", 12, 300), prize("launch-premium-250-points", "250 Reward Points", "premium", "reward_points", "uncommon", 10, 250), prize("launch-premium-500-dorocoins", "500 DoroCoins", "premium", "dorocoin", "rare", 7, 500), prize("launch-premium-25-percent", "25% Entry Discount", "premium", "percentage_entry_discount", "rare", 5, 25, "percent"), prize("launch-premium-creator-boost", "Creator Boost Credit - 72 hours", "premium", "creator_boost", "rare", 4, 72, "hours"), prize("launch-premium-750-points", "750 Reward Points", "premium", "reward_points", "rare", 3, 750), prize("launch-premium-10-free-entry", "Free Entry Credit up to $10", "premium", "free_entry", "very_rare", 2, 1000, "cents"), prize("launch-premium-limited-badge", "Limited Reward Badge", "premium", "badge", "very_rare", 2, 1), prize("launch-premium-1000-points", "1,000 Reward Points", "premium", "reward_points", "very_rare", 1, 1000)
];

export function normalizeRewardSettings(data?: Record<string, unknown> | null): RewardSettings { const costs = normalizeSpinCredits(data?.spinCosts ?? data?.thresholds ?? data?.spinThresholds); const raw = data?.tierEnabled && typeof data.tierEnabled === "object" ? data.tierEnabled as Record<string, unknown> : {}; const spinCosts = { basic: costs.basic || 100, standard: costs.standard || 250, premium: costs.premium || 500 }; return { ...DEFAULT_REWARD_SETTINGS, id: String(data?.id ?? "default"), rewardsEnabled: data?.rewardsEnabled !== false, maintenanceMode: Boolean(data?.maintenanceMode), rewardEarningPaused: Boolean(data?.rewardEarningPaused), rewardFulfillmentPaused: Boolean(data?.rewardFulfillmentPaused), tierEnabled: { basic: raw.basic !== false, standard: raw.standard !== false, premium: raw.premium !== false }, thresholds: spinCosts, spinCosts, animationDurationMs: n(data?.animationDurationMs, 4200), resultDisplayDurationMs: n(data?.resultDisplayDurationMs, 7000), primaryCampaignId: typeof data?.primaryCampaignId === "string" && data.primaryCampaignId ? data.primaryCampaignId : null, publicWheelRules: String(data?.publicWheelRules ?? DEFAULT_REWARD_SETTINGS.publicWheelRules), campaignTerms: String(data?.campaignTerms ?? DEFAULT_REWARD_SETTINGS.campaignTerms), supportContact: String(data?.supportContact ?? DEFAULT_REWARD_SETTINGS.supportContact), emailVerificationRequired: Boolean(data?.emailVerificationRequired), phoneVerificationRequired: Boolean(data?.phoneVerificationRequired), addressVerificationRequiredForPhysicalPrizes: data?.addressVerificationRequiredForPhysicalPrizes !== false, minimumAccountAgeDays: n(data?.minimumAccountAgeDays), updatedAt: iso(data?.updatedAt) }; }
export async function getRewardSettings(db: Firestore) { const snap = await db.collection("rewardSettings").doc("default").get(); return normalizeRewardSettings(snap.exists ? { id: snap.id, ...snap.data() } : null); }
export function normalizeRewardCampaign(id: string, data?: Record<string, unknown> | null): RewardCampaign { if (!data) return DEFAULT_REWARD_CAMPAIGN; return { id, campaignName: String(data.campaignName ?? data.name ?? "Rewards Campaign"), description: String(data.description ?? ""), active: data.active !== false, primary: Boolean(data.primary), startDate: iso(data.startDate), endDate: iso(data.endDate), associatedWheelTiers: Array.isArray(data.associatedWheelTiers) ? data.associatedWheelTiers.map(tier) : TIERS, bannerImageUrl: typeof data.bannerImageUrl === "string" ? data.bannerImageUrl : null, terms: String(data.terms ?? DEFAULT_REWARD_SETTINGS.campaignTerms), eligibleCountries: Array.isArray(data.eligibleCountries) ? data.eligibleCountries.map(String) : [], eligiblePlans: Array.isArray(data.eligiblePlans) ? data.eligiblePlans.map(String) : [] }; }
export async function getActiveRewardCampaign(db: Firestore, settings?: RewardSettings) { if (settings?.primaryCampaignId) { const snap = await db.collection("rewardCampaigns").doc(settings.primaryCampaignId).get(); if (snap.exists) return normalizeRewardCampaign(snap.id, snap.data()); } const snap = await db.collection("rewardCampaigns").where("active", "==", true).limit(25).get(); const campaigns = snap.docs.map((doc) => normalizeRewardCampaign(doc.id, doc.data())); return campaigns.find((item) => item.primary) ?? campaigns[0] ?? DEFAULT_REWARD_CAMPAIGN; }
export function normalizeRewardPrize(id: string, data: Record<string, unknown>): RewardPrize { const prizeType = String(data.prizeType ?? data.rewardType ?? "reward_points"); const manual = data.manualFulfillmentRequired === true || data.fulfillmentType === "manual" || ["manual_prize", "physical_reward", "gift_card"].includes(prizeType); return { id, prizeName: String(data.prizeName ?? data.name ?? "Reward Prize"), prizeDescription: String(data.prizeDescription ?? data.description ?? ""), prizeTier: tier(data.prizeTier ?? data.tier), prizeType, rarity: rarity(data.rarity), fulfillmentType: manual ? "manual" : "automatic", probabilityWeight: Math.max(0, Number(data.probabilityWeight ?? data.weight ?? 1)), quantityType: data.quantityType === "limited" ? "limited" : "unlimited", totalQuantity: maybeNumber(data.totalQuantity ?? data.quantity), remainingQuantity: maybeNumber(data.remainingQuantity ?? data.quantity), maximumWinsPerUser: maybeNumber(data.maximumWinsPerUser), maximumWinsPerDay: maybeNumber(data.maximumWinsPerDay), enabled: data.enabled !== false, status: String(data.status ?? "active"), startDate: iso(data.startDate), endDate: iso(data.endDate), expiresAt: iso(data.expiresAt), displayOrder: Number(data.displayOrder ?? 0), terms: String(data.terms ?? "Rewards cannot be withdrawn as cash."), campaignId: typeof data.campaignId === "string" ? data.campaignId : null, imageUrl: typeof data.imageUrl === "string" ? data.imageUrl : null, rewardValue: Number(data.rewardValue ?? data.value ?? 0), unit: typeof data.unit === "string" ? data.unit : null, economicValueCents: n(data.economicValueCents), budgetId: typeof data.budgetId === "string" && data.budgetId ? data.budgetId : null, manualFulfillmentRequired: manual, fulfillmentInstructions: typeof data.fulfillmentInstructions === "string" ? data.fulfillmentInstructions : null, createdByAdminId: typeof data.createdByAdminId === "string" ? data.createdByAdminId : null, winCount: n(data.winCount), cashOutEnabled: false }; }
export function isPrizeActive(item: RewardPrize, now = Date.now(), campaignId?: string | null) { if (!item.enabled || item.status !== "active" || item.probabilityWeight <= 0 || item.rewardValue <= 0) return false; if (campaignId && item.campaignId && item.campaignId !== campaignId) return false; if (item.startDate && Date.parse(item.startDate) > now) return false; const end = item.endDate ?? item.expiresAt; if (end && Date.parse(end) <= now) return false; return item.quantityType !== "limited" || (item.remainingQuantity ?? 0) > 0; }
export function availablePrizesForTier(prizes: RewardPrize[], selectedTier: RewardSpinTier, now = Date.now(), campaignId?: string | null) { return prizes.filter((item) => item.prizeTier === selectedTier && isPrizeActive(item, now, campaignId)).sort((a, b) => a.displayOrder - b.displayOrder || a.prizeName.localeCompare(b.prizeName)); }
export function chooseRewardPrize(prizes: RewardPrize[], selectedTier: RewardSpinTier, now = Date.now(), campaignId?: string | null) { const available = availablePrizesForTier(prizes, selectedTier, now, campaignId); const scaled = available.map((item) => ({ item, weight: Math.max(0, Math.round(item.probabilityWeight * 1000)) })); const total = scaled.reduce((sum, item) => sum + item.weight, 0); if (!available.length || total <= 0) return null; let cursor = randomInt(total); for (const entry of scaled) { if (cursor < entry.weight) return entry.item; cursor -= entry.weight; } return available.at(-1) ?? null; }
export function rewardPrizesNeedSetup(prizes: RewardPrize[]) { return prizes.length === 0; }
export async function loadRewardPrizes(db: Firestore) { const snap = await db.collection("rewardPrizes").where("enabled", "==", true).limit(500).get(); const configured = snap.docs.map((doc) => normalizeRewardPrize(doc.id, doc.data())); if (configured.length) return configured; const legacy = await db.collection("rewardWheelPrizes").where("enabled", "==", true).limit(500).get(); const old = legacy.docs.map((doc) => normalizeRewardPrize(doc.id, doc.data())); return old.length ? old : DEFAULT_REWARD_PRIZES; }
export function publicPrize(item: RewardPrize) { return { id: item.id, prizeName: item.prizeName, prizeDescription: item.prizeDescription, prizeTier: item.prizeTier, prizeType: item.prizeType, rarity: item.rarity, fulfillmentType: item.fulfillmentType, imageUrl: item.imageUrl, terms: item.terms, manualFulfillmentRequired: item.manualFulfillmentRequired, displayOrder: item.displayOrder, rewardValue: item.rewardValue, unit: item.unit, cashOutEnabled: false }; }
export function tierDefinitions(settings: RewardSettings) { return TIERS.map((id) => ({ id, label: `${id[0].toUpperCase()}${id.slice(1)} Spin`, spinTier: id, pointsRequired: settings.spinCosts[id], pointCost: settings.spinCosts[id], enabled: settings.tierEnabled[id] })); }
export function rewardPointReturnRatio(prizes: RewardPrize[], selectedTier: RewardSpinTier, pointCost: number) { const pool = prizes.filter((item) => item.prizeTier === selectedTier && item.enabled && item.status !== "retired" && item.probabilityWeight > 0); const totalWeight = pool.reduce((sum, item) => sum + item.probabilityWeight, 0); const expectedPoints = totalWeight ? pool.reduce((sum, item) => sum + (item.prizeType === "reward_points" ? item.rewardValue * item.probabilityWeight / totalWeight : 0), 0) : 0; const ratio = pointCost > 0 ? expectedPoints / pointCost : Number.POSITIVE_INFINITY; return { expectedPoints, ratio, warning: ratio >= 0.85, blocked: ratio >= 1 }; }

export async function buildRewardSummary(db: Firestore, userId: string) {
  const [settings, userSnap, profileSnap, accountSnap, legacySnap, historySnap, claimsSnap, streakSnap, achievementsSnap, entitlementsSnap, ledgerSnap] = await Promise.all([getRewardSettings(db), db.collection("users").doc(userId).get(), db.collection("profiles").doc(userId).get(), db.collection("rewardAccounts").doc(userId).get(), db.collection("userRewards").doc(userId).get(), db.collection("spinResults").where("userId", "==", userId).limit(50).get(), db.collection("rewardClaims").where("userId", "==", userId).limit(50).get(), db.collection("rewardStreaks").doc(userId).get(), db.collection("rewardAchievements").where("userId", "==", userId).limit(100).get(), db.collection("rewardEntitlements").where("userId", "==", userId).limit(100).get(), db.collection("rewardLedgerEntries").where("userId", "==", userId).limit(100).get()]);
  const campaign = await getActiveRewardCampaign(db, settings); const prizes = await loadRewardPrizes(db); const profile = { ...(profileSnap.data() ?? {}), ...(userSnap.data() ?? {}) }; const account = accountSnap.data() ?? {}; const legacy = legacySnap.data() ?? {}; const points = n(account.availablePoints ?? legacy.availableRewardPoints ?? userSnap.data()?.voterPoints); const timeZone = String(profile.timeZone ?? profile.timezone ?? "UTC"); const today = new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); const activitySnap = await db.collection("rewardActivityDays").doc(deterministicId("reward_activity", userId, today)).get();
  const entitlements = entitlementsSnap.docs.map((doc) => ({ id: doc.id, ...doc.data() } as Record<string, unknown>));
  return { settings, campaign, points, availableRewardPoints: points, lifetimeRewardPoints: n(account.lifetimeEarned ?? legacy.lifetimeRewardPoints), rewardDebt: n(account.rewardDebt ?? legacy.rewardDebt), tiers: tierDefinitions(settings), spinAffordability: Object.fromEntries(TIERS.map((id) => [id, points >= settings.spinCosts[id]])), prizeSetupRequired: false, prizes: Object.fromEntries(TIERS.map((id) => [id, availablePrizesForTier(prizes, id, Date.now(), campaign.id).map(publicPrize)])), history: historySnap.docs.map((doc) => ({ id: doc.id, ...doc.data() })), claims: claimsSnap.docs.map((doc) => ({ id: doc.id, ...doc.data() })), ledger: ledgerSnap.docs.map((doc) => ({ id: doc.id, ...doc.data() })), recentRewards: historySnap.docs.slice(0, 5).map((doc) => ({ id: doc.id, ...doc.data() })), streak: { current: n(streakSnap.data()?.currentStreak), longest: n(streakSnap.data()?.longestStreak), lastCheckInDay: streakSnap.data()?.lastCheckInDay ?? null, eligibleToday: activitySnap.exists, checkedInToday: streakSnap.data()?.lastCheckInDay === today, checkInAwardsPoints: false }, achievements: achievementsSnap.docs.map((doc) => ({ id: doc.id, ...doc.data() })), entitlements: entitlements.filter((item) => ["available", "reserved"].includes(String(item.status))), accountEligibility: isConsumerRewardsEligible(profile), safety: { pointsSource: "server_confirmed_eligible_activity_only", pointsPurchasable: false, clientCanGrantPoints: false, serverSelectsPrize: true, cashOutEnabled: false, rewardSelectionExposedToBrowser: false, planBasedOdds: false } };
}

// Kept for webhook compatibility: purchasing DoroCoins never earns Reward Points.
export async function awardDoroCoinPurchaseRewards(_db: Firestore, _input: { userId: string; coins: number; sourceId: string; eventId: string }) { return { pointsAwarded: 0, spinCreditsAwarded: emptySpinCredits(), rewardEventId: null, skipped: "reward_points_are_earned_only" }; }
function entitlementType(prizeType: string): RewardEntitlementType | null { return ["free_entry", "fixed_entry_discount", "percentage_entry_discount", "creator_boost", "bonus_spin", "badge"].includes(prizeType) ? prizeType as RewardEntitlementType : null; }
function ledger(input: { id: string; userId: string; direction: "credit" | "debit"; amount: number; sourceType: string; sourceId: string; sourceEventKey: string; description: string; spinId: string; createdAt: string }) { return { ...input, currency: "REWARD_POINTS", immutable: true, withdrawable: false, cashValue: null }; }

export async function executeRewardSpin(db: Firestore, input: { userId: string; tier: RewardSpinTier; idempotencyKey?: string | null; paymentSource?: "points" | "bonus_spin"; bonusEntitlementId?: string | null }) {
  const settings = await getRewardSettings(db); const campaign = await getActiveRewardCampaign(db, settings); const allPrizes = await loadRewardPrizes(db); const prizes = availablePrizesForTier(allPrizes, input.tier, Date.now(), campaign.id); const selected = chooseRewardPrize(prizes, input.tier, Date.now(), campaign.id); if (!selected) throw new Error("NO_AVAILABLE_PRIZES"); if (rewardPointReturnRatio(prizes, input.tier, settings.spinCosts[input.tier]).blocked) throw new Error("REWARD_POINT_RETURN_RATIO_BLOCKED");
  const now = new Date().toISOString(); const spinId = input.idempotencyKey ? deterministicId("reward_spin", input.userId, input.tier, input.idempotencyKey) : randomUUID(); const spinRef = db.collection("spinResults").doc(spinId); const paymentSource = input.paymentSource === "bonus_spin" ? "bonus_spin" : "points"; const versionId = `launch-v1-${input.tier}`;
  const result = await db.runTransaction(async (transaction) => {
    const accountRef = db.collection("rewardAccounts").doc(input.userId); const legacyRef = db.collection("userRewards").doc(input.userId); const userRef = db.collection("users").doc(input.userId); const profileRef = db.collection("profiles").doc(input.userId); const prizeRef = selected.id.startsWith("launch-") ? null : db.collection("rewardPrizes").doc(selected.id); const budgetRef = selected.budgetId ? db.collection("rewardBudgets").doc(selected.budgetId) : null; const bonusRef = paymentSource === "bonus_spin" && input.bonusEntitlementId ? db.collection("rewardEntitlements").doc(input.bonusEntitlementId) : null;
    const [existing, accountSnap, legacySnap, userSnap, profileSnap, prizeSnap, budgetSnap, bonusSnap] = await Promise.all([transaction.get(spinRef), transaction.get(accountRef), transaction.get(legacyRef), transaction.get(userRef), transaction.get(profileRef), prizeRef ? transaction.get(prizeRef) : Promise.resolve(null), budgetRef ? transaction.get(budgetRef) : Promise.resolve(null), bonusRef ? transaction.get(bonusRef) : Promise.resolve(null)]);
    if (existing.exists) return { alreadyProcessed: true, spin: { id: existing.id, ...existing.data() } };
    if (!settings.rewardsEnabled || settings.maintenanceMode) throw new Error("REWARDS_DISABLED"); if (settings.rewardFulfillmentPaused) throw new Error("REWARD_FULFILLMENT_PAUSED"); if (!settings.tierEnabled[input.tier]) throw new Error("WHEEL_DISABLED"); const eligibility = isConsumerRewardsEligible({ ...(profileSnap.data() ?? {}), ...(userSnap.data() ?? {}) }); if (!eligibility.eligible) throw new Error(eligibility.restricted ? "REWARDS_ACCOUNT_RESTRICTED" : "REWARDS_ACCOUNT_NOT_ELIGIBLE");
    const account = accountSnap.data() ?? {}; const legacy = legacySnap.data() ?? {}; const previousPoints = n(account.availablePoints ?? legacy.availableRewardPoints ?? userSnap.data()?.voterPoints); if (n(account.rewardDebt ?? legacy.rewardDebt)) throw new Error("REWARD_DEBT_ACTIVE"); const pointCost = settings.spinCosts[input.tier]; if (paymentSource === "points" && previousPoints < pointCost) throw new Error("INSUFFICIENT_REWARD_POINTS");
    if (paymentSource === "bonus_spin") { if (!bonusSnap?.exists || bonusSnap.data()?.userId !== input.userId || bonusSnap.data()?.type !== "bonus_spin" || bonusSnap.data()?.status !== "available") throw new Error("BONUS_SPIN_UNAVAILABLE"); if (bonusSnap.data()?.tier && bonusSnap.data()?.tier !== input.tier) throw new Error("BONUS_SPIN_TIER_MISMATCH"); if (bonusSnap.data()?.expiresAt && Date.parse(String(bonusSnap.data()?.expiresAt)) <= Date.now()) throw new Error("BONUS_SPIN_EXPIRED"); }
    let selectedPrize = selected; if (prizeRef) { if (!prizeSnap?.exists) throw new Error("PRIZE_NOT_FOUND"); selectedPrize = normalizeRewardPrize(prizeSnap.id, prizeSnap.data() ?? {}); if (!isPrizeActive(selectedPrize, Date.now(), campaign.id)) throw new Error("PRIZE_UNAVAILABLE"); if (selectedPrize.quantityType === "limited") { const remaining = n(selectedPrize.remainingQuantity); if (!remaining) throw new Error("PRIZE_OUT_OF_STOCK"); transaction.set(prizeRef, { remainingQuantity: remaining - 1, winCount: selectedPrize.winCount + 1, updatedAt: now }, { merge: true }); } else transaction.set(prizeRef, { winCount: selectedPrize.winCount + 1, updatedAt: now }, { merge: true }); }
    if (budgetRef) { if (!budgetSnap?.exists) throw new Error("REWARD_BUDGET_NOT_FOUND"); const remaining = n(budgetSnap.data()?.remainingExposureCents); if (remaining < selectedPrize.economicValueCents) throw new Error("REWARD_BUDGET_EXHAUSTED"); transaction.set(budgetRef, { remainingExposureCents: remaining - selectedPrize.economicValueCents, reservedExposureCents: FieldValue.increment(selectedPrize.economicValueCents), updatedAt: now }, { merge: true }); }
    const rewardPointPrize = selectedPrize.prizeType === "reward_points" ? n(selectedPrize.rewardValue) : 0; const debit = paymentSource === "points" ? pointCost : 0; const nextPoints = previousPoints - debit + rewardPointPrize;
    for (const [kind, direction, value, sourceType, description] of [["cost", "debit", debit, "spin_cost", `${input.tier} Spin cost.`], ["prize", "credit", rewardPointPrize, "spin_reward", selectedPrize.prizeName]] as const) { if (!value) continue; const id = deterministicId("reward_ledger", spinId, kind); const record = ledger({ id, userId: input.userId, direction, amount: value, sourceType, sourceId: kind === "cost" ? spinId : selectedPrize.id, sourceEventKey: `spin-${kind}:${spinId}`, description, spinId, createdAt: now }); transaction.create(db.collection("rewardLedgerEntries").doc(id), record); transaction.create(accountRef.collection("ledger").doc(id), record); }
    if (bonusRef) transaction.set(bonusRef, { status: "consumed", consumedAt: now, consumedBySpinId: spinId, updatedAt: now }, { merge: true });
    const fulfillmentId = deterministicId("reward_fulfillment", spinId); const fulfillmentStatus = selectedPrize.manualFulfillmentRequired ? "pending_claim" : "fulfilled"; const probabilitySnapshot = { versionId, prizeId: selectedPrize.id, prizeWeight: selectedPrize.probabilityWeight, activePrizeCount: prizes.length, totalWeight: prizes.reduce((sum, item) => sum + item.probabilityWeight, 0), eligiblePrizeIds: prizes.map((item) => item.id) }; const spin = { id: spinId, userId: input.userId, wheelTier: input.tier, pointCost: debit, paymentSource, campaignId: campaign.id, wheelVersionId: versionId, prizeId: selectedPrize.id, prizeName: selectedPrize.prizeName, prizeDescription: selectedPrize.prizeDescription, prizeType: selectedPrize.prizeType, prizeTier: selectedPrize.prizeTier, rarity: selectedPrize.rarity, imageUrl: selectedPrize.imageUrl, rewardValue: selectedPrize.rewardValue, status: "confirmed", spinStatus: "confirmed", rewardStatus: fulfillmentStatus, fulfillmentStatus, fulfillmentId, manualFulfillmentRequired: selectedPrize.manualFulfillmentRequired, serverSelected: true, idempotencyKey: input.idempotencyKey ?? null, probabilitySnapshot, inventoryReservationId: selectedPrize.quantityType === "limited" ? deterministicId("reward_inventory", spinId) : null, budgetReservationId: budgetRef ? deterministicId("reward_budget", spinId) : null, cashOutEnabled: false, createdAt: now, updatedAt: now };
    transaction.set(accountRef, { userId: input.userId, availablePoints: nextPoints, lifetimeEarned: n(account.lifetimeEarned) + rewardPointPrize, lifetimeSpent: n(account.lifetimeSpent) + debit, updatedAt: now, createdAt: account.createdAt ?? now }, { merge: true }); transaction.set(legacyRef, { userId: input.userId, availableRewardPoints: nextPoints, lifetimeRewardPoints: n(legacy.lifetimeRewardPoints) + rewardPointPrize, updatedAt: now }, { merge: true }); transaction.set(userRef, { voterPoints: nextPoints, updatedAt: now }, { merge: true }); transaction.create(spinRef, spin); transaction.create(db.collection("rewardSpinHistory").doc(spinId), spin); transaction.create(accountRef.collection("spinHistory").doc(spinId), spin);
    if (selectedPrize.prizeType === "dorocoin") { const walletRef = db.collection("doroCoinWallets").doc(input.userId); const coinRef = db.collection("doroCoinTransactions").doc(deterministicId("reward_dorocoin", spinId)); transaction.set(walletRef, { userId: input.userId, balance: FieldValue.increment(selectedPrize.rewardValue), withdrawable: false, updatedAt: now }, { merge: true }); transaction.create(coinRef, { id: coinRef.id, userId: input.userId, amount: selectedPrize.rewardValue, signedAmount: selectedPrize.rewardValue, direction: "credit", type: "reward", sourceType: "reward_spin", sourceId: spinId, description: selectedPrize.prizeName, immutable: true, withdrawable: false, cashOutEnabled: false, createdAt: now }); }
    const type = entitlementType(selectedPrize.prizeType); if (type) { const id = deterministicId("reward_entitlement", spinId, type); transaction.create(db.collection("rewardEntitlements").doc(id), rewardEntitlementPayload({ id, userId: input.userId, type, sourceId: spinId, value: selectedPrize.rewardValue, unit: selectedPrize.unit ?? undefined, tier: type === "bonus_spin" ? input.tier : undefined, metadata: type === "free_entry" ? { maximumFeeCents: selectedPrize.rewardValue } : {}, now })); if (type === "badge") transaction.set(db.collection("userBadges").doc(deterministicId("reward_badge", input.userId, selectedPrize.id)), { id: deterministicId("reward_badge", input.userId, selectedPrize.id), userId: input.userId, badgeId: selectedPrize.id, source: "rewards", sourceId: spinId, status: "earned", displayPublicly: false, earnedAt: now, createdAt: now, updatedAt: now }, { merge: true }); }
    const fulfillment = { id: fulfillmentId, spinId, userId: input.userId, prizeId: selectedPrize.id, prizeType: selectedPrize.prizeType, status: fulfillmentStatus, attemptCount: selectedPrize.manualFulfillmentRequired ? 0 : 1, nextAttemptAt: null, lastErrorCode: null, replacementPrizeId: null, refundedPointCost: 0, createdAt: now, updatedAt: now }; transaction.create(db.collection("rewardFulfillments").doc(fulfillmentId), fulfillment); transaction.create(db.collection("rewardFulfilments").doc(fulfillmentId), fulfillment); if (selectedPrize.manualFulfillmentRequired) transaction.create(db.collection("rewardClaims").doc(spinId), { id: spinId, fulfillmentId, spinId, userId: input.userId, prizeId: selectedPrize.id, prizeName: selectedPrize.prizeName, prizeType: selectedPrize.prizeType, status: "awaiting_claim", claimStatus: "awaiting_claim", fulfillmentStatus: "awaiting_claim", createdAt: now, updatedAt: now }); const auditId = deterministicId("reward_spin_audit", spinId); transaction.create(db.collection("rewardAuditLogs").doc(auditId), { id: auditId, userId: input.userId, spinId, action: "reward_spin_confirmed", tier: input.tier, pointCost: debit, paymentSource, prizeId: selectedPrize.id, wheelVersionId: versionId, serverSelected: true, cashOutEnabled: false, createdAt: now }); return { alreadyProcessed: false, spin };
  });
  return { ...result, spin: { ...result.spin, prize: publicPrize(selected) }, settings, campaign };
}

export async function createRewardClaim(db: Firestore, input: { userId: string; claimId: string; legalName: string; email: string; phone?: string; deliveryAddress?: string; termsAccepted: boolean }) { if (!input.termsAccepted) throw new Error("TERMS_REQUIRED"); const now = new Date().toISOString(); const ref = db.collection("rewardClaims").doc(input.claimId); return db.runTransaction(async (transaction) => { const snap = await transaction.get(ref); if (!snap.exists) throw new Error("CLAIM_NOT_FOUND"); const claim = snap.data() ?? {}; if (claim.userId !== input.userId) throw new Error("CLAIM_FORBIDDEN"); if (!["awaiting_claim", "claim_rejected"].includes(String(claim.claimStatus ?? claim.status))) throw new Error("CLAIM_ALREADY_SUBMITTED"); const payload = { claimStatus: "claim_submitted", status: "claim_submitted", fulfillmentStatus: "claim_under_review", legalName: input.legalName.slice(0, 120), email: input.email.slice(0, 180), phone: input.phone?.slice(0, 60) ?? null, deliveryAddress: input.deliveryAddress?.slice(0, 1000) ?? null, termsAccepted: true, submittedAt: now, updatedAt: now, claimReference: `CS-${input.claimId.slice(0, 8).toUpperCase()}` }; transaction.set(ref, payload, { merge: true }); const fulfillmentId = String(claim.fulfillmentId ?? input.claimId); transaction.set(db.collection("rewardFulfilments").doc(fulfillmentId), payload, { merge: true }); transaction.set(db.collection("rewardFulfillments").doc(fulfillmentId), payload, { merge: true }); transaction.create(db.collection("rewardAuditLogs").doc(deterministicId("reward_claim", input.claimId)), { id: deterministicId("reward_claim", input.claimId), userId: input.userId, claimId: input.claimId, action: "reward_claim_submitted", createdAt: now }); return { id: input.claimId, ...claim, ...payload }; }); }
export function adminPrizePayload(body: Record<string, unknown>, adminId: string) { const now = new Date().toISOString(); const quantityType = body.quantityType === "limited" ? "limited" : "unlimited"; const fulfillmentType = body.fulfillmentType === "manual" ? "manual" : "automatic"; const prizeType = String(body.prizeType ?? "reward_points"); if (!["reward_points", "dorocoin", "free_entry", "fixed_entry_discount", "percentage_entry_discount", "creator_boost", "bonus_spin", "badge"].includes(prizeType)) throw new Error("REWARD_PRIZE_TYPE_NOT_REGISTERED"); return { prizeName: String(body.prizeName ?? body.name ?? "Untitled prize").slice(0, 120), prizeDescription: String(body.prizeDescription ?? body.description ?? "").slice(0, 500), prizeTier: tier(body.prizeTier ?? body.tier), prizeType, rarity: rarity(body.rarity), fulfillmentType, manualFulfillmentRequired: fulfillmentType === "manual", probabilityWeight: Math.max(0, Number(body.probabilityWeight ?? 1)), quantityType, totalQuantity: quantityType === "unlimited" ? null : n(body.totalQuantity ?? body.quantity), remainingQuantity: quantityType === "unlimited" ? null : n(body.remainingQuantity ?? body.totalQuantity ?? body.quantity), maximumWinsPerUser: maybeNumber(body.maximumWinsPerUser), maximumWinsPerDay: maybeNumber(body.maximumWinsPerDay), enabled: body.enabled !== false, status: String(body.status ?? "draft"), startDate: typeof body.startDate === "string" && body.startDate ? body.startDate : null, endDate: typeof body.endDate === "string" && body.endDate ? body.endDate : null, expiresAt: typeof body.expiresAt === "string" && body.expiresAt ? body.expiresAt : null, displayOrder: Number(body.displayOrder ?? 0), terms: String(body.terms ?? "Rewards cannot be withdrawn as cash.").slice(0, 2000), campaignId: typeof body.campaignId === "string" && body.campaignId ? body.campaignId : null, imageUrl: typeof body.imageUrl === "string" && body.imageUrl ? body.imageUrl : null, rewardValue: n(body.rewardValue), unit: typeof body.unit === "string" ? body.unit.slice(0, 30) : null, economicValueCents: n(body.economicValueCents), budgetId: typeof body.budgetId === "string" && body.budgetId ? body.budgetId : null, fulfillmentInstructions: typeof body.fulfillmentInstructions === "string" ? body.fulfillmentInstructions.slice(0, 2000) : null, updatedAt: now, createdByAdminId: adminId, cashOutEnabled: false }; }
