import { z } from "zod";
import { getAdminAuth, getAdminDb } from "@/lib/firebase/admin";
import { writeAuditLog } from "@/lib/server/audit";
import { requireAdminPermission, requireRecentAdminAuthentication } from "@/lib/server/auth";
import { ok, fail, readJson, serverError, serverUnavailable, validationError } from "@/lib/server/responses";

const actionSchema = z.object({ action: z.enum(["warn", "restrict_messaging", "restrict_challenge_creation", "restrict_participation", "restrict_withdrawals", "suspend_talent_workspace", "suspend_sponsor_workspace", "suspend_account", "reinstate", "require_identity_verification", "revoke_sessions", "require_password_reset", "add_note"]), reason: z.string().trim().min(8).max(1000), note: z.string().trim().max(2000).optional() });
const mask = (value: unknown) => { const text = String(value ?? ""); return text.length < 5 ? "****" : `${text.slice(0, 2)}${"*".repeat(Math.min(8, text.length - 4))}${text.slice(-2)}`; };

export async function GET(request: Request, { params }: { params: Promise<{ uid: string }> }) {
  const { uid } = await params; const url = new URL(request.url); const fullPayout = url.searchParams.get("payout") === "full";
  const authResult = fullPayout ? await requireRecentAdminAuthentication(request, "users.viewPayoutDetails") : await requireAdminPermission(request, "users.view"); if (authResult.response) return authResult.response;
  const db = getAdminDb(); if (!db) return serverUnavailable("User control centre");
  if (fullPayout && (request.headers.get("x-admin-access-reason")?.trim().length ?? 0) < 8) return validationError({ reason: "A reason is required to view full payout details." });
  // @ts-expect-error Firestore control-centre records are intentionally projected from heterogeneous collections.
  try { const [user, profile, challenges, participation, submissions, ledger, withdrawals, reports, tickets, notes, audit] = await Promise.all([db.collection("users").doc(uid).get(), db.collection("profiles").doc(uid).get(), db.collection("challenges").where("creatorId", "==", uid).limit(100).get(), db.collection("challengeParticipants").where("userId", "==", uid).limit(100).get(), db.collection("submissions").where("userId", "==", uid).limit(100).get(), db.collection("cashLedger").where("userId", "==", uid).limit(200).get(), db.collection("withdrawalRequests").where("userId", "==", uid).limit(100).get(), db.collection("reports").where("userId", "==", uid).limit(100).get(), db.collection("supportTickets").where("userId", "==", uid).limit(100).get(), db.collection("adminNotes").where("targetId", "==", uid).limit(100).get(), db.collection("auditLogs").where("targetId", "==", uid).limit(200).get()]); if (!user.exists) return fail("User not found.", 404); const data = { ...user.data(), ...profile.data() }; const payout = (data.payoutAccount ?? {}) as Record<string, unknown>; const payoutDetails = Object.fromEntries(Object.entries(payout).map(([key, value]) => [key, fullPayout ? value : mask(value)])); if (fullPayout) await writeAuditLog({ actorId: authResult.user!.uid, actorType: "admin", action: "user.payout_details_viewed", targetType: "account", targetId: uid, reason: request.headers.get("x-admin-access-reason") }, db); const docs = (snap: FirebaseFirestore.QuerySnapshot) => snap.docs.map((doc) => ({ id: doc.id, ...doc.data() })); return ok({ user: { id: uid, displayName: data.displayName ?? data.name ?? "User", email: data.email ?? "", accountStatus: data.accountStatus ?? "active", restrictions: data.restrictions ?? {}, kycStatus: data.kycStatus ?? "not_started", payoutDetails, payoutDetailsMasked: !fullPayout }, workspaces: data.workspaceTypes ?? [], challenges: docs(challenges), participation: docs(participation), submissions: docs(submissions), earnings: docs(ledger).filter((item) => item.direction === "credit"), transactions: docs(ledger), withdrawals: docs(withdrawals), reports: docs(reports), support: docs(tickets), notes: docs(notes), activityHistory: docs(audit), readonlyPreview: true, impersonationEnabled: false }); } catch (error) { return serverError("User control centre could not be loaded.", error instanceof Error ? error.message : error); }
}

export async function PATCH(request: Request, { params }: { params: Promise<{ uid: string }> }) {
  const { uid } = await params; const { user, response } = await requireAdminPermission(request, "users.restrict"); if (response) return response; const db = getAdminDb(); const auth = getAdminAuth(); if (!db || !auth) return serverUnavailable("User controls"); const body = await readJson(request); if (body.response) return body.response; const parsed = actionSchema.safeParse(body.body); if (!parsed.success) return validationError({ request: parsed.error.issues[0]?.message ?? "Invalid action." });
  try { const ref = db.collection("users").doc(uid); const snap = await ref.get(); if (!snap.exists) return fail("User not found.", 404); const now = new Date().toISOString(); const restrictions = { ...((snap.data()?.restrictions ?? {}) as Record<string, unknown>) }; const action = parsed.data.action; if (action.startsWith("restrict_")) restrictions[action.replace("restrict_", "")] = true; if (action === "reinstate") Object.keys(restrictions).forEach((key) => { restrictions[key] = false; }); const update: Record<string, unknown> = { restrictions, updatedAt: now }; if (action === "suspend_account") update.accountStatus = "suspended"; if (action === "reinstate") update.accountStatus = "active"; if (action === "require_identity_verification") update.kycStatus = "required"; if (action === "require_password_reset") update.passwordResetRequiredAt = now; if (action === "revoke_sessions") await auth.revokeRefreshTokens(uid); await ref.set(update, { merge: true }); if (action === "add_note") { const noteRef = db.collection("adminNotes").doc(); await noteRef.set({ id: noteRef.id, targetType: "user", targetId: uid, note: parsed.data.note ?? parsed.data.reason, internalOnly: true, createdBy: user!.uid, createdAt: now }); } await writeAuditLog({ actorId: user!.uid, actorType: "admin", action: `user.${action}`, targetType: "account", targetId: uid, reason: parsed.data.reason, before: snap.data(), after: update }, db); return ok({ uid, action }, "User control updated."); } catch (error) { return serverError("User control could not be updated.", error instanceof Error ? error.message : error); }
}
