"use client";

import { useState } from "react";
import { useParams } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ClipboardCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button, Card, EmptyState, LinkButton, PageTitle } from "@/components/ui";
import { apiRequest } from "@/lib/api/client";

const tabs = ["Overview", "Participants", "Entry Requests", "Submissions", "Voting", "Reports", "Winners", "Settlement", "Timeline", "Settings", "Audit Log"] as const;
type Payload = { challenge: Record<string, unknown>; participants: Record<string, unknown>[]; entryRequests: Record<string, unknown>[]; submissions: Record<string, unknown>[]; reports: Record<string, unknown>[]; winnerProposals: Record<string, unknown>[]; settlements: Record<string, unknown>[]; audits: Record<string, unknown>[]; permissions: { isAdmin: boolean; canModerateSensitiveActions: boolean } };

export default function ChallengeManagePage() {
  const { id } = useParams<{ id: string }>();
  const [tab, setTab] = useState<(typeof tabs)[number]>("Overview");
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["challenge-manage", id], queryFn: () => apiRequest<Payload>(`/api/challenges/${id}/manage`), enabled: Boolean(id) });
  const data = query.data?.ok ? query.data.data : null;
  const mutation = useMutation({ mutationFn: (input: Record<string, unknown>) => apiRequest(`/api/challenges/${id}/manage`, { method: "PATCH", body: JSON.stringify(input) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["challenge-manage", id] }) });
  const lists: Record<string, Record<string, unknown>[]> = { Participants: data?.participants ?? [], "Entry Requests": data?.entryRequests ?? [], Submissions: data?.submissions ?? [], Reports: data?.reports ?? [], Winners: data?.winnerProposals ?? [], Settlement: data?.settlements ?? [], "Audit Log": data?.audits ?? [] };
  const items = lists[tab] ?? [];
  function act(targetType: string, targetId: string, action: string, needsReason = false) { const reason = needsReason ? window.prompt("Reason") ?? "" : ""; mutation.mutate({ targetType, targetId, action, reason }); }
  return <AppShell><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><PageTitle title="Challenge Management" subtitle={String(data?.challenge.title ?? "Manage participants, submissions, reports, results, and lifecycle state.")} icon={<ClipboardCheck />} /><LinkButton href={`/challenges/${id}`} variant="secondary">View Challenge</LinkButton></div><div className="mt-6 flex gap-2 overflow-x-auto pb-2">{tabs.map((item) => <Button key={item} variant={tab === item ? "primary" : "secondary"} onClick={() => setTab(item)}>{item}</Button>)}</div>{query.isLoading ? <Card className="mt-6 h-64 animate-pulse" /> : !data ? <Card className="mt-6 border-red-500/30 p-5 text-red-200">{query.data?.message ?? "Challenge management could not load."}</Card> : tab === "Overview" ? <Overview data={data} id={id} /> : ["Voting", "Timeline", "Settings"].includes(tab) ? <Tools tab={tab} id={id} /> : items.length ? <div className="mt-6 grid gap-4">{items.map((item) => <Row key={String(item.id)} item={item} tab={tab} act={act} busy={mutation.isPending} canAdminModerate={data.permissions.canModerateSensitiveActions} />)}</div> : <Card className="mt-6"><EmptyState icon={<ClipboardCheck />} title={`No ${tab.toLowerCase()} records`} body="Records will appear here when real challenge activity is available." /></Card>}</div></AppShell>;
}
function Overview({ data, id }: { data: Payload; id: string }) { return <div className="mt-6 grid gap-4 md:grid-cols-3">{[["Participants", data.participants.length], ["Submissions", data.submissions.length], ["Open reports", data.reports.filter((r) => !["resolved", "dismissed"].includes(String(r.status))).length]].map(([label, value]) => <Card key={String(label)} className="p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></Card>)}<Card className="p-5 md:col-span-3"><div className="flex flex-wrap gap-3"><LinkButton href={`/challenges/${id}/entry-requests`}>Entry Requests</LinkButton><LinkButton href={`/challenges/${id}/propose-winners`} variant="secondary">Winner Review</LinkButton></div></Card></div> }
function Tools({ tab, id }: { tab: string; id: string }) { const copy: Record<string,string> = { Voting: "Voting windows and leaderboard visibility use canonical challenge lifecycle rules.", Timeline: "Timeline changes after entries exist require admin review.", Settings: "Challenge settings remain subject to publish and eligibility validation." }; return <Card className="mt-6 p-6"><h2 className="text-xl font-black">{tab}</h2><p className="mt-3 text-slate-300">{copy[tab]}</p>{tab === "Voting" ? <LinkButton className="mt-5" href={`/challenges/${id}/votes`}>View Voting</LinkButton> : null}</Card> }
function Row({ item, tab, act, busy, canAdminModerate }: { item: Record<string, unknown>; tab: string; act: (type:string,id:string,action:string,reason?:boolean)=>void; busy:boolean; canAdminModerate:boolean }) { const id=String(item.id); const status=String(item.status ?? item.moderationStatus ?? "pending").replaceAll("_"," "); const type=tab === "Participants" ? "participant" : tab === "Submissions" ? "submission" : tab === "Reports" ? "report" : ""; return <Card className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-black">{String(item.title ?? item.displayName ?? item.userName ?? item.type ?? id)}</h2><p className="mt-1 text-sm capitalize text-slate-400">{status}</p></div><div className="flex flex-wrap gap-2">{type === "submission" && canAdminModerate ? <><Button disabled={busy} onClick={() => act(type,id,"approve")}>Approve</Button><Button disabled={busy} variant="secondary" onClick={() => act(type,id,"request_changes",true)}>Request Changes</Button><Button disabled={busy} variant="secondary" onClick={() => act(type,id,"reject",true)}>Reject</Button></> : type === "participant" && canAdminModerate ? <><Button disabled={busy} variant="secondary" onClick={() => act(type,id,"restore")}>Restore</Button><Button disabled={busy} variant="secondary" onClick={() => act(type,id,"disqualify",true)}>Disqualify</Button></> : type === "report" && canAdminModerate ? <><Button disabled={busy} onClick={() => act(type,id,"review")}>Review</Button><Button disabled={busy} variant="secondary" onClick={() => act(type,id,"resolve")}>Resolve</Button><Button disabled={busy} variant="secondary" onClick={() => act(type,id,"escalate",true)}>Escalate</Button></> : type === "report" ? <Button disabled={busy} onClick={() => act(type,id,"request_review",true)}>Request Admin Review</Button> : null}</div></div></Card> }
