"use client";

import { useEffect, useMemo, useState } from "react";
import { FileCheck2, Search } from "lucide-react";
import { SponsorShell, type SponsorShellProfile } from "@/components/sponsor/sponsor-shell";
import { Button, Card, EmptyState, Field, inputClass, LinkButton, textareaClass } from "@/components/ui";
import { apiRequest } from "@/lib/api/client";
import { approvalStatuses, label } from "@/lib/sponsor-collaboration";

export default function SponsorApprovalsPage() {
  const [profile, setProfile] = useState<SponsorShellProfile | null>(null);
  const [items, setItems] = useState<any[]>([]);
  const [status, setStatus] = useState("all");
  const [query, setQuery] = useState("");
  const [title, setTitle] = useState("");
  const [type, setType] = useState("campaign_asset");
  const [deadline, setDeadline] = useState("");
  const [preview, setPreview] = useState("");
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState("");
  async function load() { const [profileResult, result] = await Promise.all([apiRequest<{ sponsorProfile: SponsorShellProfile }>("/api/sponsor/profile"), apiRequest<{ approvals: any[] }>("/api/sponsor/approvals")]); if (profileResult.ok && profileResult.data) setProfile(profileResult.data.sponsorProfile); if (result.ok && result.data) setItems(result.data.approvals); else setNotice(result.message || "Approvals could not be loaded."); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function create() { const result = await apiRequest("/api/sponsor/approvals", { method: "POST", body: JSON.stringify({ title, type, deadline, previewFoundation: preview }) }); setNotice(result.message); if (result.ok) { setTitle(""); setPreview(""); setDeadline(""); void load(); } }
  const filtered = useMemo(() => items.filter((item) => (status === "all" || item.status === status) && (!query || [item.title, item.type, item.relatedCampaignId, item.relatedCreatorId].some((value) => String(value ?? "").toLowerCase().includes(query.toLowerCase())))), [items, query, status]);
  return <SponsorShell profile={profile}><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm font-black uppercase tracking-[0.2em] text-[var(--gold)]">Approval Center</p><h1 className="mt-3 text-4xl font-black">Centralized approvals</h1><p className="mt-3 max-w-3xl leading-7 text-slate-300">Review campaign assets, placements, promotional content, and final reports. Approvals do not release money or publish campaigns automatically.</p></div><LinkButton href="/sponsor/deliverables" variant="secondary">Deliverables</LinkButton></div><div className="mt-8 grid gap-8 xl:grid-cols-[.85fr_1.15fr]"><Card className="p-6"><h2 className="text-2xl font-black">Create approval item</h2><div className="mt-5 grid gap-4"><Field label="Approval title"><input className={inputClass} value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="Type"><input className={inputClass} value={type} onChange={(event) => setType(event.target.value)} /></Field><Field label="Deadline"><input className={inputClass} value={deadline} onChange={(event) => setDeadline(event.target.value)} /></Field><Field label="Preview"><textarea className={textareaClass} value={preview} onChange={(event) => setPreview(event.target.value)} /></Field><Button disabled={title.length < 3} onClick={() => void create()}>Create Approval</Button>{notice ? <p className="text-sm text-slate-300">{notice}</p> : null}</div></Card><div><Card className="p-4"><div className="grid gap-3 lg:grid-cols-[1fr_240px]"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3.5 text-slate-500" size={18} /><input className={`${inputClass} pl-10`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search approvals" /></div><select className={inputClass} value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{approvalStatuses.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></div></Card>{loading ? <Card className="mt-5 h-72 animate-pulse bg-[#171717]" /> : filtered.length === 0 ? <EmptyState icon={<FileCheck2 />} title="No approvals pending." body="Assets and campaign decisions needing your review will appear here." /> : <div className="mt-5 grid gap-4 lg:grid-cols-2">{filtered.map((item) => <ApprovalCard key={item.id} item={item} reload={load} />)}</div>}</div></div></div></SponsorShell>;
}
function ApprovalCard({ item, reload }: { item: any; reload: () => Promise<void> }) { const [notice, setNotice] = useState(""); async function update(status: string) { const result = await apiRequest(`/api/sponsor/approvals/${item.id}`, { method: "PATCH", body: JSON.stringify({ status }) }); setNotice(result.message); if (result.ok) void reload(); } return <Card className="p-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-[var(--gold)]">{label(item.status)}</p><h2 className="mt-2 text-xl font-black">{item.title}</h2><p className="mt-2 text-sm text-slate-400">{label(item.type)} / Deadline: {item.deadline || "Not scheduled"}</p><p className="mt-2 text-sm leading-6 text-slate-300">{item.previewFoundation || "Preview not available yet."}</p><div className="mt-4 flex flex-wrap gap-3"><Button onClick={() => void update("approved")}>Approve</Button><Button variant="secondary" onClick={() => void update("changes_requested")}>Request Changes</Button><Button variant="ghost" onClick={() => void update("rejected")}>Reject</Button><LinkButton href={`/sponsor/approvals/${item.id}`} variant="ghost">Details</LinkButton></div>{notice ? <p className="mt-3 text-xs text-slate-400">{notice}</p> : null}</Card>; }

