"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, Building2, ClipboardCheck, ReceiptText, Search, ShieldCheck, Target, UsersRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Card, inputClass, LinkButton, PageTitle } from "@/components/ui";
import { apiRequest } from "@/lib/api/client";

type Kind = "challenges" | "assigned" | "submissions" | "reviews" | "analytics" | "finance" | "sponsorships" | "team" | "activity";
type Item = Record<string, unknown> & { id: string };
type Payload = { challenges: Item[]; records?: Item[]; finance?: Item[]; sponsorships?: Item[]; team?: Item[]; activity?: Item[]; access: { role: string; department: string; permissions: string[] }; accessState?: string; metrics: Record<string, number>; pagination: { total: number } };
const settings: Record<Kind, { title: string; subtitle: string; icon: typeof Building2 }> = {
  challenges: { title: "Official Challenges", subtitle: "Challenge Suite organizational work visible within your access scope.", icon: Building2 },
  assigned: { title: "Assigned to Me", subtitle: "Challenges where you have an active staff responsibility.", icon: ClipboardCheck },
  submissions: { title: "Submission Operations", subtitle: "Real participant submissions for official challenges within your scope.", icon: ShieldCheck },
  reviews: { title: "Review Queue", subtitle: "Official challenges requiring review work within your granted scope.", icon: ClipboardCheck },
  analytics: { title: "Enterprise Analytics", subtitle: "Recorded operational totals for Enterprise-owned challenges only.", icon: BarChart3 },
  finance: { title: "Enterprise Finance", subtitle: "Organizational settlement items kept separate from Personal Wallet and earnings.", icon: ReceiptText },
  sponsorships: { title: "Enterprise Sponsorships", subtitle: "Canonical sponsorship records connected to official challenges in your scope.", icon: Target },
  team: { title: "Enterprise Team", subtitle: "Authorized staff roles, scopes, assignments and membership status.", icon: UsersRound },
  activity: { title: "Enterprise Activity", subtitle: "Recorded operational history for official challenges in your scope.", icon: Activity },
};

function text(value: unknown, fallback: string) { return typeof value === "string" && value.trim() ? value : fallback; }
function money(value: unknown, currency: unknown) { return new Intl.NumberFormat("en-US", { style: "currency", currency: text(currency, "USD") }).format(Number(value ?? 0) / 100); }

export function EnterpriseSectionPage({ kind }: { kind: Kind }) {
  const [data, setData] = useState<Payload | null>(null);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");
  useEffect(() => { void apiRequest<Payload>(`/api/enterprise/workspace?section=${kind}`).then((result) => result.ok && result.data ? setData(result.data) : setError(result.message)); }, [kind]);
  const config = settings[kind]; const Icon = config.icon;
  const challenges = useMemo(() => (data?.challenges ?? []).filter((item) => kind !== "assigned" || item.assignment).filter((item) => kind !== "reviews" || item.needsAttention).filter((item) => `${item.title ?? ""} ${item.category ?? ""}`.toLowerCase().includes(search.toLowerCase())), [data, kind, search]);
  const records = kind === "submissions" ? data?.records ?? [] : kind === "finance" ? data?.finance ?? [] : kind === "sponsorships" ? data?.sponsorships ?? [] : kind === "team" ? data?.team ?? [] : kind === "activity" ? data?.activity ?? [] : [];
  const listMode = (["challenges", "assigned", "reviews"] as Kind[]).includes(kind);
  return <AppShell><div className="mx-auto max-w-7xl"><PageTitle title={config.title} subtitle={config.subtitle} icon={<Icon className="text-[var(--gold)]" />} />{error ? <Card className="mt-7 p-6"><h2 className="font-black text-slate-950">This Enterprise area is unavailable</h2><p className="mt-2 text-sm text-red-700">{error}</p><div className="mt-5 flex flex-wrap gap-3"><LinkButton href="/dashboard" variant="secondary">Personal Workspace</LinkButton><LinkButton href="/contact">Contact Support</LinkButton></div></Card> : !data ? <Card className="mt-7 h-72 animate-pulse" /> : <>
    {data.accessState === "obligation_only" ? <Card className="mt-7 border-amber-300 p-5"><h2 className="font-black text-slate-950">Obligation management only</h2><p className="mt-2 text-sm text-slate-600">Full Enterprise access has ended. Only existing assigned obligations remain available; new Enterprise work is disabled.</p></Card> : null}
    {kind === "analytics" ? <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(data.metrics).map(([label, value]) => <Card key={label} className="p-5"><p className="text-3xl font-black text-slate-950">{value}</p><p className="mt-1 text-sm capitalize text-slate-600">{label.replace(/([A-Z])/g, " $1")}</p></Card>)}</div> : null}
    {kind === "team" ? <div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{records.map((item) => <Card key={item.id} className="p-5"><p className="text-xs font-black uppercase text-amber-700">{text(item.status, "active").replaceAll("_", " ")}</p><h2 className="mt-2 text-lg font-black text-slate-950">{text(item.displayName, "Enterprise staff")}</h2><p className="mt-2 text-sm text-slate-600">{text(item.role, "operations").replaceAll("_", " ")} · {text(item.department, "Operations")}</p><p className="mt-1 text-xs text-slate-500">{text(item.scope, "assigned_only").replaceAll("_", " ")}</p></Card>)}{!records.length ? <Card className="p-6 text-sm text-slate-600">No Enterprise staff records are available in this scope.</Card> : null}</div> : null}
    {kind === "finance" ? <div className="mt-7 grid gap-4">{records.map((item) => <Card key={item.id} className="grid gap-3 p-5 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase text-slate-500">Amount</p><p className="mt-1 font-black text-slate-950">{money(item.amountCents, item.currency)}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Status</p><p className="mt-1 text-sm text-slate-700">{text(item.status, "requires review").replaceAll("_", " ")}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Challenge</p><LinkButton href={`/challenges/${text(item.challengeId, "missing")}/manage`} variant="secondary" className="mt-1">Open Operations</LinkButton></div></Card>)}{!records.length ? <Card className="p-6 text-sm text-slate-600">No Enterprise settlement items require attention.</Card> : null}</div> : null}
    {kind === "sponsorships" ? <div className="mt-7 grid gap-4 md:grid-cols-2">{records.map((item) => <Card key={item.id} className="p-5"><p className="text-xs font-black uppercase text-amber-700">{text(item.status, "recorded").replaceAll("_", " ")}</p><h2 className="mt-2 text-lg font-black text-slate-950">{text(item.title ?? item.campaignTitle, "Official challenge sponsorship")}</h2><p className="mt-2 text-sm text-slate-600">Sponsor funds remain separately attributed and never settle to staff Personal Wallets.</p><LinkButton href={`/challenges/${text(item.challengeId, "missing")}/manage`} className="mt-5">Open Sponsorship</LinkButton></Card>)}{!records.length ? <Card className="p-6 text-sm text-slate-600">No sponsorship records exist for challenges in this scope.</Card> : null}</div> : null}
    {kind === "submissions" ? <div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{records.map((item) => <Card key={item.id} className="p-5"><p className="text-xs font-black uppercase text-amber-700">{text(item.status, "submitted").replaceAll("_", " ")}</p><h2 className="mt-2 text-lg font-black text-slate-950">{text(item.title, "Participant submission")}</h2><LinkButton href={`/challenges/${text(item.challengeId, "missing")}/manage?tab=submissions&focus=${item.id}`} className="mt-5">Review Submission</LinkButton></Card>)}{!records.length ? <Card className="p-6 text-sm text-slate-600">No submissions are available in this Enterprise scope.</Card> : null}</div> : null}
    {kind === "activity" ? <div className="mt-7 grid gap-3">{records.map((item) => <Card key={item.id} className="p-5"><p className="font-black text-slate-950">{text(item.action, "Enterprise activity").replaceAll("_", " ")}</p><p className="mt-1 text-sm text-slate-600">{text(item.reason, "Recorded operational action")}</p><p className="mt-2 text-xs text-slate-500">{text(item.createdAt, "Time unavailable")}</p></Card>)}{!records.length ? <Card className="p-6 text-sm text-slate-600">No recorded Enterprise activity is available in this scope.</Card> : null}</div> : null}
    {listMode ? <><div className="mt-7 max-w-md"><label className="relative block"><Search className="absolute left-3 top-3.5 text-slate-400" size={18} /><span className="sr-only">Search official challenges</span><input className={`${inputClass} pl-10`} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search official challenges" /></label></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{challenges.map((item) => <Card key={item.id} className="p-5"><p className="text-xs font-black uppercase text-amber-700">{text(item.displayStatus, "Draft")}</p><h2 className="mt-2 text-lg font-black text-slate-950">{text(item.title, "Untitled challenge")}</h2><p className="mt-1 text-sm text-slate-600">{text(item.assignment ?? item.category, "Official challenge")}</p><LinkButton href={`/challenges/${item.id}/manage`} className="mt-5">Open Operations</LinkButton></Card>)}{!challenges.length ? <Card className="p-6 text-sm text-slate-600">{kind === "assigned" ? "No work is assigned to you right now." : kind === "reviews" ? "No reviews require attention in this scope." : "No official challenges are available in this Enterprise scope."}</Card> : null}</div></> : null}
  </>}</div></AppShell>;
}
