"use client";

import { Check, ChevronDown, Search, X } from "lucide-react";
import { useId, useMemo, useState } from "react";
import { inputClass } from "@/components/ui";
import { COUNTRY_OPTIONS, type CanonicalOption } from "@/lib/forms/canonical-options";
import type { CanonicalEntityType } from "@/lib/forms/field-control-registry";

type SearchSelectProps = { label: string; value: string; options: readonly CanonicalOption[]; onChange: (value: string) => void; placeholder?: string; disabled?: boolean; error?: string };
export function SearchSelect({ label, value, options, onChange, placeholder = "Select an option", disabled, error }: SearchSelectProps) {
  const id = useId(); const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [activeIndex, setActiveIndex] = useState(0);
  const selected = options.find((option) => String(option.value) === value);
  const filtered = useMemo(() => options.filter((option) => option.label.toLowerCase().includes(query.trim().toLowerCase())), [options, query]);
  const choose = (index: number) => { const option = filtered[index]; if (!option) return; onChange(String(option.value)); setOpen(false); setQuery(""); };
  return <div><label htmlFor={id} className="mb-2.5 block text-sm font-bold text-[var(--foreground)]">{label}</label><div className="relative"><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-3.5 text-[var(--muted)]" size={17} /><input id={id} className={`${inputClass} px-10`} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={`${id}-options`} aria-activedescendant={open && filtered[activeIndex] ? `${id}-option-${activeIndex}` : undefined} aria-invalid={Boolean(error)} disabled={disabled} value={open ? query : selected?.label ?? ""} placeholder={placeholder} onFocus={() => { setOpen(true); setQuery(""); setActiveIndex(0); }} onChange={(event) => { setQuery(event.target.value); setOpen(true); setActiveIndex(0); }} onKeyDown={(event) => { if (event.key === "Escape") setOpen(false); if (event.key === "ArrowDown") { event.preventDefault(); setOpen(true); setActiveIndex((index) => Math.min(index + 1, Math.max(filtered.length - 1, 0))); } if (event.key === "ArrowUp") { event.preventDefault(); setActiveIndex((index) => Math.max(index - 1, 0)); } if (event.key === "Enter") { event.preventDefault(); choose(activeIndex); } }} /><ChevronDown aria-hidden="true" className="pointer-events-none absolute right-3 top-3.5 text-[var(--muted)]" size={17} />{open && !disabled ? <div id={`${id}-options`} role="listbox" className="absolute z-40 mt-2 max-h-64 w-full overflow-y-auto rounded-[8px] border border-[var(--line)] bg-[var(--panel)] p-2 shadow-xl">{filtered.length ? filtered.map((option, index) => <button id={`${id}-option-${index}`} key={String(option.value)} type="button" role="option" aria-selected={String(option.value) === value} className={`flex min-h-11 w-full items-center justify-between rounded-[8px] px-3 text-left text-sm hover:bg-amber-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-500 ${index === activeIndex ? "bg-amber-50" : ""}`} onMouseEnter={() => setActiveIndex(index)} onMouseDown={(event) => event.preventDefault()} onClick={() => choose(index)}><span>{option.label}</span>{String(option.value) === value ? <Check size={16} /> : null}</button>) : <p className="px-3 py-4 text-sm text-[var(--muted)]">No matching options.</p>}</div> : null}</div>{error ? <p className="mt-2 text-sm font-bold text-red-700">{error}</p> : null}</div>;
}

type MultiSelectProps = { label: string; values: string[]; options: readonly CanonicalOption[]; onChange: (values: string[]) => void; maximum?: number; placeholder?: string; disabled?: boolean };
export function MultiSelect({ label, values, options, onChange, maximum, placeholder = "Search options", disabled }: MultiSelectProps) {
  const id = useId(); const [query, setQuery] = useState(""); const selected = new Set(values); const filtered = options.filter((option) => option.label.toLowerCase().includes(query.trim().toLowerCase())); const atLimit = maximum !== undefined && values.length >= maximum;
  return <div><label htmlFor={id} className="mb-2.5 block text-sm font-bold text-[var(--foreground)]">{label}</label><div className="relative"><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-3.5 text-[var(--muted)]" size={17} /><input id={id} className={`${inputClass} pl-10`} role="combobox" aria-controls={`${id}-options`} aria-expanded="true" disabled={disabled} value={query} onChange={(event) => setQuery(event.target.value)} placeholder={placeholder} /></div><div id={`${id}-options`} role="listbox" aria-multiselectable="true" className="mt-2 max-h-52 overflow-y-auto rounded-[8px] border border-[var(--line)] bg-[var(--panel)] p-2">{filtered.map((option) => { const value = String(option.value); const checked = selected.has(value); return <button key={value} type="button" role="option" aria-selected={checked} disabled={disabled || (!checked && atLimit)} className="flex min-h-11 w-full items-center justify-between rounded-[8px] px-3 text-left text-sm hover:bg-amber-50 disabled:opacity-50" onClick={() => onChange(checked ? values.filter((item) => item !== value) : [...values, value])}><span>{option.label}</span>{checked ? <Check size={16} /> : null}</button>; })}</div><div className="mt-3 flex flex-wrap gap-2">{values.map((value) => { const option = options.find((item) => String(item.value) === value); return <span key={value} className="inline-flex items-center gap-2 rounded-full border border-[var(--line)] bg-[var(--panel-2)] px-3 py-2 text-xs font-bold">{option?.label ?? value}<button type="button" disabled={disabled} onClick={() => onChange(values.filter((item) => item !== value))} aria-label={`Remove ${option?.label ?? value}`}><X size={14} /></button></span>; })}</div>{maximum !== undefined ? <p className="mt-2 text-xs text-[var(--muted)]">Choose up to {maximum}. {values.length} selected.</p> : null}</div>;
}

export type EntityPickerOption = { id: string; label: string; description?: string };
type EntityPickerProps = { label: string; entityType: CanonicalEntityType; query: string; onQueryChange: (value: string) => void; options: EntityPickerOption[]; value?: string; onChange: (value: string | null) => void; loading?: boolean; disabled?: boolean };
export function EntityPicker({ label, entityType, query, onQueryChange, options, value, onChange, loading, disabled }: EntityPickerProps) { const id = useId(); return <div data-entity-type={entityType}><label htmlFor={id} className="mb-2.5 block text-sm font-bold text-[var(--foreground)]">{label}</label><input id={id} className={inputClass} role="combobox" aria-expanded={options.length > 0} aria-controls={`${id}-entities`} value={query} disabled={disabled} onChange={(event) => onQueryChange(event.target.value)} placeholder={`Search ${entityType.replaceAll("_", " ")}`} />{loading ? <p className="mt-2 text-sm text-[var(--muted)]">Searching...</p> : null}{options.length ? <div id={`${id}-entities`} role="listbox" className="mt-2 rounded-[8px] border border-[var(--line)] bg-[var(--panel)] p-2">{options.map((option) => <button key={option.id} type="button" role="option" aria-selected={option.id === value} className="flex min-h-11 w-full flex-col rounded-[8px] px-3 py-2 text-left hover:bg-amber-50" onClick={() => onChange(option.id)}><b>{option.label}</b>{option.description ? <span className="text-xs text-[var(--muted)]">{option.description}</span> : null}</button>)}</div> : null}</div>; }
export function MultiEntityPicker(props: Omit<EntityPickerProps, "value" | "onChange"> & { values: string[]; onChange: (values: string[]) => void }) { const { values, onChange, options, ...rest } = props; return <div><EntityPicker {...rest} options={options.filter((option) => !values.includes(option.id))} value="" onChange={(value) => { if (value && !values.includes(value)) onChange([...values, value]); }} /><div className="mt-3 flex flex-wrap gap-2">{values.map((value) => { const option = options.find((item) => item.id === value); return <span key={value} className="inline-flex items-center gap-2 rounded-full border border-[var(--line)] bg-[var(--panel-2)] px-3 py-2 text-xs font-bold">{option?.label ?? value}<button type="button" disabled={rest.disabled} onClick={() => onChange(values.filter((item) => item !== value))} aria-label={`Remove ${option?.label ?? value}`}><X size={14} /></button></span>; })}</div></div>; }
export function CurrencyInput({ label, value, onChange, currency = "USD", min = 0 }: { label: string; value: string; onChange: (value: string) => void; currency?: string; min?: number }) { const id = useId(); return <div><label htmlFor={id} className="mb-2.5 block text-sm font-bold text-[var(--foreground)]">{label}</label><div className="relative"><span className="pointer-events-none absolute left-4 top-3.5 text-sm font-bold text-[var(--muted)]">{currency}</span><input id={id} className={`${inputClass} pl-14`} type="number" inputMode="decimal" min={min} step="0.01" value={value} onChange={(event) => onChange(event.target.value)} /></div></div>; }

export function ChoiceCards<T extends string>({ label, value, options, onChange, disabled }: { label: string; value: T; options: readonly CanonicalOption<T>[]; onChange: (value: T) => void; disabled?: boolean }) { return <fieldset><legend className="mb-2.5 text-sm font-bold text-[var(--foreground)]">{label}</legend><div className="grid gap-3 sm:grid-cols-2">{options.map((option) => <label key={option.value} className={`flex min-h-11 cursor-pointer items-center gap-3 rounded-[8px] border p-3 text-sm font-bold ${value === option.value ? "border-amber-500 bg-amber-50" : "border-[var(--line)] bg-[var(--panel)]"}`}><input type="radio" name={label} value={option.value} checked={value === option.value} disabled={disabled} onChange={() => onChange(option.value)} /><span>{option.label}</span></label>)}</div></fieldset>; }

export function NumberInput({ label, value, onChange, min, max, step = 1, error }: { label: string; value: string | number; onChange: (value: string) => void; min?: number; max?: number; step?: number; error?: string }) { const id = useId(); return <div><label htmlFor={id} className="mb-2.5 block text-sm font-bold text-[var(--foreground)]">{label}</label><input id={id} className={inputClass} type="number" inputMode={step % 1 === 0 ? "numeric" : "decimal"} min={min} max={max} step={step} value={value} aria-invalid={Boolean(error)} onChange={(event) => onChange(event.target.value)} />{error ? <p className="mt-2 text-sm font-bold text-red-700">{error}</p> : null}</div>; }

export function DatePicker({ label, value, onChange, min, max }: { label: string; value: string; onChange: (value: string) => void; min?: string; max?: string }) { const id = useId(); return <div><label htmlFor={id} className="mb-2.5 block text-sm font-bold text-[var(--foreground)]">{label}</label><input id={id} className={inputClass} type="date" value={value} min={min} max={max} onChange={(event) => onChange(event.target.value)} /></div>; }
export function DateTimePicker({ label, value, onChange, min, max }: { label: string; value: string; onChange: (value: string) => void; min?: string; max?: string }) { const id = useId(); return <div><label htmlFor={id} className="mb-2.5 block text-sm font-bold text-[var(--foreground)]">{label}</label><input id={id} className={inputClass} type="datetime-local" value={value} min={min} max={max} onChange={(event) => onChange(event.target.value)} /></div>; }

export function LocationPicker({ country, onCountryChange, region, onRegionChange, regionOptions = [] }: { country: string; onCountryChange: (value: string) => void; region: string; onRegionChange: (value: string) => void; regionOptions?: readonly CanonicalOption[] }) { return <div className="grid gap-4 sm:grid-cols-2"><SearchSelect label="Country" value={country} options={COUNTRY_OPTIONS} onChange={(value) => { onCountryChange(value); onRegionChange(""); }} /><SearchSelect label="State / region" value={region} options={regionOptions} onChange={onRegionChange} disabled={!country || !regionOptions.length} placeholder={country ? "Select a state or region" : "Choose a country first"} /></div>; }
