"use client";
import { useState } from "react";
import { LifeBuoy, Send } from "lucide-react";
import { apiRequest } from "@/lib/api/client";
import { Button, Card, Field, PageTitle, inputClass, textareaClass } from "@/components/ui";

export function SupportTicketForm() {
  const [category, setCategory] = useState("account"); const [subject, setSubject] = useState(""); const [description, setDescription] = useState(""); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  async function submit() { setSaving(true); const result = await apiRequest("/api/support/tickets", { method: "POST", body: JSON.stringify({ category, subject, description, prioritySuggestion: "normal", attachmentPaths: [], contactPreference: "in_app" }) }); setNotice(result.message); if (result.ok) { setSubject(""); setDescription(""); } setSaving(false); }
  return <><PageTitle title="Contact Support" subtitle="Create a support ticket linked to your authenticated account." icon={<LifeBuoy className="text-[var(--gold)]" />} /><Card className="mt-7 p-6"><div className="grid gap-5"><Field label="Category"><select className={inputClass} value={category} onChange={(event) => setCategory(event.target.value)}>{["account", "challenge", "payment", "payout", "refund", "submission", "voting", "sponsor", "event", "tournament", "technical_issue", "safety_concern", "other"].map((value) => <option value={value} key={value}>{value.replaceAll("_", " ")}</option>)}</select></Field><Field label="Subject"><input className={inputClass} value={subject} onChange={(event) => setSubject(event.target.value)} maxLength={160} /></Field><Field label="Description"><textarea className={textareaClass} value={description} onChange={(event) => setDescription(event.target.value)} maxLength={5000} rows={8} /></Field><p className="text-sm text-slate-400">Attachments must use Challenge Suite native upload storage. External attachment URLs are not accepted.</p><Button onClick={() => void submit()} disabled={saving || subject.length < 5 || description.length < 20}><Send size={17} /> {saving ? "Submitting..." : "Submit Ticket"}</Button>{notice ? <p role="status" className="text-sm">{notice}</p> : null}</div></Card></>;
}
