"use client";

import { useState } from "react";
import { CheckCircle2, Save, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { Button, Card, Field, inputClass, LinkButton, PageTitle, textareaClass } from "@/components/ui";
import { createChallenge } from "@/lib/api/services";
import { MediaUploadField } from "@/components/media-upload-field";
import { challengeDraftMediaPath } from "@/lib/media-upload-paths";

const steps = ["Basic Details", "Visibility", "Format & Rounds", "Participants", "Submissions", "Voting", "Judging", "Prize Foundation", "Media & Branding", "Sponsor Readiness", "Review & Publish"];
const options = {  visibilityMode: ["public", "invite_only", "access_code", "approved_list", "hidden", "public_preview"],
  format: ["single_round", "multi_round", "knockout", "leaderboard", "judge_reviewed", "submission_voting", "registration_only"],
  winnerSelection: ["highest_votes", "judge_selection", "hybrid", "manual"]
};
function dateInput(days: number) { const date = new Date(); date.setDate(date.getDate() + days); return `${date.toISOString().slice(0, 10)}T12:00`; }
const initial = {
  title: "", description: "", category: "Creative", coverImageUrl: "", coverImagePath: "", competitionType: "Online Challenge",
  visibilityMode: "public", accessCode: "", format: "single_round", maxParticipants: "50", minimumAge: "0", locationRestriction: "",
  approvalRequired: true, registrationQuestions: "", termsRequired: true, submissionType: "image", maxFileSizeMb: "25",
  maxVideoDurationSeconds: "180", allowResubmission: false, requireSubmissionApproval: true, submissionGuidelines: "",
  startsAt: dateInput(1), submissionDeadline: dateInput(5), votingStartsAt: dateInput(5), votingDeadline: dateInput(6), endsAt: dateInput(7),
  allowFreeVotes: true, votesPerUserPerDay: "1", allowDoroCoinVotes: true, weightedVotes: false, showVoteCount: true, showLeaderboard: true,
  winnerSelection: "highest_votes", multipleWinners: false, placementMode: "top_three", prizeDescription: "", prizeSponsor: "",
  prizeTerms: "", manualPayoutNote: "", promoImageUrl: "", promoImagePath: "", trailerVideoUrl: "", trailerVideoPath: "", eventLogoUrl: "", sponsorBannerUrl: "",
  brandColor: "#F5B700", allowSponsorInterest: false, showSponsorRequestButton: false, sponsorCategories: "",
  sponsorVisibilityAreas: "Challenge page\nWinner announcement", launchMode: "draft",
  venueName: "", eventAddress: "", eventCity: "", eventState: "", eventCountry: "",
  externalLiveUrl: "", externalLiveProvider: "", externalLiveStatus: "not_ready", externalLiveOpensAt: "", externalLiveCtaLabel: "Watch live on partner site",
  tournamentType: "knockout"
};
type Form = typeof initial;

export function HostCompetitionWizard({ initialCompetitionType }: { initialCompetitionType?: string } = {}) {
  if (initialCompetitionType === "Hybrid Competition") return <HybridCompetitionBuilder />;
  const auth = useAuth();
  const [step, setStep] = useState(0), [form, setForm] = useState(() => ({ ...initial, competitionType: initialCompetitionType ?? initial.competitionType })), [saving, setSaving] = useState(false);
  const [error, setError] = useState(""), [createdId, setCreatedId] = useState("");
  const update = <K extends keyof Form>(key: K, value: Form[K]) => { setForm((current) => ({ ...current, [key]: value })); setError(""); };
  const validate = () => {
    if (step === 0 && (form.title.trim().length < 3 || form.description.trim().length < 10)) return "Add a title and a description of at least 10 characters.";
    if (step === 1 && form.visibilityMode === "access_code" && !form.accessCode.trim()) return "Add an access code.";
    if (Number(form.maxParticipants) < 2) return "Maximum participants must be at least 2.";
    if (new Date(form.votingStartsAt) < new Date(form.submissionDeadline)) return "Voting cannot begin before submissions close.";
    if (new Date(form.votingDeadline) > new Date(form.endsAt)) return "Voting must end by the competition end date.";
    return "";
  };
  const payload = (publish: boolean) => {
    const live = ["Live Event", "Hybrid Competition"].includes(form.competitionType);
    const lines = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);
    return {
      title: form.title, description: form.description, category: form.category, type: form.competitionType,
      visibility: ["public", "public_preview"].includes(form.visibilityMode) ? "public" : "private",
      acceptedSubmissionTypes: [form.submissionType === "video" ? "video" : "image"], competitionFormat: form.format, bestOf: "1 Rounder",
      startsAt: form.startsAt, endsAt: form.endsAt, submissionDeadline: form.submissionDeadline, votingStartsAt: form.votingStartsAt,
      votingDeadline: form.votingDeadline, standardRules: "Respect participants.\nSubmit original work.\nFollow published competition policies.",
      policyTerms: form.prizeTerms || "Participation remains subject to platform review.", challengeGuidelines: form.submissionGuidelines,
      coverImageUrl: form.coverImageUrl, coverImagePath: form.coverImagePath, promoImageUrl: form.promoImageUrl, promoImagePath: form.promoImagePath, trailerVideoUrl: form.trailerVideoUrl, trailerVideoPath: form.trailerVideoPath, promoVideoUrl: "", promoVideoPath: "",
      prizeType: form.prizeDescription ? "physical_product" : "bragging_rights", prizeTitle: form.prizeDescription ? "Competition prize" : "",
      prizeDescription: form.prizeDescription, prizeValue: 0, prizeDeliveryNotes: form.manualPayoutNote,
      votingSettings: { allowFreeVotes: form.allowFreeVotes, allowDoroCoinVotes: form.allowDoroCoinVotes, weightedVotes: form.weightedVotes },
      requiresSubmissionApproval: form.requireSubmissionApproval, sponsorEnabled: form.allowSponsorInterest, sponsorSlots: form.allowSponsorInterest ? 3 : 0,
      minimumSponsorshipAmount: 0, sponsorPlacementOptions: lines(form.sponsorVisibilityAreas), sponsorPackages: [],
      isLiveEvent: live, venueName: live ? form.venueName || "Venue pending" : "", eventAddress: live ? form.eventAddress : "", eventCity: live ? form.eventCity || form.locationRestriction || "Location pending" : "",
      eventState: live ? form.eventState : "", eventCountry: live ? form.eventCountry || "Location pending" : "", eventMapUrl: "", eventCapacity: Number(form.maxParticipants),
      externalLiveUrl: form.externalLiveUrl, externalLiveProvider: form.externalLiveProvider, externalLiveStatus: form.externalLiveStatus,
      externalLiveOpensAt: form.externalLiveOpensAt, externalLiveCtaLabel: form.externalLiveCtaLabel,
      tournamentType: form.competitionType === "Tournament" ? form.tournamentType : "none", tournamentStages: form.competitionType === "Tournament" ? [
        { id: "registration", name: "Registration", order: 1, status: "draft", advancementRule: "Approve participants before round one." },
        { id: "round_1", name: "Round 1", order: 2, status: "draft", advancementRule: "Collect submissions and votes or judge scores." },
        { id: "final", name: "Final", order: 3, status: "draft", advancementRule: "Host confirms results, then admin reviews winner announcement." }
      ] : [], divisionFormat: 2, maxParticipants: Math.min(50, Number(form.maxParticipants)),
      scoringMode: "best_of", bestOfRounds: 3, pointsToWin: 10, timerEnabled: false, timerDuration: 0, roundDuration: 0,
      judgeScoringEnabled: ["judge_selection", "hybrid"].includes(form.winnerSelection),
      hostOperations: {
        visibilityMode: form.visibilityMode, accessCode: form.accessCode, format: form.format, minimumAge: Number(form.minimumAge),
        locationRestriction: form.locationRestriction, approvalRequired: form.approvalRequired, registrationQuestions: lines(form.registrationQuestions),
        termsRequired: form.termsRequired, submissionType: form.submissionType, maxFileSizeMb: Number(form.maxFileSizeMb),
        maxVideoDurationSeconds: Number(form.maxVideoDurationSeconds), allowResubmission: form.allowResubmission,
        votesPerUserPerDay: Number(form.votesPerUserPerDay), showVoteCount: form.showVoteCount, showLeaderboard: form.showLeaderboard,
        winnerSelection: form.winnerSelection, multipleWinners: form.multipleWinners, placementMode: form.placementMode,
        prizeSponsor: form.prizeSponsor, manualPayoutNote: form.manualPayoutNote, eventLogoUrl: form.eventLogoUrl,
        sponsorBannerUrl: form.sponsorBannerUrl, brandColor: form.brandColor, allowSponsorInterest: form.allowSponsorInterest,
        showSponsorRequestButton: form.showSponsorRequestButton, sponsorCategories: lines(form.sponsorCategories),
        sponsorVisibilityAreas: lines(form.sponsorVisibilityAreas), launchMode: form.launchMode
      }, publish
    };
  };
  async function submit(publish: boolean) {
    const problem = validate(); if (problem) return setError(problem);
    setSaving(true); const result = await createChallenge(payload(publish)); setSaving(false);
    if (!result.ok) return setError(result.message || "Competition could not be saved.");
    setCreatedId(((result.data?.challenge as { id?: string } | undefined)?.id) || "saved");
  }
  if (createdId) return <AppShell><Card className="mx-auto max-w-2xl p-8 text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-400" /><h1 className="mt-5 text-3xl font-black">Competition saved</h1><p className="mt-3 text-slate-300">Advanced events, tournaments, sponsor settings, and prizes remain subject to review. No money movement was enabled.</p><div className="mt-6 flex justify-center gap-3"><LinkButton href={createdId === "saved" ? "/my-challenges" : `/challenges/${createdId}`}>View Competition</LinkButton><LinkButton href="/dashboard/host" variant="secondary">Host Control Center</LinkButton></div></Card></AppShell>;
  return <AppShell><div className="mx-auto max-w-6xl"><PageTitle title={form.competitionType === "Private Challenge" ? "Create Private Challenge" : form.competitionType === "Live Event" ? "Create Live Event" : form.competitionType === "Tournament" ? "Create Tournament Challenge" : "Create Challenge"} subtitle={form.competitionType === "Private Challenge" ? "Set invite access, participant approval, dates, media, and review-safe rules." : form.competitionType === "Live Event" ? "Build a physical-first event with venue, schedule, participant, media, and external livestream foundations." : form.competitionType === "Tournament" ? "Plan a multi-stage tournament with rounds, advancement rules, voting or judging, finals, and review-safe winner confirmation." : "Build a normal online challenge. Private, live, tournament, and hybrid builders now live in their own sections."} /><Card className="mt-6 p-4 sm:p-6">
    <div className="flex gap-2 overflow-x-auto pb-2">{steps.map((label, index) => <button key={label} onClick={() => index <= step && setStep(index)} className={`min-h-11 min-w-40 rounded-[8px] px-3 text-left text-xs font-black ${index === step ? "bg-[var(--gold)] text-black" : "bg-[#191919] text-slate-300"}`}>{index + 1}. {label}</button>)}</div>
    <div className="mt-8 min-h-[470px]"><WizardStep step={step} form={form} update={update} userId={auth.user?.uid ?? "anonymous"} /></div>
    {error ? <p className="mt-5 rounded-[8px] bg-red-950/50 p-4 text-red-200">{error}</p> : null}
    <div className="mt-8 flex flex-col gap-3 border-t border-white/10 pt-6 sm:flex-row sm:justify-between"><Button variant="secondary" onClick={() => submit(false)} disabled={saving}><Save size={17} /> Save Draft</Button><div className="flex gap-3"><Button variant="ghost" disabled={step === 0} onClick={() => setStep((value) => value - 1)}>Back</Button>{step < 10 ? <Button onClick={() => { const problem = validate(); problem ? setError(problem) : setStep((value) => value + 1); }}>Next</Button> : <Button onClick={() => submit(form.launchMode !== "draft")} disabled={saving}>{saving ? "Saving..." : form.launchMode === "schedule" ? "Schedule Launch" : "Publish Competition"}</Button>}</div></div>
  </Card></div></AppShell>;
}

function WizardStep({ step, form, update, userId }: { step: number; form: Form; update: <K extends keyof Form>(key: K, value: Form[K]) => void; userId: string }) {
  const check = (key: keyof Form, label: string) => <label className="flex min-h-12 items-center gap-3 rounded-[8px] border border-white/10 px-4 py-3 font-bold"><input type="checkbox" checked={Boolean(form[key])} onChange={(event) => update(key, event.target.checked as never)} />{label}</label>;
  const selectButtons = (key: "visibilityMode" | "format" | "winnerSelection", values: string[]) => <Grid>{values.map((value) => <Button key={value} variant={form[key] === value ? "primary" : "secondary"} onClick={() => update(key, value)}>{value.replaceAll("_", " ")}</Button>)}</Grid>;
  if (step === 0) return <Step title="Basic Details"><Field label="Title"><input className={inputClass} value={form.title} onChange={(e) => update("title", e.target.value)} /></Field><Field label="Description"><textarea className={textareaClass} value={form.description} onChange={(e) => update("description", e.target.value)} /></Field><Grid><Field label="Category"><input className={inputClass} value={form.category} onChange={(e) => update("category", e.target.value)} /></Field><MediaUploadField label="Cover Image" value={form.coverImageUrl} onChange={(url, metadata) => { update("coverImageUrl", url); update("coverImagePath", metadata?.path ?? ""); }} storagePath={challengeDraftMediaPath(userId, "banner")} kind="image" buttonLabel="Upload Cover Image" /></Grid><SpecializedFlowNotice competitionType={form.competitionType} /></Step>;
  if (step === 1) return <Step title="Visibility">{selectButtons("visibilityMode", options.visibilityMode)}{form.visibilityMode === "access_code" ? <Field label="Access Code"><input className={inputClass} value={form.accessCode} onChange={(e) => update("accessCode", e.target.value)} /></Field> : null}</Step>;
  if (step === 2) return <Step title="Format & Rounds">{selectButtons("format", options.format)}{form.competitionType === "Tournament" ? <div className="grid gap-4 sm:grid-cols-2"><Field label="Tournament Type"><select className={inputClass} value={form.tournamentType} onChange={(e) => update("tournamentType", e.target.value)}>{["knockout", "bracket", "league_table", "audition_to_final", "group_stage_to_final", "custom_rounds"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></Field><Card className="p-4 text-sm text-slate-300">Tournaments are multi-stage competitions: registration, rounds, advancement, final, winner confirmation, and admin review. Bracket execution remains a foundation.</Card></div> : null}</Step>;
  if (step === 3) return <Step title="Participants & Registration"><Grid><Field label="Maximum Participants"><input className={inputClass} type="number" min="2" max="50" value={form.maxParticipants} onChange={(e) => update("maxParticipants", e.target.value)} /></Field><Field label="Minimum Age"><input className={inputClass} type="number" min="0" value={form.minimumAge} onChange={(e) => update("minimumAge", e.target.value)} /></Field></Grid><Field label="Location Restriction"><input className={inputClass} value={form.locationRestriction} onChange={(e) => update("locationRestriction", e.target.value)} /></Field>{["Live Event", "Hybrid Competition"].includes(form.competitionType) ? <Grid><Field label="Venue"><input className={inputClass} value={form.venueName} onChange={(e) => update("venueName", e.target.value)} /></Field><Field label="Address"><input className={inputClass} value={form.eventAddress} onChange={(e) => update("eventAddress", e.target.value)} /></Field><Field label="City"><input className={inputClass} value={form.eventCity} onChange={(e) => update("eventCity", e.target.value)} /></Field><Field label="Country"><input className={inputClass} value={form.eventCountry} onChange={(e) => update("eventCountry", e.target.value)} /></Field><Field label="External Livestream URL"><input className={inputClass} value={form.externalLiveUrl} onChange={(e) => update("externalLiveUrl", e.target.value)} placeholder="https://partner-site.com/live" /></Field><Field label="External Live Status"><select className={inputClass} value={form.externalLiveStatus} onChange={(e) => update("externalLiveStatus", e.target.value)}>{["not_ready", "scheduled", "live", "ended"].map((value) => <option key={value}>{value}</option>)}</select></Field></Grid> : null}<Field label="Registration Questions (one per line)"><textarea className={textareaClass} value={form.registrationQuestions} onChange={(e) => update("registrationQuestions", e.target.value)} /></Field><Grid>{check("approvalRequired", "Participant approval required")}{check("termsRequired", "Terms agreement required")}</Grid><Card className="p-4 text-sm text-slate-300">Live events are physical-first. Challenge Suite stores registration, venue, schedule, lineup, voting/results connection, and external livestream link/status only.</Card></Step>;
  if (step === 4) return <Step title="Submission Settings"><Grid><Field label="Submission Type"><select className={inputClass} value={form.submissionType} onChange={(e) => update("submissionType", e.target.value)}>{["image", "video", "text", "link"].map((v) => <option key={v}>{v}</option>)}</select></Field><Field label="Max File Size (MB)"><input className={inputClass} type="number" value={form.maxFileSizeMb} onChange={(e) => update("maxFileSizeMb", e.target.value)} /></Field><Field label="Max Video Duration (seconds)"><input className={inputClass} type="number" value={form.maxVideoDurationSeconds} onChange={(e) => update("maxVideoDurationSeconds", e.target.value)} /></Field><Field label="Submission Deadline"><input className={inputClass} type="datetime-local" value={form.submissionDeadline} onChange={(e) => update("submissionDeadline", e.target.value)} /></Field></Grid><Field label="Submission Guidelines"><textarea className={textareaClass} value={form.submissionGuidelines} onChange={(e) => update("submissionGuidelines", e.target.value)} /></Field><Grid>{check("allowResubmission", "Allow resubmission")}{check("requireSubmissionApproval", "Approve before public display")}</Grid></Step>;
  if (step === 5) return <Step title="Voting Settings"><Grid><Field label="Voting Starts"><input className={inputClass} type="datetime-local" value={form.votingStartsAt} onChange={(e) => update("votingStartsAt", e.target.value)} /></Field><Field label="Voting Ends"><input className={inputClass} type="datetime-local" value={form.votingDeadline} onChange={(e) => update("votingDeadline", e.target.value)} /></Field><Field label="Votes Per User / Day"><input className={inputClass} type="number" min="0" value={form.votesPerUserPerDay} onChange={(e) => update("votesPerUserPerDay", e.target.value)} /></Field><Field label="Competition End"><input className={inputClass} type="datetime-local" value={form.endsAt} onChange={(e) => update("endsAt", e.target.value)} /></Field></Grid><Grid>{check("allowFreeVotes", "Allow free votes")}{check("allowDoroCoinVotes", "Allow DoroCoin votes")}{check("weightedVotes", "Vote multiplier")}{check("showVoteCount", "Show vote count")}{check("showLeaderboard", "Show leaderboard")}</Grid></Step>;
  if (step === 6) return <Step title="Judging & Winner Selection">{selectButtons("winnerSelection", options.winnerSelection)}<Grid>{check("multipleWinners", "Allow multiple winners")}<Field label="Placement"><select className={inputClass} value={form.placementMode} onChange={(e) => update("placementMode", e.target.value)}><option value="single">Single winner</option><option value="top_three">1st / 2nd / 3rd</option><option value="categories">Category winners</option></select></Field></Grid></Step>;
  if (step === 7) return <Step title="Prize Foundation"><Field label="Prize Description"><textarea className={textareaClass} value={form.prizeDescription} onChange={(e) => update("prizeDescription", e.target.value)} /></Field><Grid><Field label="Prize Sponsor"><input className={inputClass} value={form.prizeSponsor} onChange={(e) => update("prizeSponsor", e.target.value)} /></Field><Field label="Manual Payout Note"><input className={inputClass} value={form.manualPayoutNote} onChange={(e) => update("manualPayoutNote", e.target.value)} /></Field></Grid><Field label="Prize Terms"><textarea className={textareaClass} value={form.prizeTerms} onChange={(e) => update("prizeTerms", e.target.value)} /></Field><Card className="border-yellow-500/30 p-4 text-sm text-yellow-100"><ShieldCheck className="mb-2" />Automatic cash payouts and prize-pool releases are not active yet.</Card></Step>;
  if (step === 8) return <Step title="Media & Branding"><Grid><MediaUploadField label="Promo Flyer" value={form.promoImageUrl} onChange={(url, metadata) => { update("promoImageUrl", url); update("promoImagePath", metadata?.path ?? ""); }} storagePath={challengeDraftMediaPath(userId, "gallery")} kind="image" buttonLabel="Upload Promo Image" /><MediaUploadField label="Trailer Video" value={form.trailerVideoUrl} onChange={(url, metadata) => { update("trailerVideoUrl", url); update("trailerVideoPath", metadata?.path ?? ""); }} storagePath={challengeDraftMediaPath(userId, "video")} kind="video" buttonLabel="Upload Trailer Video" /><MediaUploadField label="Event Logo" value={form.eventLogoUrl} onChange={(url) => update("eventLogoUrl", url)} storagePath={challengeDraftMediaPath(userId, "gallery")} kind="image" buttonLabel="Upload Event Logo" /><MediaUploadField label="Sponsor Banner" value={form.sponsorBannerUrl} onChange={(url) => update("sponsorBannerUrl", url)} storagePath={challengeDraftMediaPath(userId, "gallery")} kind="image" buttonLabel="Upload Sponsor Banner" /><Field label="Brand Color"><input className={inputClass} type="color" value={form.brandColor} onChange={(e) => update("brandColor", e.target.value)} /></Field></Grid><p className="text-sm text-slate-400">Media uploads fail closed until secure Storage rules are manually published. External livestream links remain partner URLs only.</p></Step>;
  if (step === 9) return <Step title="Sponsor Readiness"><Grid>{check("allowSponsorInterest", "Allow sponsor interest")}{check("showSponsorRequestButton", "Show sponsor request button")}</Grid><Field label="Sponsor Categories"><textarea className={textareaClass} value={form.sponsorCategories} onChange={(e) => update("sponsorCategories", e.target.value)} /></Field><Field label="Visibility Areas"><textarea className={textareaClass} value={form.sponsorVisibilityAreas} onChange={(e) => update("sponsorVisibilityAreas", e.target.value)} /></Field><Card className="p-4 text-sm text-slate-300">Sponsor requests remain review-only. No sponsor capture or release is activated.</Card></Step>;
  return <Step title="Review & Publish"><div className="grid gap-3 sm:grid-cols-2">{[["Competition", form.competitionType], ["Visibility", form.visibilityMode], ["Format", form.format], ["Participants", form.maxParticipants], ["Voting", `${form.votesPerUserPerDay} vote(s)/day`], ["Winner selection", form.winnerSelection]].map(([label, value]) => <Card key={label} className="p-4"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 font-black capitalize">{value.replaceAll("_", " ")}</p></Card>)}</div><Grid>{["draft", "publish", "schedule"].map((value) => <Button key={value} variant={form.launchMode === value ? "primary" : "secondary"} onClick={() => update("launchMode", value)}>{value}</Button>)}</Grid><Card className="p-4 text-sm text-slate-300">Moderation, vote controls, winner publication, exports, sponsor money, payouts, refunds, and prize releases remain safe foundations.</Card></Step>;
}
function Step({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-6"><div><p className="text-xs font-black uppercase text-[var(--gold)]">Host competition builder</p><h2 className="mt-2 text-2xl font-black">{title}</h2></div>{children}</section>; }
function Grid({ children }: { children: React.ReactNode }) { return <div className="grid gap-4 sm:grid-cols-2">{children}</div>; }

function SpecializedFlowNotice({ competitionType }: { competitionType: string }) {
  if (competitionType === "Live Event") return <Card className="p-4 text-sm leading-6 text-slate-300"><b className="text-white">Live Event foundation.</b> Capture venue name, venue address, city/country, event date, start time, end time, registration open/close, check-in method, attendee limit, RSVP/register mode, event rules, agenda/schedule, host/contact person, emergency contact, age restriction, media coverage permission, sponsor placement options, livestream link if real, prize/award info, judges/officials, and publish review. Ticket checkout remains setup-safe; no ticket payment is created.</Card>;
  if (competitionType === "Tournament") return <Card className="p-4 text-sm leading-6 text-slate-300"><b className="text-white">Tournament foundation.</b> Support manual bracket setup and auto-generated bracket after registration closes as a safe foundation. Fields cover format, participant/team count, registration deadline, seeding method, round schedule, match rules, scoring method, tie-breakers, team/solo mode, bracket visibility, dispute rules, prize structure, sponsor options, and publish review. Brackets and participants are generated only from real registration data.</Card>;
  if (competitionType === "Private Challenge") return <Card className="p-4 text-sm leading-6 text-slate-300"><b className="text-white">Private Challenge foundation.</b> Support invite code, invite link, selected users/email invite, participant limit, hidden/link-only/invited-users visibility, access rules, invite expiration, approval requirement, timeline, submission rules, and plan-gated prize/monetization. Free users cannot create private challenges; Host gets broader private access.</Card>;
  return <Card className="p-4 text-sm leading-6 text-slate-300">This builder is section-based. Private challenges, live events, tournaments, and hybrid competitions use dedicated workspace entries for their format.</Card>;
}



const hybridSteps = ["Basic Details", "Online Qualification", "Shortlist Rules", "Final Round", "Scoring & Judges", "Media", "Review & Publish"];
const hybridInitial = {
  title: "", description: "", category: "Creative", coverImageUrl: "", coverImagePath: "", acceptedMediaType: "image", maxSubmissionLength: "180", maxFileSizeMb: "50",
  onlineSubmissionStart: dateInput(1), onlineSubmissionDeadline: dateInput(7), qualificationMethod: "mixed", numberOfFinalists: "10", finalistAnnouncementDate: dateInput(8), advancementRules: "Top submissions advance after host review and published scoring checks.",
  finalRoundType: "hybrid_live_online", finalDateTime: dateInput(14), venueName: "", finalLocation: "", externalLiveUrl: "", externalLiveStatus: "not_ready", finalRequirements: "Finalists complete a final-round entry or judging session.",
  audienceVoteWeight: "40", judgeScoreWeight: "50", hostReviewWeight: "10", tieBreakerRule: "Highest judge score breaks ties.", judgeNames: "", judgeEmails: "", judgeCriteria: "Originality\nExecution\nAudience impact", judgeVisibility: "summary",
  promoImageUrl: "", promoImagePath: "", trailerVideoUrl: "", trailerVideoPath: "", launchMode: "draft"
};
type HybridForm = typeof hybridInitial;

function HybridCompetitionBuilder() {
  const auth = useAuth();
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<HybridForm>(hybridInitial);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [createdId, setCreatedId] = useState("");
  const update = <K extends keyof HybridForm>(key: K, value: HybridForm[K]) => { setForm((current) => ({ ...current, [key]: value })); setError(""); };
  const validate = () => {
    if (step === 0 && (form.title.trim().length < 3 || form.description.trim().length < 10)) return "Add a title and a description of at least 10 characters.";
    if (step === 1 && new Date(form.onlineSubmissionDeadline) <= new Date(form.onlineSubmissionStart)) return "Online submission deadline must be after the start date.";
    if (step === 2 && Number(form.numberOfFinalists) < 1) return "Add at least one finalist slot.";
    if (step === 4 && Number(form.audienceVoteWeight) + Number(form.judgeScoreWeight) + Number(form.hostReviewWeight) !== 100) return "Scoring weights must total 100%.";
    return "";
  };
  const lines = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);
  async function submit(publish: boolean) {
    const problem = validate(); if (problem) return setError(problem);
    setSaving(true);
    const payload = {
      title: form.title, description: form.description, category: form.category, type: "Hybrid Competition", visibility: "public",
      acceptedSubmissionTypes: [form.acceptedMediaType], competitionFormat: "Hybrid Qualification to Final", bestOf: "Hybrid Final",
      startsAt: form.onlineSubmissionStart, submissionDeadline: form.onlineSubmissionDeadline, votingStartsAt: form.onlineSubmissionDeadline, votingDeadline: form.finalDateTime, endsAt: form.finalDateTime,
      standardRules: "Hybrid competitions combine online qualification with a live, scheduled, or judged final stage.", policyTerms: "Finalists, winners, revenue, and prizes remain subject to admin review.", challengeGuidelines: form.finalRequirements,
      coverImageUrl: form.coverImageUrl, coverImagePath: form.coverImagePath, promoImageUrl: form.promoImageUrl, promoImagePath: form.promoImagePath, trailerVideoUrl: form.trailerVideoUrl, trailerVideoPath: form.trailerVideoPath, promoVideoUrl: "", promoVideoPath: "",
      prizeType: "bragging_rights", prizeValue: 0, paidEntryEnabled: false, entryFee: 0, prizePoolEnabled: false, prizePool: 0, cashPayoutsEnabled: false,
      isLiveEvent: ["live_physical_event", "hybrid_live_online"].includes(form.finalRoundType), venueName: form.venueName, eventAddress: form.finalLocation, eventCity: form.finalLocation, eventCapacity: Number(form.numberOfFinalists),
      externalLiveUrl: form.externalLiveUrl, externalLiveStatus: form.externalLiveStatus, externalLiveCtaLabel: "Watch final on partner site",
      tournamentType: "hybrid_qualification_final", tournamentStages: [
        { id: "online_qualification", name: "Online Qualification", order: 1, status: "draft", advancementRule: form.advancementRules },
        { id: "shortlist", name: "Shortlist", order: 2, status: "draft", advancementRule: `${form.numberOfFinalists} finalists announced ${form.finalistAnnouncementDate}` },
        { id: "final_round", name: "Final Round", order: 3, status: "draft", advancementRule: form.finalRequirements },
        { id: "admin_review", name: "Winner Review", order: 4, status: "draft", advancementRule: "Winners reviewed before announcement. No payout execution." }
      ],
      maxParticipants: 50, judgeScoringEnabled: true, votingSettings: { allowFreeVotes: true, allowDoroCoinVotes: true, weightedVotes: false }, requiresSubmissionApproval: true,
      hostOperations: { hybridCompetition: true, onlineSubmissionStart: form.onlineSubmissionStart, onlineSubmissionDeadline: form.onlineSubmissionDeadline, acceptedMediaType: form.acceptedMediaType, maxSubmissionLength: Number(form.maxSubmissionLength), maxFileSizeMb: Number(form.maxFileSizeMb), qualificationMethod: form.qualificationMethod, numberOfFinalists: Number(form.numberOfFinalists), finalistAnnouncementDate: form.finalistAnnouncementDate, advancementRules: form.advancementRules, finalRoundType: form.finalRoundType, finalDateTime: form.finalDateTime, finalLocation: form.finalLocation, audienceVoteWeight: Number(form.audienceVoteWeight), judgeScoreWeight: Number(form.judgeScoreWeight), hostReviewWeight: Number(form.hostReviewWeight), tieBreakerRule: form.tieBreakerRule, judgeNames: lines(form.judgeNames), judgeEmails: lines(form.judgeEmails), judgeCriteria: lines(form.judgeCriteria), judgeVisibility: form.judgeVisibility, finalistsLocked: false, finalRoundOpen: false, winnersReviewed: false, winnersAnnounced: false },
      publish
    };
    const result = await createChallenge(payload);
    setSaving(false);
    if (!result.ok) return setError(result.message || "Hybrid competition could not be saved.");
    setCreatedId(((result.data?.challenge as { id?: string } | undefined)?.id) || "saved");
  }
  if (createdId) return <AppShell><Card className="mx-auto max-w-2xl p-8 text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-400" /><h1 className="mt-5 text-3xl font-black">Hybrid competition saved</h1><p className="mt-3 text-slate-300">Online qualification, finalist selection, final round, judging, and winner review are saved as safe foundations.</p><div className="mt-6 flex justify-center gap-3"><LinkButton href={createdId === "saved" ? "/my-challenges" : `/challenges/${createdId}`}>View Competition</LinkButton><LinkButton href="/host/hybrid" variant="secondary">Hybrid Workspace</LinkButton></div></Card></AppShell>;
  return <AppShell><div className="mx-auto max-w-6xl"><PageTitle title="Create Hybrid Competition" subtitle="Hybrid competitions combine online submissions with a live, scheduled, or judged final stage. Use this when participants qualify online before advancing to a final round." /><Card className="mt-6 p-4 sm:p-6"><div className="flex gap-2 overflow-x-auto pb-2">{hybridSteps.map((label, index) => <button key={label} onClick={() => index <= step && setStep(index)} className={`min-h-11 min-w-40 rounded-[8px] px-3 text-left text-xs font-black ${index === step ? "bg-[var(--gold)] text-black" : "bg-[#191919] text-slate-300"}`}>{index + 1}. {label}</button>)}</div><div className="mt-8 min-h-[470px]"><HybridStep step={step} form={form} update={update} userId={auth.user?.uid ?? "anonymous"} /></div>{error ? <p className="mt-5 rounded-[8px] bg-red-950/50 p-4 text-red-200">{error}</p> : null}<div className="mt-8 flex flex-col gap-3 border-t border-white/10 pt-6 sm:flex-row sm:justify-between"><Button variant="secondary" onClick={() => submit(false)} disabled={saving}><Save size={17} /> Save Draft</Button><div className="flex gap-3"><Button variant="ghost" disabled={step === 0} onClick={() => setStep((value) => value - 1)}>Back</Button>{step < hybridSteps.length - 1 ? <Button onClick={() => { const problem = validate(); problem ? setError(problem) : setStep((value) => value + 1); }}>Next</Button> : <Button onClick={() => submit(form.launchMode !== "draft")} disabled={saving}>{saving ? "Saving..." : "Publish Hybrid"}</Button>}</div></div></Card></div></AppShell>;
}

function HybridStep({ step, form, update, userId }: { step: number; form: HybridForm; update: <K extends keyof HybridForm>(key: K, value: HybridForm[K]) => void; userId: string }) {
  if (step === 0) return <Step title="Basic Details"><Field label="Title"><input className={inputClass} value={form.title} onChange={(e) => update("title", e.target.value)} /></Field><Field label="Description"><textarea className={textareaClass} value={form.description} onChange={(e) => update("description", e.target.value)} /></Field><Grid><Field label="Category"><input className={inputClass} value={form.category} onChange={(e) => update("category", e.target.value)} /></Field><MediaUploadField label="Cover Image" value={form.coverImageUrl} onChange={(url, metadata) => { update("coverImageUrl", url); update("coverImagePath", metadata?.path ?? ""); }} storagePath={challengeDraftMediaPath(userId, "banner")} kind="image" buttonLabel="Upload Cover Image" /></Grid></Step>;
  if (step === 1) return <Step title="Online Qualification"><Grid><Field label="Online Submission Start"><input className={inputClass} type="datetime-local" value={form.onlineSubmissionStart} onChange={(e) => update("onlineSubmissionStart", e.target.value)} /></Field><Field label="Online Submission Deadline"><input className={inputClass} type="datetime-local" value={form.onlineSubmissionDeadline} onChange={(e) => update("onlineSubmissionDeadline", e.target.value)} /></Field><Field label="Accepted Media Type"><select className={inputClass} value={form.acceptedMediaType} onChange={(e) => update("acceptedMediaType", e.target.value)}>{["image", "video", "text"].map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Qualification Method"><select className={inputClass} value={form.qualificationMethod} onChange={(e) => update("qualificationMethod", e.target.value)}>{["public_vote", "judge_review", "host_selection", "mixed"].map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></Field><Field label="Max Submission Length / Duration"><input className={inputClass} value={form.maxSubmissionLength} onChange={(e) => update("maxSubmissionLength", e.target.value)} /></Field><Field label="Max File Size (MB)"><input className={inputClass} type="number" value={form.maxFileSizeMb} onChange={(e) => update("maxFileSizeMb", e.target.value)} /></Field></Grid></Step>;
  if (step === 2) return <Step title="Shortlist Rules"><Grid><Field label="Number of Finalists"><input className={inputClass} type="number" min="1" value={form.numberOfFinalists} onChange={(e) => update("numberOfFinalists", e.target.value)} /></Field><Field label="Finalist Announcement Date"><input className={inputClass} type="datetime-local" value={form.finalistAnnouncementDate} onChange={(e) => update("finalistAnnouncementDate", e.target.value)} /></Field></Grid><Field label="Advancement Rules"><textarea className={textareaClass} value={form.advancementRules} onChange={(e) => update("advancementRules", e.target.value)} /></Field></Step>;
  if (step === 3) return <Step title="Final Round"><Grid><Field label="Final Round Type"><select className={inputClass} value={form.finalRoundType} onChange={(e) => update("finalRoundType", e.target.value)}>{["live_physical_event", "virtual_live_session", "scheduled_online_final", "hybrid_live_online"].map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></Field><Field label="Final Date / Time"><input className={inputClass} type="datetime-local" value={form.finalDateTime} onChange={(e) => update("finalDateTime", e.target.value)} /></Field><Field label="Venue / Location"><input className={inputClass} value={form.venueName} onChange={(e) => update("venueName", e.target.value)} /></Field><Field label="External Livestream Link"><input className={inputClass} value={form.externalLiveUrl} onChange={(e) => update("externalLiveUrl", e.target.value)} placeholder="Partner livestream URL" /></Field><Field label="External Live Status"><select className={inputClass} value={form.externalLiveStatus} onChange={(e) => update("externalLiveStatus", e.target.value)}>{["not_ready", "scheduled", "live", "ended"].map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Final Location Notes"><input className={inputClass} value={form.finalLocation} onChange={(e) => update("finalLocation", e.target.value)} /></Field></Grid><Field label="Final Submission / Judging Requirements"><textarea className={textareaClass} value={form.finalRequirements} onChange={(e) => update("finalRequirements", e.target.value)} /></Field></Step>;
  if (step === 4) return <Step title="Scoring & Judges"><Grid><Field label="Audience Vote Weight %"><input className={inputClass} type="number" value={form.audienceVoteWeight} onChange={(e) => update("audienceVoteWeight", e.target.value)} /></Field><Field label="Judge Score Weight %"><input className={inputClass} type="number" value={form.judgeScoreWeight} onChange={(e) => update("judgeScoreWeight", e.target.value)} /></Field><Field label="Host Review Weight %"><input className={inputClass} type="number" value={form.hostReviewWeight} onChange={(e) => update("hostReviewWeight", e.target.value)} /></Field><Field label="Tie-breaker Rule"><input className={inputClass} value={form.tieBreakerRule} onChange={(e) => update("tieBreakerRule", e.target.value)} /></Field></Grid><Grid><Field label="Judge Names"><textarea className={textareaClass} value={form.judgeNames} onChange={(e) => update("judgeNames", e.target.value)} /></Field><Field label="Judge Emails (foundation only)"><textarea className={textareaClass} value={form.judgeEmails} onChange={(e) => update("judgeEmails", e.target.value)} /></Field><Field label="Judge Scoring Criteria"><textarea className={textareaClass} value={form.judgeCriteria} onChange={(e) => update("judgeCriteria", e.target.value)} /></Field><Field label="Score Visibility"><select className={inputClass} value={form.judgeVisibility} onChange={(e) => update("judgeVisibility", e.target.value)}><option value="private">Private</option><option value="summary">Summary</option><option value="public_after_review">Public after review</option></select></Field></Grid></Step>;
  if (step === 5) return <Step title="Media"><Grid><MediaUploadField label="Promo Image" value={form.promoImageUrl} onChange={(url, metadata) => { update("promoImageUrl", url); update("promoImagePath", metadata?.path ?? ""); }} storagePath={challengeDraftMediaPath(userId, "gallery")} kind="image" buttonLabel="Upload Promo Image" /><MediaUploadField label="Trailer Video" value={form.trailerVideoUrl} onChange={(url, metadata) => { update("trailerVideoUrl", url); update("trailerVideoPath", metadata?.path ?? ""); }} storagePath={challengeDraftMediaPath(userId, "video")} kind="video" buttonLabel="Upload Trailer Video" /></Grid></Step>;
  return <Step title="Review & Publish"><div className="grid gap-3 sm:grid-cols-2">{[["Type", "Hybrid Competition"], ["Qualification", form.qualificationMethod], ["Finalists", form.numberOfFinalists], ["Final round", form.finalRoundType], ["Scoring", `${form.audienceVoteWeight}/${form.judgeScoreWeight}/${form.hostReviewWeight}`], ["Winner flow", "Finalists locked -> final opens -> scoring -> admin review -> announcement"]].map(([label, value]) => <Card key={label} className="p-4"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 font-black capitalize">{value.replaceAll("_", " ")}</p></Card>)}</div><Grid>{["draft", "publish", "schedule"].map((value) => <Button key={value} variant={form.launchMode === value ? "primary" : "secondary"} onClick={() => update("launchMode", value)}>{value}</Button>)}</Grid><Card className="p-4 text-sm text-slate-300">Finalists, winners, revenue, prizes, and event operations remain admin-review foundations. No payout, refund, or prize release is enabled.</Card></Step>;
}
