import { getAdminDb } from "@/lib/firebase/admin";
import { requireAdminPermission } from "@/lib/server/auth";
import { DEFAULT_PUBLIC_CONTENT, safePublicPath } from "@/lib/public-site/config";
import { writeAuditLog } from "@/lib/server/audit";
import { ok, readJson, serverError, serverUnavailable, validationError } from "@/lib/server/responses";
export const dynamic="force-dynamic";
const clean=(v:unknown,max=1000)=>typeof v==="string"?v.trim().slice(0,max):"";
function payload(body:Record<string,unknown>){
 const hero=(body.hero??{}) as Record<string,unknown>,announcement=(body.announcement??{}) as Record<string,unknown>,finalCta=(body.finalCta??{}) as Record<string,unknown>;
 const list=(value:unknown)=>Array.isArray(value)?value.map((item)=>clean(item,40)).filter(Boolean).slice(0,12):[];
 return {announcement:{enabled:announcement.enabled!==false,message:clean(announcement.message,180),ctaLabel:clean(announcement.ctaLabel,40),ctaRoute:safePublicPath(announcement.ctaRoute,"/for-talent"),status:["draft","scheduled","published","archived"].includes(clean(announcement.status,20))?clean(announcement.status,20):"draft",startAt:clean(announcement.startAt,40)||null,endAt:clean(announcement.endAt,40)||null,priority:Math.max(0,Math.min(100,Number(announcement.priority)||0)),audience:["all","user","creator","host","sponsor","admin"].includes(clean(announcement.audience,20))?clean(announcement.audience,20):"all",loggedInState:["all","guest","authenticated"].includes(clean(announcement.loggedInState,20))?clean(announcement.loggedInState,20):"all",roles:list(announcement.roles),plans:list(announcement.plans)},hero:{eyebrow:clean(hero.eyebrow,100),headline:clean(hero.headline,180),supportingCopy:clean(hero.supportingCopy,500),videoUrl:clean(hero.videoUrl,600),posterUrl:clean(hero.posterUrl,600)},finalCta:{headline:clean(finalCta.headline,160),body:clean(finalCta.body,400),label:clean(finalCta.label,40)},assurances:Array.isArray(body.assurances)?body.assurances.map((v)=>clean(v,100)).filter(Boolean).slice(0,8):DEFAULT_PUBLIC_CONTENT.assurances,faqs:Array.isArray(body.faqs)?body.faqs.flatMap((v)=>{const row=v as Record<string,unknown>,question=clean(row.question,180),answer=clean(row.answer,900);return question&&answer?[{question,answer}]:[]}).slice(0,12):[]};
}
export async function GET(request:Request){const {response}=await requireAdminPermission(request,"content.preview");if(response)return response;const db=getAdminDb();if(!db)return serverUnavailable("Public content admin");try{const snap=await db.collection("publicSiteConfig").doc("default").get();return ok({config:snap.exists?{...DEFAULT_PUBLIC_CONTENT,...snap.data()}:DEFAULT_PUBLIC_CONTENT},"Public content configuration loaded.")}catch(e){return serverError("Public content configuration could not be loaded.",e instanceof Error?e.message:e)}}
export async function PATCH(request:Request){const {user,response}=await requireAdminPermission(request,"content.publish");if(response)return response;const db=getAdminDb();if(!db)return serverUnavailable("Public content admin");const parsed=await readJson(request);if(parsed.response)return parsed.response;const body=(parsed.body??{}) as Record<string,unknown>;const next=payload(body);if(!next.hero.headline||!next.hero.supportingCopy)return validationError({hero:"Hero headline and supporting copy are required."});const ref=db.collection("publicSiteConfig").doc("default");try{const beforeSnap=await ref.get(),before=beforeSnap.exists?beforeSnap.data():null,now=new Date().toISOString();const versionRef=db.collection("publicSiteConfigVersions").doc();await Promise.all([ref.set({...next,updatedAt:now,updatedBy:user.uid,createdAt:(before as Record<string,unknown>|null)?.createdAt??now,createdBy:(before as Record<string,unknown>|null)?.createdBy??user.uid},{merge:true}),versionRef.set({id:versionRef.id,configId:"default",...next,createdAt:now,createdBy:user.uid}),writeAuditLog({actorId:user.uid,actorType:"admin",action:"public_site.content_updated",targetType:"publicSiteConfig",targetId:"default",before,after:next,metadata:{versionId:versionRef.id}},db)]);return ok({config:next,versionId:versionRef.id},"Public content configuration saved.")}catch(e){return serverError("Public content configuration could not be saved.",e instanceof Error?e.message:e)}}
