"use client";

import Link from "next/link";
import { ArrowRight, ChevronLeft, ChevronRight, Play } from "lucide-react";
import { useRef } from "react";
import { PUBLIC_AMBASSADOR_VIDEOS } from "@/lib/public-site/config";
import { useLanguage } from "@/lib/i18n/use-language";

export function AmbassadorVideoScroll() {
  const { t } = useLanguage();
  const rail = useRef<HTMLDivElement>(null);
  const move = (direction: number) => rail.current?.scrollBy({ left: direction * Math.max(280, (rail.current?.clientWidth ?? 0) * 0.88), behavior: "smooth" });
  return <section className="public-section bg-[#f8f7f2]" id="talent-ambassadors"><div className="public-container"><div className="flex items-end justify-between gap-5"><div className="max-w-3xl"><p className="text-sm font-bold text-[#8b7900]">{t("Challenge Suite")}</p><h2 className="mt-4 text-[clamp(2rem,8vw,3rem)] font-semibold leading-[1.08]"><span className="block">{t("Every Challenge Starts Here.")}</span><span className="block">{t("Battle. Compete. Dominate. Create.")}</span></h2><p className="mt-4 max-w-2xl text-base leading-7 text-[#626262] sm:text-lg">{t("From creators to competitors, Challenge Suite is where talent shows up, stands out, and gets rewarded.")}</p></div><div className="hidden gap-2 md:flex"><button type="button" aria-label="Scroll ambassador videos left" onClick={() => move(-1)} className="grid h-11 w-11 place-items-center rounded-full border border-[#d8d8d2] bg-white"><ChevronLeft size={19} /></button><button type="button" aria-label="Scroll ambassador videos right" onClick={() => move(1)} className="grid h-11 w-11 place-items-center rounded-full border border-[#d8d8d2] bg-white"><ChevronRight size={19} /></button></div></div><div ref={rail} tabIndex={0} aria-label="Challenge Suite ambassador videos" className="mt-9 flex snap-x snap-mandatory gap-4 overflow-x-auto pb-4 [scrollbar-width:thin]">{PUBLIC_AMBASSADOR_VIDEOS.map((item, index) => <article key={item.id} className="shrink-0 basis-[86%] snap-start overflow-hidden rounded-[12px] border border-[#deded8] bg-white sm:basis-[calc((100%-1rem)/2)] lg:basis-[calc((100%-2rem)/3)]"><div className={`relative aspect-[16/10] ${index % 2 ? "bg-[#ecebe5]" : "bg-[#f4df58]"}`}><div className="absolute inset-0 flex items-center justify-center" aria-label={`${item.title}. Coming Soon.`}><span className="grid h-14 w-14 place-items-center rounded-full border border-black/10 bg-white/75 text-black/65"><Play size={21} /></span><span className="absolute bottom-4 left-4 rounded-full bg-white/80 px-3 py-1 text-xs font-bold">Coming Soon</span></div></div><div className="min-h-[124px] p-5"><h3 className="text-lg font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-black/60">{item.subtitle}</p>{item.status === "active" && item.ctaHref ? <Link href={item.ctaHref} className="mt-3 inline-flex text-sm font-bold text-[#7b6b00]">{item.ctaLabel}<ArrowRight size={16} /></Link> : null}</div></article>)}</div></div></section>;
}
