"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Activity, BarChart3, CheckCircle2, ClipboardCheck, Search, ShieldCheck, Sparkles, Trophy, UsersRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { CreatorAnalytics } from "@/components/creator/creator-analytics";
import { Card, EmptyState, LinkButton, PageTitle } from "@/components/ui";

type RecordItem = Record<string, unknown> & { id: string };
type CreatorData = { challenges: RecordItem[]; completedChallenges: RecordItem[]; participants: RecordItem[]; submissions: RecordItem[]; winners: RecordItem[]; votes: RecordItem[]; sponsorInterest: RecordItem[]; boosts: RecordItem[]; notifications: RecordItem[] };

async function loadCreatorData(): Promise<CreatorData> {
  const response = await fetch("/api/host/operations", { cache: "no-store" });
  const body = await response.json();
  if (!response.ok || !body.ok) throw new Error(body.message || "Creator workspace could not be loaded.");
  return body.data;
}

const labels = { dashboard: ["Creator Studio", "Your real challenge activity, next actions, and growth tools in one place."], analytics: ["Creator Analytics", "Measure participation, submissions, votes, revenue, and sponsor interest from your recorded challenge activity."], boosts: ["Monthly Boosts", "Choose an eligible challenge, then review and confirm the boost through the existing protected flow."], "sponsor-ready": ["Sponsor-Ready Challenges", "Prepare owned challenges for sponsor discovery and monitor real interest."], submissions: ["Creator Submissions", "Review entries attached to challenges you own."] } as const;

export function CreatorWorkspace({ mode = "dashboard" }: { mode?: keyof typeof labels }) {
  const query = useQuery({ queryKey: ["creator-workspace"], queryFn: loadCreatorData, staleTime: 30_000 });
  const [search, setSearch] = useState("");
  const [view, setView] = useState("all");
  const data = query.data;
  const challenges = data?.challenges ?? [];
  const filtered = useMemo(() => challenges.filter((item) => String(item.title ?? "").toLowerCase().includes(search.toLowerCase())), [challenges, search]);
  const status = (item: RecordItem) => String(item.status ?? item.lifecycleStatus ?? "draft").toLowerCase();
  const sponsorReadyStatuses = new Set(["published", "scheduled"]);
  const sponsorEligible = filtered.filter((item) => sponsorReadyStatuses.has(status(item)));
  const sponsorReady = sponsorEligible.filter((item) => Boolean(item.sponsorReady || item.sponsorEnabled || (item.monetization as Record<string, unknown> | undefined)?.sponsorReady));
  const eligibleBoosts = filtered.filter((item) => ["published", "registration_open", "active", "voting"].includes(status(item)) && String(item.visibility ?? "public") === "public");
  const activeBoostIds = new Set((data?.boosts ?? []).filter((item) => ["active", "confirmed"].includes(String(item.status ?? "").toLowerCase())).map((item) => String(item.challengeId ?? "")));
  const boostRecords = view === "active" ? eligibleBoosts.filter((item) => activeBoostIds.has(item.id)) : view === "history" ? filtered.filter((item) => (data?.boosts ?? []).some((boost) => String(boost.challengeId ?? "") === item.id)) : view === "ineligible" ? filtered.filter((item) => !eligibleBoosts.some((eligible) => eligible.id === item.id)) : view === "eligible" ? eligibleBoosts : filtered;
  const sponsorRecords = view === "interest" ? sponsorReady.filter((item) => data?.sponsorInterest.some((interest) => String(interest.challengeId ?? "") === item.id)) : view === "not_ready" ? sponsorEligible.filter((item) => !sponsorReady.some((ready) => ready.id === item.id)) : sponsorReady;
  const title = labels[mode];

  return <AppShell><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><PageTitle title={title[0]} subtitle={title[1]} /><div className="flex flex-wrap gap-2"><LinkButton href="/challenges/create">Create Challenge</LinkButton><LinkButton href="/my-challenges" variant="secondary">Manage Challenges</LinkButton></div></div><nav className="mt-7 flex gap-2 overflow-x-auto border-b border-white/10 pb-3" aria-label="Creator tools">{Object.entries(labels).map(([key, value]) => <Link key={key} href={key === "dashboard" ? "/creator" : `/creator/${key}`} className={`shrink-0 rounded-[8px] px-4 py-2 text-sm font-black ${mode === key ? "bg-[var(--gold)] text-black" : "bg-white/5 text-slate-300"}`}>{value[0]}</Link>)}</nav>
    {query.isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-3">{[0,1,2].map((item) => <Card key={item} className="h-36 animate-pulse" />)}</div> : query.error ? <Card className="mt-8"><EmptyState icon={<Activity />} title="Creator workspace unavailable" body={query.error.message} /></Card> : null}
    {data && mode === "dashboard" ? <Dashboard data={data} /> : null}
    {data && mode === "analytics" ? <CreatorAnalytics data={data} /> : null}
    {data && mode === "boosts" ? <section className="mt-8"><OperationalHeader title="Boost allowance" body={`${data.boosts.filter((item) => ["active", "confirmed"].includes(String(item.status ?? "").toLowerCase())).length} active confirmed boosts. Availability is checked again by the protected boost flow.`} values={["all","eligible","ineligible","active","history"]} value={view} onChange={setView} /><ToolSearch value={search} onChange={setSearch} placeholder="Search your challenges"/><div className="mt-6 grid gap-5 md:grid-cols-2">{boostRecords.map((challenge) => <ChallengeCard key={challenge.id} challenge={challenge} note={eligibleBoosts.some((item) => item.id === challenge.id) ? activeBoostIds.has(challenge.id) ? "Confirmed boost is active" : "Eligible for boost review" : "Not eligible: publish this challenge publicly before requesting a boost"} action={eligibleBoosts.some((item) => item.id === challenge.id) ? `/challenges/${challenge.id}/boost` : `/challenges/${challenge.id}/manage`} actionLabel={eligibleBoosts.some((item) => item.id === challenge.id) ? "Review Boost" : "Review Challenge"} />)}</div>{!boostRecords.length ? <EmptyCard title="No matching boost records" body="Boosts appear only from owned challenges and confirmed boost records. No boost is created by this page." /> : null}</section> : null}
    {data && mode === "sponsor-ready" ? <section className="mt-8"><OperationalHeader title="Sponsor readiness" body="Public status, sponsor settings, and recorded inquiries remain separate from confirmed sponsor funding." values={["all","interest","not_ready"]} value={view} onChange={setView} /><ToolSearch value={search} onChange={setSearch} placeholder="Search sponsor-ready challenges"/><div className="mt-6 grid gap-5 md:grid-cols-2">{sponsorRecords.map((challenge) => <ChallengeCard key={challenge.id} challenge={challenge} note={sponsorReady.some((item) => item.id === challenge.id) ? `${data.sponsorInterest.filter((item) => String(item.challengeId) === challenge.id).length} recorded sponsor inquiries` : "Not sponsor ready: enable sponsor discovery settings on an eligible owned challenge"} action={`/challenges/${challenge.id}/manage`} actionLabel="Manage Readiness" />)}</div>{!sponsorRecords.length ? <EmptyCard title="No matching sponsor-readiness records" body="Sponsor interest and funding are shown only when real records exist." /> : null}</section> : null}
    {data && mode === "submissions" ? <section className="mt-8 grid gap-4">{data.submissions.map((submission) => <Card key={submission.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">{String(submission.title ?? "Untitled entry")}</p><p className="mt-1 text-sm text-slate-400">{String(submission.status ?? "submitted").replaceAll("_", " ")}</p></div><LinkButton href={`/submissions/${submission.id}`} variant="secondary">Review Entry</LinkButton></Card>)}{!data.submissions.length ? <EmptyCard title="No creator submissions yet" body="Entries will appear when people submit to your owned challenges." /> : null}</section> : null}
  </div></AppShell>;
}

function Dashboard({ data }: { data: CreatorData }) { const metrics = [["Owned challenges", data.challenges.length, Trophy], ["Participants", data.participants.length, UsersRound], ["Submissions", data.submissions.length, ClipboardCheck], ["Recorded votes", data.votes.length, BarChart3]] as const; return <><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon]) => <Card key={label} className="p-5"><Icon className="text-[var(--gold)]"/><p className="mt-6 text-3xl font-black">{value.toLocaleString()}</p><p className="mt-1 text-sm text-slate-400">{label}</p></Card>)}</section><section className="mt-8 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><Card className="p-6"><h2 className="text-xl font-black">Recent challenge activity</h2><div className="mt-5 grid gap-3">{data.challenges.slice(0,5).map((item) => <Link key={item.id} href={`/challenges/${item.id}/manage`} className="flex items-center justify-between rounded-[8px] border border-white/10 p-4"><span><b>{String(item.title ?? "Untitled challenge")}</b><small className="mt-1 block capitalize text-slate-400">{String(item.status ?? "draft").replaceAll("_", " ")}</small></span><CheckCircle2 size={18} className="text-[var(--gold)]"/></Link>)}{!data.challenges.length ? <p className="text-sm text-slate-400">No owned challenge activity yet.</p> : null}</div></Card><Card className="p-6"><Sparkles className="text-[var(--gold)]"/><h2 className="mt-4 text-xl font-black">Next steps</h2><div className="mt-4 grid gap-3 text-sm"><Link href="/challenges/create" className="rounded-[8px] bg-white/5 p-3">Create or finish a challenge</Link><Link href="/creator/boosts" className="rounded-[8px] bg-white/5 p-3">Review boost eligibility</Link><Link href="/creator/sponsor-ready" className="rounded-[8px] bg-white/5 p-3">Prepare sponsor readiness</Link></div></Card></section></>; }

function Analytics({ data }: { data: CreatorData }) { const hasReal = data.participants.length + data.submissions.length + data.votes.length > 0; const rows = data.challenges.slice(0,8).map((challenge) => ({ challenge, participants: data.participants.filter((item) => String(item.challengeId) === challenge.id).length, submissions: data.submissions.filter((item) => String(item.challengeId) === challenge.id).length, votes: data.votes.filter((item) => String(item.challengeId) === challenge.id).length })); const max = Math.max(1, ...rows.map((row) => row.participants + row.submissions + row.votes)); return <section className="mt-8"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Total participants" value={data.participants.length}/><Metric label="Eligible submissions" value={data.submissions.length}/><Metric label="Recorded votes" value={data.votes.length}/></div><Card className="mt-6 p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">Challenge activity</h2><p className="mt-1 text-sm text-slate-400">Real records grouped by owned challenge.</p></div>{!hasReal ? <span className="rounded-full bg-amber-400/10 px-3 py-2 text-xs font-black text-amber-300">Preview sample data unavailable until activity begins</span> : null}</div><div className="mt-7 grid gap-5">{rows.map((row) => <div key={row.challenge.id}><div className="flex justify-between text-sm"><b>{String(row.challenge.title ?? "Untitled challenge")}</b><span>{row.participants} participants · {row.submissions} entries · {row.votes} votes</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-[var(--gold)]" style={{width:`${Math.max(3,((row.participants+row.submissions+row.votes)/max)*100)}%`}}/></div></div>)}{!rows.length ? <p className="text-sm text-slate-400">Create a challenge to begin collecting real analytics. No sample is stored as activity.</p> : null}</div></Card></section>; }
function ToolSearch({value,onChange,placeholder}:{value:string;onChange:(value:string)=>void;placeholder:string}){return <label className="flex max-w-xl items-center gap-3 rounded-[8px] border border-white/10 bg-white/5 px-4"><Search size={18}/><input value={value} onChange={(event)=>onChange(event.target.value)} placeholder={placeholder} className="min-h-12 flex-1 bg-transparent outline-none"/></label>}
function ChallengeCard({challenge,note,action,actionLabel}:{challenge:RecordItem;note:string;action:string;actionLabel:string}){return <Card className="p-6"><p className="text-xs font-black uppercase tracking-[0.14em] text-[var(--gold)]">{String(challenge.status ?? "draft").replaceAll("_", " ")}</p><h2 className="mt-3 text-xl font-black">{String(challenge.title ?? "Untitled challenge")}</h2><p className="mt-2 text-sm text-slate-400">{note}</p><LinkButton href={action} variant="secondary" className="mt-5">{actionLabel}</LinkButton></Card>}
function Metric({label,value}:{label:string;value:number}){return <Card className="p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-[var(--gold)]">{value.toLocaleString()}</p></Card>}
function EmptyCard({title,body}:{title:string;body:string}){return <Card className="mt-6"><EmptyState icon={<ShieldCheck/>} title={title} body={body}/></Card>}
function OperationalHeader({title,body,values,value,onChange}:{title:string;body:string;values:string[];value:string;onChange:(value:string)=>void}){return <Card className="mb-6 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-black">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{body}</p></div><div className="flex gap-2 overflow-x-auto">{values.map((item)=><button key={item} type="button" onClick={()=>onChange(item)} className={`shrink-0 rounded-[8px] px-3 py-2 text-xs font-black capitalize ${value===item?"bg-[var(--gold)] text-black":"bg-white/5 text-slate-300"}`}>{item.replaceAll("_"," ")}</button>)}</div></div></Card>}
