import { z } from "zod";
import { getAdminDb } from "@/lib/firebase/admin";
import { writeAuditLog } from "@/lib/server/audit";
import { requireAdminPermission } from "@/lib/server/auth";
import { conflict, fail, ok, readJson, serverError, serverUnavailable, validationError } from "@/lib/server/responses";

const schema = z.object({ jobId: z.string().min(1), reason: z.string().trim().min(8).max(1000) });
export async function GET(request: Request) { const { response } = await requireAdminPermission(request, "jobs.view"); if (response) return response; const db = getAdminDb(); if (!db) return serverUnavailable("Background jobs"); const snap = await db.collection("backgroundJobs").orderBy("updatedAt", "desc").limit(250).get(); return ok({ jobs: snap.docs.map((doc) => ({ id: doc.id, ...doc.data() })), readOnly: true }); }
export async function POST(request: Request) { const { user, response } = await requireAdminPermission(request, "jobs.retry"); if (response) return response; const db = getAdminDb(); if (!db) return serverUnavailable("Background jobs"); const body = await readJson(request); if (body.response) return body.response; const parsed = schema.safeParse(body.body); if (!parsed.success) return validationError({ request: parsed.error.issues[0]?.message ?? "Invalid retry." }); try { const ref = db.collection("backgroundJobs").doc(parsed.data.jobId); await db.runTransaction(async (transaction) => { const snap = await transaction.get(ref); if (!snap.exists) throw new Error("NOT_FOUND"); const data = snap.data() ?? {}; if (!["failed", "needs_attention"].includes(String(data.status))) throw new Error("INVALID_STATE"); if (data.retryRequestedAt && data.retryCompletedAt == null) throw new Error("ALREADY_PENDING"); transaction.set(ref, { status: "retrying", retryRequestedAt: new Date().toISOString(), retryRequestedBy: user!.uid, retryReason: parsed.data.reason, retryIdempotencyKey: `retry_${ref.id}_${Number(data.attemptCount ?? 0) + 1}`, attemptCount: Number(data.attemptCount ?? 0) + 1, updatedAt: new Date().toISOString() }, { merge: true }); }); await writeAuditLog({ actorId: user!.uid, actorType: "admin", action: "background_job.retry_requested", targetType: "system", targetId: parsed.data.jobId, reason: parsed.data.reason, metadata: { noDirectFinancialExecution: true } }, db); return ok({ jobId: parsed.data.jobId, status: "retrying" }, "Retry requested. The job worker will re-check idempotency before execution."); } catch (error) { if (error instanceof Error && error.message === "NOT_FOUND") return fail("Job not found.", 404); if (error instanceof Error && ["INVALID_STATE", "ALREADY_PENDING"].includes(error.message)) return conflict("This job is not eligible for another retry."); return serverError("Retry could not be requested.", error instanceof Error ? error.message : error); } }
