"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BriefcaseBusiness, CheckCircle2, Clock3, ExternalLink, LifeBuoy, RefreshCw, Search, ShieldCheck, UserPlus, UsersRound } from "lucide-react";
import { apiRequest } from "@/lib/api/client";
import { Button, Card, EmptyState, Field, PageTitle, inputClass, textareaClass } from "@/components/ui";

type RecordItem = Record<string, unknown> & { id: string };
const labels = (value: unknown) => String(value ?? "Not available").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export function AdminTeamWorkspace() {
  const [data, setData] = useState<{ administrators: RecordItem[]; invitations: RecordItem[] }>({ administrators: [], invitations: [] });
  const [method, setMethod] = useState("email"); const [identity, setIdentity] = useState(""); const [role, setRole] = useState("support_admin"); const [reason, setReason] = useState(""); const [notice, setNotice] = useState("");
  const load = () => void apiRequest<typeof data>("/api/admin/team").then((result) => result.data && setData(result.data));
  useEffect(load, []);
  async function appoint() { const result = await apiRequest("/api/admin/team", { method: "POST", body: JSON.stringify({ method, email: method === "email" ? identity : undefined, uid: method !== "email" ? identity : undefined, roles: [role], reason }) }); setNotice(result.message); if (result.ok) { setIdentity(""); setReason(""); load(); } }
  return <><PageTitle title="Admin Team" subtitle="Invite, appoint, secure, and review authorized administrators." icon={<UsersRound className="text-[var(--gold)]" />} /><Card className="mt-7 p-6"><h2 className="text-xl font-black">Add administrator</h2><p className="mt-2 text-sm text-slate-400">Only Platform Owner and Super Admin can appoint administrators. Access stays pending until security setup is complete.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Method"><select className={inputClass} value={method} onChange={(event) => setMethod(event.target.value)}><option value="email">Email invitation</option><option value="uid">Firebase UID</option><option value="existing_user">Existing user search</option></select></Field><Field label={method === "email" ? "Email" : "Firebase UID"}><input className={inputClass} value={identity} onChange={(event) => setIdentity(event.target.value)} /></Field><Field label="Role"><select className={inputClass} value={role} onChange={(event) => setRole(event.target.value)}>{["super_admin", "operations_admin", "finance_admin", "moderation_admin", "safety_admin", "support_admin", "sponsor_manager", "event_tournament_admin", "content_admin", "marketing_communications_admin", "analyst", "read_only_auditor", "technical_admin", "developer_support"].map((value) => <option key={value} value={value}>{labels(value)}</option>)}</select></Field><Field label="Reason"><input className={inputClass} value={reason} onChange={(event) => setReason(event.target.value)} /></Field></div><Button className="mt-5" onClick={() => void appoint()} disabled={!identity || reason.length < 8}><UserPlus size={17} /> Add Administrator</Button>{notice ? <p className="mt-4 text-sm text-slate-300">{notice}</p> : null}</Card><RecordGrid records={[...data.administrators, ...data.invitations]} empty="No administrator records are available." /> </>;
}

export function ActionCentreWorkspace() {
  const [tasks, setTasks] = useState<RecordItem[]>([]); const [filter, setFilter] = useState("all"); const [notice, setNotice] = useState("");
  const load = () => void apiRequest<{ tasks: RecordItem[] }>("/api/admin/action-centre").then((result) => result.data && setTasks(result.data.tasks)); useEffect(load, []);
  const visible = useMemo(() => tasks.filter((task) => filter === "all" || task.state === filter), [tasks, filter]);
  async function update(taskId: string, action: string) { const reason = ["escalate", "resolve"].includes(action) ? window.prompt("Reason for this action")?.trim() : undefined; if (["escalate", "resolve"].includes(action) && !reason) return; const result = await apiRequest("/api/admin/action-centre", { method: "PATCH", body: JSON.stringify({ taskId, action, reason }) }); setNotice(result.message); if (result.ok) load(); }
  return <><PageTitle title="Action Centre" subtitle="Persistent work generated from real operational records." icon={<CheckCircle2 className="text-[var(--gold)]" />} /><div className="mt-6 flex flex-wrap gap-2">{["all", "unassigned", "assigned", "overdue", "escalated", "failed_automation", "waiting_for_user", "waiting_for_provider", "resolved"].map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-[8px] border px-4 py-2 text-sm font-bold ${filter === value ? "border-[var(--gold)] bg-[var(--gold)] text-black" : "border-white/10"}`}>{labels(value)}</button>)}</div>{notice ? <p className="mt-4 text-sm">{notice}</p> : null}<div className="mt-6 grid gap-4 xl:grid-cols-2">{visible.map((task) => <Card key={task.id} className="p-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-black uppercase text-[var(--gold)]">{labels(task.sourceType)}</p><h2 className="mt-2 text-lg font-black">{String(task.title)}</h2></div><span className="text-xs font-bold">{labels(task.state)}</span></div><p className="mt-3 text-sm text-slate-400">{String(task.reason ?? "Operational review required.")}</p><p className="mt-3 flex items-center gap-2 text-xs text-slate-500"><Clock3 size={14} /> SLA due {String(task.slaDueAt ?? "Not available")}</p><div className="mt-5 flex flex-wrap gap-2"><Button onClick={() => void update(task.id, "assign_to_me")}>Assign to me</Button><Button variant="secondary" onClick={() => void update(task.id, "start")}>Start</Button><Button variant="secondary" onClick={() => void update(task.id, "escalate")}>Escalate</Button><Button variant="secondary" onClick={() => void update(task.id, "resolve")}>Resolve</Button>{task.sourceCollection && task.sourceId ? <Link href={`/admin/search?q=${encodeURIComponent(String(task.sourceId))}`} className="inline-flex min-h-11 items-center gap-2 px-3 text-sm font-bold text-[var(--gold)]">Source record <ExternalLink size={15} /></Link> : null}</div></Card>)}{!visible.length ? <Card><EmptyState icon={<CheckCircle2 />} title="No matching tasks" body="Only materialized tasks linked to real source records appear here." /></Card> : null}</div></>;
}

export function PeopleWorkspace() {
  const [users, setUsers] = useState<RecordItem[]>([]); const [query, setQuery] = useState(""); useEffect(() => { void apiRequest<{ users: RecordItem[] }>("/api/admin/people/users").then((result) => result.data && setUsers(result.data.users)); }, []); const filtered = users.filter((user) => `${user.displayName} ${user.email}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageTitle title="People" subtitle="Search all real accounts and open a permission-controlled user control centre." icon={<UsersRound className="text-[var(--gold)]" />} /><div className="mt-6 flex items-center rounded-[8px] border border-white/10 bg-[#141414] px-4"><Search size={17} /><input className="h-12 flex-1 bg-transparent px-3 outline-none" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name or email" /></div><div className="mt-6 overflow-x-auto rounded-[8px] border border-white/10"><table className="min-w-[1000px] w-full text-left text-sm"><thead className="bg-white/5 text-xs uppercase text-slate-400"><tr>{["Name", "Email", "Workspace", "Plan", "Verification", "KYC", "Status", "Joined", "Recent activity", "Risk"].map((value) => <th key={value} className="p-4">{value}</th>)}</tr></thead><tbody>{filtered.map((user) => <tr key={user.id} className="border-t border-white/10"><td className="p-4 font-bold"><Link href={`/admin/people/users/${user.id}`} className="text-[var(--gold)]">{String(user.displayName)}</Link></td><td className="p-4">{String(user.email)}</td><td className="p-4">{labels(user.activeWorkspace)}</td><td className="p-4">{labels(user.plan)}</td><td className="p-4">{labels(user.verificationState)}</td><td className="p-4">{labels(user.kycState)}</td><td className="p-4">{labels(user.accountStatus)}</td><td className="p-4">{String(user.createdAt ?? "-")}</td><td className="p-4">{String(user.lastActivityAt ?? "-")}</td><td className="p-4">{Array.isArray(user.riskFlags) ? user.riskFlags.length : 0}</td></tr>)}</tbody></table></div></>;
}

export function UserControlCentre({ uid }: { uid: string }) {
  const [data, setData] = useState<Record<string, unknown> | null>(null); useEffect(() => { void apiRequest<Record<string, unknown>>(`/api/admin/people/users/${uid}`).then((result) => result.data && setData(result.data)); }, [uid]); const tabs = ["Overview", "Workspaces", "Challenges", "Participation", "Submissions", "Earnings", "Transactions", "Withdrawals", "Reports", "Restrictions", "Support", "Notes", "Activity History", "Technical Details"];
  return <><PageTitle title={String((data?.user as Record<string, unknown> | undefined)?.displayName ?? "User Control Centre")} subtitle="Read-only account preview with audited administrative controls." icon={<ShieldCheck className="text-[var(--gold)]" />} /><div className="mt-5 flex gap-2 overflow-x-auto">{tabs.map((tab) => <span key={tab} className="shrink-0 rounded-[8px] border border-white/10 px-3 py-2 text-xs font-bold">{tab}</span>)}</div>{data ? <RecordGrid records={[{ id: uid, ...((data.user as Record<string, unknown>) ?? {}) }]} empty="User data is unavailable." /> : <Card className="mt-6 h-52 animate-pulse" />}</>;
}

export function StatusWorkspace({ mode }: { mode: "status" | "jobs" | "readiness" }) {
  const [records, setRecords] = useState<RecordItem[]>([]); useEffect(() => { const url = mode === "jobs" ? "/api/admin/background-jobs" : "/api/admin/system-status"; void apiRequest<Record<string, RecordItem[]>>(url).then((result) => { const value = result.data?.[mode === "jobs" ? "jobs" : mode === "readiness" ? "readiness" : "services"]; if (value) setRecords(value); }); }, [mode]);
  return <><PageTitle title={mode === "status" ? "System Status" : mode === "jobs" ? "Background Jobs" : "Feature Readiness"} subtitle={mode === "jobs" ? "Real job records. Retry is permission restricted and idempotency checked." : "Configuration presence only. Manual verification and runtime incidents remain separate."} icon={<RefreshCw className="text-[var(--gold)]" />} /><RecordGrid records={records} empty={mode === "jobs" ? "No background job records are available." : "No provider readiness records are available."} /></>;
}

export function HelpCentre() { const topics = ["First-time admin walkthrough", "Status glossary", "Financial glossary", "Challenge lifecycle guide", "Daily admin operations", "Challenge review", "Withdrawal approval", "Refund approval", "Chargeback handling", "Sponsor approval", "Host verification", "Support ticket handling", "Dispute handling", "Appeal handling", "Emergency controls", "Creating administrators", "Finance reconciliation", "Event operations", "Tournament correction", "Content publishing"]; return <><PageTitle title="Admin Help Centre" subtitle="Operational guidance and handover content inside Challenge Suite." icon={<LifeBuoy className="text-[var(--gold)]" />} /><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{topics.map((topic) => <Card key={topic} className="p-5"><h2 className="font-black">{topic}</h2><p className="mt-2 text-sm text-slate-400">Follow permission checks, require reasons for sensitive actions, review impact, and confirm the audit entry.</p></Card>)}</div><Card className="mt-7 p-6"><p className="text-xs font-black uppercase text-[var(--gold)]">Developer Support</p><h2 className="mt-2 text-xl font-black">Anjola Samuel</h2><a className="mt-3 inline-flex min-h-11 items-center text-[var(--gold)]" href="mailto:anjolaolalekan777@gmail.com">anjolaolalekan777@gmail.com</a><p className="mt-3 text-sm text-slate-400">Include environment and error reference. Never attach secrets. Training Mode is available only in staging or development.</p></Card></>;
}

function RecordGrid({ records, empty }: { records: RecordItem[]; empty: string }) { return <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{records.map((record) => <Card key={record.id} className="p-5"><h2 className="font-black">{String(record.displayName ?? record.name ?? record.title ?? record.subject ?? record.id)}</h2><dl className="mt-4 space-y-2 text-sm">{Object.entries(record).filter(([key, value]) => key !== "id" && value !== null && typeof value !== "object").slice(0, 8).map(([key, value]) => <div key={key} className="flex justify-between gap-4"><dt className="text-slate-500">{labels(key)}</dt><dd className="text-right font-bold">{labels(value)}</dd></div>)}</dl></Card>)}{!records.length ? <Card className="md:col-span-2 xl:col-span-3"><EmptyState icon={<AlertTriangle />} title={empty} body="Real records will appear when the corresponding workflow creates them." /></Card> : null}</div>; }
