"use client";
import { useEffect, useState } from "react";
import { Trophy } from "lucide-react";
import { apiRequest } from "@/lib/api/client";
import { Card, EmptyState, PageTitle } from "@/components/ui";

const tabs = ["Overview", "Lifecycle", "Participants", "Submissions", "Voting", "Prize Funding", "Finance", "Settlement", "Reports", "Disputes", "Communications", "Activity History", "Technical Details"];
export function ChallengeControlCentre({ challengeId }: { challengeId: string }) {
  const [challenge, setChallenge] = useState<Record<string, unknown> | null>(null); const [tab, setTab] = useState("Overview");
  useEffect(() => { void apiRequest<{ challenges: Array<Record<string, unknown> & { id: string }> }>("/api/admin/operations").then((result) => setChallenge(result.data?.challenges.find((item) => item.id === challengeId) ?? null)); }, [challengeId]);
  return <><PageTitle title={String(challenge?.title ?? "Challenge Control Centre")} subtitle="Review lifecycle, participants, finance, safety, and audit history without bypassing state rules." icon={<Trophy className="text-[var(--gold)]" />} /><div className="mt-5 flex gap-2 overflow-x-auto" role="tablist">{tabs.map((value) => <button key={value} role="tab" aria-selected={tab === value} onClick={() => setTab(value)} className={`min-h-11 shrink-0 rounded-[8px] px-4 text-sm font-bold ${tab === value ? "bg-[var(--gold)] text-black" : "border border-white/10"}`}>{value}</button>)}</div>{challenge ? <Card className="mt-6 p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase text-[var(--gold)]">{tab}</p><h2 className="mt-2 text-xl font-black">{String(challenge.title)}</h2></div><span className="rounded-[8px] border border-white/10 px-3 py-2 text-xs font-bold">{String(challenge.status ?? "recorded").replaceAll("_", " ")}</span></div><dl className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Object.entries(challenge).filter(([key, value]) => key !== "id" && value !== null && typeof value !== "object" && (tab === "Technical Details" || !/(Id|Ids|Reference)$/.test(key))).map(([key, value]) => <div key={key} className="rounded-[8px] bg-white/[0.03] p-4"><dt className="text-xs font-bold text-slate-500">{key.replace(/([A-Z])/g, " $1")}</dt><dd className="mt-2 font-bold">{String(value)}</dd></div>)}</dl>{["Lifecycle", "Finance", "Settlement"].includes(tab) ? <div className="mt-6 rounded-[8px] border border-amber-400/30 bg-amber-400/5 p-4 text-sm text-amber-100"><strong>Impact preview required.</strong> Sensitive edits require a reason, recent authentication, valid state transition, creator notification, participant notification for material changes, and an audit entry.</div> : null}</Card> : <Card className="mt-6"><EmptyState icon={<Trophy />} title="Challenge not found" body="Only real challenge records are displayed." /></Card>}</>;
}
