"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { Button, Card, Field, LinkButton, PageTitle, inputClass, textareaClass } from "@/components/ui";
import { apiRequest } from "@/lib/api/client";

type Item = Record<string, unknown> & { id: string };
type Operations = { challenges: Item[]; completedChallenges: Item[]; participants: Item[]; submissions: Item[]; winners: Item[]; votes: Item[]; attendance: Item[]; sponsorInterest: Item[]; notifications: Item[]; controls: Record<string, boolean> };
const REPORT_TABS = ["Participant", "Submission", "Vote", "Winner", "Attendance", "Sponsor Interest"] as const;
const SUBMISSION_TABS = ["Pending Review", "Approved", "Rejected", "Flagged", "Resubmission Requested"] as const;
const PARTICIPANT_TABS = ["All", "Pending", "Approved", "Rejected", "Checked In", "Disqualified"] as const;

export default function HostOperationsPage() {
  const { tool = "participants" } = useParams<{ tool: string }>();
  const [data, setData] = useState<Operations | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); const result = await apiRequest<Operations>("/api/host/operations"); if (result.ok && result.data) { setData(result.data); setError(""); } else setError(result.message); setLoading(false); }
  useEffect(() => { void load(); }, []);
  if (loading) return <AppShell><Card className="mx-auto h-64 max-w-7xl animate-pulse" aria-label="Loading host operations" /></AppShell>;
  if (error || !data) return <AppShell><Card className="mx-auto max-w-3xl p-6"><h1 className="text-2xl font-black">Host operations unavailable</h1><p className="mt-3 text-red-200">{error || "Host records could not be loaded."}</p><Button className="mt-5" onClick={() => void load()}>Retry</Button></Card></AppShell>;
  return <AppShell><div className="mx-auto max-w-7xl">{tool === "reports" ? <ReportsView data={data} /> : tool === "submissions" ? <SubmissionsView data={data} reload={load} /> : tool === "participants" ? <ParticipantsView data={data} reload={load} /> : <GenericView tool={tool} data={data} />}</div></AppShell>;
}

function ReportsView({ data }: { data: Operations }) {
  const [tab, setTab] = useState<(typeof REPORT_TABS)[number]>("Participant");
  const key = tab === "Sponsor Interest" ? "sponsor_interest" : tab.toLowerCase();
  const source = key === "participant" ? data.participants : key === "submission" ? data.submissions : key === "vote" ? data.votes : key === "winner" ? data.winners : key === "attendance" ? data.attendance : data.sponsorInterest;
  const emptyCopy: Record<string, string> = { participant: "No participant report available yet. Participants will appear after users register for this competition.", submission: "No submission report available yet. Submissions will appear after participants upload entries.", vote: "No vote report available yet. Vote reports become available when voting starts.", winner: "No winner report available yet. Winner reports become available after winners are finalized.", attendance: "No attendance report available yet. Attendance reports become available after event check-in begins.", sponsor_interest: "No sponsor-interest report available yet. Sponsor interest will appear after sponsor requests are received." };
  return <><PageTitle title="Reports & Results" subtitle="Reports are generated from confirmed participant, submission, voting, winner, attendance, and sponsor-interest records." />
    <Tabs labels={REPORT_TABS} selected={tab} onSelect={(value) => setTab(value as typeof tab)} />
    {!data.completedChallenges.length ? <PlainEmpty title="No completed challenges yet" body="Reports become available after an owned competition is completed." /> : <div className="mt-6 grid gap-4">{data.completedChallenges.map((challenge) => {
      const records = source.filter((item) => String(item.challengeId ?? "") === challenge.id);
      const count = records.length;
      return <Card key={challenge.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><h2 className="break-words text-lg font-black">{String(challenge.title ?? "Challenge")}</h2><p className="mt-1 text-sm capitalize text-slate-400">{String(challenge.status ?? challenge.lifecycleStatus ?? "completed").replaceAll("_", " ")} · {challenge.id}</p><p className="mt-2 text-sm text-slate-300">{tab}: {count} record{count === 1 ? "" : "s"}</p><p className="mt-1 text-xs text-slate-500">Updated {formatDate(challenge.updatedAt)}</p></div><div className="flex flex-wrap gap-2">{count ? <LinkButton href={`/api/host/reports/${challenge.id}?type=${key}`}>Export CSV</LinkButton> : <Button disabled variant="secondary">No data to export</Button>}<LinkButton href={`/challenges/${challenge.id}`} variant="ghost">View Competition</LinkButton></div></div>{!count ? <p className="mt-4 border-t border-white/10 pt-4 text-sm text-slate-400">{emptyCopy[key]}</p> : null}</Card>;
    })}</div>}
  </>;
}

function SubmissionsView({ data, reload }: { data: Operations; reload: () => Promise<void> }) {
  const [tab, setTab] = useState<(typeof SUBMISSION_TABS)[number]>("Pending Review");
  const [review, setReview] = useState<Item | null>(null);
  const [action, setAction] = useState("approve");
  const [reason, setReason] = useState("");
  const [changes, setChanges] = useState("");
  const [deadline, setDeadline] = useState("");
  const [note, setNote] = useState("");
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  const normalized = (item: Item) => String(item.status ?? item.moderationStatus ?? "pending_review").toLowerCase();
  const matches = (item: Item, label: string) => { const status = normalized(item); return label === "Pending Review" ? ["pending", "pending_review", "submitted"].includes(status) : label === "Resubmission Requested" ? ["resubmission_requested", "needs_changes"].includes(status) : status === label.toLowerCase(); };
  const items = data.submissions.filter((item) => matches(item, tab));
  async function submit(item: Item, nextAction: string, direct = false) {
    if (!direct) { setReview(item); setAction(nextAction); setReason(""); setChanges(""); setDeadline(""); setNote(""); setMessage(""); return; }
    setSaving(true); const result = await apiRequest(`/api/challenges/${item.challengeId}/manage`, { method: "PATCH", body: JSON.stringify({ targetType: "submission", targetId: item.id, action: nextAction }) }); setSaving(false); setMessage(result.message); if (result.ok) { setReview(null); await reload(); }
  }
  async function confirm() { if (!review) return; setSaving(true); const result = await apiRequest(`/api/challenges/${review.challengeId}/manage`, { method: "PATCH", body: JSON.stringify({ targetType: "submission", targetId: review.id, action, reason, requestedChanges: changes, resubmissionDeadline: deadline, note }) }); setSaving(false); setMessage(result.message); if (result.ok) { setReview(null); await reload(); } }
  return <><PageTitle title="Submission Review" subtitle="Review submissions, approve eligible entries, request fixes, or flag issues based on your competition rules." /><Tabs labels={SUBMISSION_TABS} selected={tab} onSelect={(value) => setTab(value as typeof tab)} counts={Object.fromEntries(SUBMISSION_TABS.map((label) => [label, data.submissions.filter((item) => matches(item, label)).length]))} />
    {!items.length ? <PlainEmpty title={`No ${tab.toLowerCase()} submissions`} body="Submission records will appear here when they reach this review state." /> : <div className="mt-6 grid gap-4">{items.map((item) => <Card key={item.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-black">{String(item.title ?? item.challengeTitle ?? "Submission")}</h2><p className="mt-1 text-sm text-slate-400">{String(item.participantName ?? item.displayName ?? "Participant")} · {String(item.status ?? "pending_review").replaceAll("_", " ")}</p><p className="mt-2 text-xs text-slate-500">Submitted {formatDate(item.submittedAt ?? item.createdAt)}{item.resubmissionDeadline ? ` · Resubmit by ${formatDate(item.resubmissionDeadline)}` : ""}</p>{item.rejectionReason ? <p className="mt-2 text-sm text-red-200">Reason: {String(item.rejectionReason)}</p> : null}{item.requestedChanges ? <p className="mt-2 text-sm text-yellow-100">Requested changes: {String(item.requestedChanges)}</p> : null}</div><div className="flex flex-wrap gap-2">{["pending", "pending_review", "submitted"].includes(normalized(item)) ? <><Button onClick={() => void submit(item, "approve", true)} disabled={saving}>Approve</Button><Button variant="secondary" onClick={() => void submit(item, "reject")}>Reject</Button><Button variant="secondary" onClick={() => void submit(item, "request_resubmission")}>Request Resubmission</Button><Button variant="ghost" onClick={() => void submit(item, "flag")}>Flag</Button></> : null}<Button variant="secondary" onClick={() => { setReview(item); setAction("view"); }}>View Details</Button><LinkButton href={`/challenges/${item.challengeId}`} variant="ghost">View Competition</LinkButton></div></div></Card>)}</div>}
    {review ? <ReviewDialog item={review} action={action} setAction={setAction} reason={reason} setReason={setReason} changes={changes} setChanges={setChanges} deadline={deadline} setDeadline={setDeadline} note={note} setNote={setNote} message={message} saving={saving} onClose={() => setReview(null)} onConfirm={confirm} /> : null}
  </>;
}

function ParticipantsView({ data, reload }: { data: Operations; reload: () => Promise<void> }) {
  const [challengeId, setChallengeId] = useState(""); const [tab, setTab] = useState("All"); const [search, setSearch] = useState(""); const [payment, setPayment] = useState("all"); const [submission, setSubmission] = useState("all"); const [sort, setSort] = useState("newest"); const [target, setTarget] = useState<Item | null>(null); const [action, setAction] = useState(""); const [reason, setReason] = useState(""); const [message, setMessage] = useState("");
  const challenge = data.challenges.find((item) => item.id === challengeId);
  const statusMatch = (item: Item) => tab === "All" || (tab === "Checked In" ? String(item.checkInStatus ?? "") === "checked_in" : tab === "Disqualified" ? String(item.disqualificationStatus ?? item.status ?? "").includes("disqual") : String(item.approvalStatus ?? item.status ?? "").toLowerCase() === tab.toLowerCase());
  const items = useMemo(() => data.participants.filter((item) => String(item.challengeId ?? "") === challengeId && statusMatch(item) && (payment === "all" || String(item.paymentStatus ?? "not_required") === payment) && (submission === "all" || String(item.submissionStatus ?? "not_started") === submission) && (!search || `${item.displayName ?? ""} ${item.username ?? ""} ${item.email ?? ""}`.toLowerCase().includes(search.toLowerCase()))).sort((a, b) => sort === "name" ? String(a.displayName ?? "").localeCompare(String(b.displayName ?? "")) : sort === "oldest" ? Date.parse(String(a.createdAt ?? a.joinedAt ?? "")) - Date.parse(String(b.createdAt ?? b.joinedAt ?? "")) : Date.parse(String(b.createdAt ?? b.joinedAt ?? "")) - Date.parse(String(a.createdAt ?? a.joinedAt ?? ""))), [data.participants, challengeId, tab, payment, submission, search, sort]);
  async function mutate() { if (!target || !challengeId) return; const result = await apiRequest(`/api/challenges/${challengeId}/manage`, { method: "PATCH", body: JSON.stringify({ targetType: "participant", targetId: target.id, action, reason }) }); setMessage(result.message); if (result.ok) { setTarget(null); await reload(); } }
  return <><PageTitle title="Participant Management" subtitle="Select a competition to review registration, payment, submission, approval, and check-in status." />
    <Card className="mt-6 p-5"><Field label="Competition"><select className={inputClass} value={challengeId} onChange={(event) => setChallengeId(event.target.value)}><option value="">Select a competition to manage participants</option>{data.challenges.map((item) => <option key={item.id} value={item.id}>{String(item.title ?? "Challenge")} · {String(item.status ?? "draft")} · {Number(item.participantCount ?? 0)} participants</option>)}</select></Field></Card>
    {!challengeId ? <PlainEmpty title="Select a competition to manage participants" body="Choose one of your hosted competitions before participant records are shown." /> : <><Tabs labels={PARTICIPANT_TABS} selected={tab} onSelect={setTab} /><div className="mt-4 grid gap-3 md:grid-cols-4"><input className={inputClass} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search participant" aria-label="Search participant" /><select className={inputClass} value={payment} onChange={(event) => setPayment(event.target.value)} aria-label="Payment status"><option value="all">All payment states</option><option value="not_required">Not Required</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select><select className={inputClass} value={submission} onChange={(event) => setSubmission(event.target.value)} aria-label="Submission status"><option value="all">All submission states</option><option value="not_started">Not Started</option><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="pending_review">Pending Review</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="resubmission_requested">Resubmission Requested</option></select><select className={inputClass} value={sort} onChange={(event) => setSort(event.target.value)} aria-label="Sort participants"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="name">Name</option></select></div>
      {!items.length ? <PlainEmpty title="No Participants Yet" body="Share your competition link. Registrations will appear here." action={<LinkButton href="/host/challenges">View Hosted Competitions</LinkButton>} /> : <div className="mt-6 grid gap-4">{items.map((item) => <Card key={item.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-black">{String(item.displayName ?? item.username ?? "Participant")}</h2><p className="mt-1 text-sm text-slate-400">Registration {String(item.approvalStatus ?? item.status ?? "pending")} · Payment {String(item.paymentStatus ?? "not_required")} · Submission {String(item.submissionStatus ?? "not_started")}</p><p className="mt-2 text-xs text-slate-500">Registered {formatDate(item.createdAt ?? item.joinedAt)} · Check-in {String(item.checkInStatus ?? "not_checked_in")}</p>{item.disqualificationStatus === "pending_admin_review" ? <p className="mt-2 text-sm text-yellow-100">Disqualification pending admin review</p> : null}</div><div className="flex flex-wrap gap-2"><LinkButton href={item.username ? `/profile/${item.username}` : `/profile/${item.userId}`} variant="ghost">View Profile</LinkButton>{item.submissionId ? <LinkButton href={`/submissions/${item.submissionId}`} variant="ghost">View Entry</LinkButton> : null}<LinkButton href={`/challenges/${challengeId}`} variant="ghost">View Challenge</LinkButton><Button onClick={() => { setTarget(item); setAction("approve"); setReason(""); }}>Approve Registration</Button><Button variant="secondary" onClick={() => { setTarget(item); setAction("reject"); setReason(""); }}>Reject Registration</Button><Button variant="secondary" onClick={() => { setTarget(item); setAction("request_info"); setReason(""); }}>Request Info</Button><LinkButton href={`/messages?recipientId=${encodeURIComponent(String(item.userId ?? ""))}`} variant="secondary">Message Participant</LinkButton>{challenge?.isLiveEvent || String(challenge?.type ?? "").toLowerCase().includes("live") ? <Button variant="secondary" onClick={() => { setTarget(item); setAction("check_in"); setReason(""); }}>Check In</Button> : null}<Button variant="ghost" onClick={() => { setTarget(item); setAction("request_disqualification"); setReason(""); }}>Disqualify</Button></div></div></Card>)}</div>}
      <div className="mt-5">{items.length ? <LinkButton href={`/api/host/reports/${challengeId}?type=participant`}>Export Participants</LinkButton> : <Button disabled variant="secondary">No data to export</Button>}</div>
    </>}
    {target ? <ReasonDialog title={action === "request_disqualification" ? "Request disqualification review" : action === "request_info" ? "Request participant information" : action === "reject" ? "Reject registration" : action === "check_in" ? "Confirm live-event check-in" : "Approve registration"} reasonRequired={["reject", "request_info", "request_disqualification"].includes(action)} reason={reason} setReason={setReason} message={message} onClose={() => setTarget(null)} onConfirm={mutate} /> : null}
  </>;
}

function GenericView({ tool, data }: { tool: string; data: Operations }) { const items = tool === "notifications" ? data.notifications : tool === "winners" ? data.winners : data.challenges; return <><PageTitle title={tool.split("-").map(capitalize).join(" ")} subtitle="Review real host records for your competitions." />{items.length ? <div className="mt-6 grid gap-4">{items.map((item) => <Card key={item.id} className="p-5"><h2 className="text-lg font-black">{String(item.title ?? item.name ?? "Host record")}</h2><p className="mt-2 text-sm text-slate-400">{String(item.status ?? "recorded").replaceAll("_", " ")}</p></Card>)}</div> : <PlainEmpty title="No records yet" body="Records will appear here when real competition activity is available." />}</>; }
function Tabs({ labels, selected, onSelect, counts }: { labels: readonly string[]; selected: string; onSelect: (value: string) => void; counts?: Record<string, number> }) { return <div className="mt-6 flex gap-2 overflow-x-auto pb-2" role="tablist">{labels.map((label) => <Button key={label} variant={selected === label ? "primary" : "secondary"} onClick={() => onSelect(label)}>{label}{counts ? ` (${counts[label] ?? 0})` : ""}</Button>)}</div>; }
function PlainEmpty({ title, body, action }: { title: string; body: string; action?: React.ReactNode }) { return <Card className="mt-6 p-8 text-center"><h2 className="text-xl font-black">{title}</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-400">{body}</p>{action ? <div className="mt-5 flex justify-center">{action}</div> : null}</Card>; }
function ReviewDialog(props: { item: Item; action: string; setAction: (value: string) => void; reason: string; setReason: (value: string) => void; changes: string; setChanges: (value: string) => void; deadline: string; setDeadline: (value: string) => void; note: string; setNote: (value: string) => void; message: string; saving: boolean; onClose: () => void; onConfirm: () => Promise<void> }) { const { item, action, setAction, reason, setReason, changes, setChanges, deadline, setDeadline, note, setNote, message, saving, onClose, onConfirm } = props; return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/75 p-3 sm:items-center" role="dialog" aria-modal="true" aria-labelledby="review-title" onKeyDown={(event) => { if (event.key === "Escape") onClose(); }}><Card className="max-h-[92vh] w-full max-w-3xl overflow-y-auto p-5 sm:p-7"><div className="flex justify-between gap-4"><div><h2 id="review-title" className="text-2xl font-black">Submission review</h2><p className="mt-2 text-sm text-slate-400">{String(item.title ?? "Submission")} · {String(item.status ?? "pending_review")}</p></div><Button autoFocus variant="ghost" onClick={onClose}>Close</Button></div>{item.mediaUrl || item.imageUrl ? <img src={String(item.mediaUrl ?? item.imageUrl)} alt="Submitted media" className="mt-5 max-h-80 w-full rounded-[8px] object-contain" /> : <p className="mt-5 rounded-[8px] border border-white/10 p-4 text-sm text-slate-400">No reviewable media is attached to this submission.</p>}<div className="mt-5 grid gap-3 sm:grid-cols-4">{["approve", "reject", "flag", "request_resubmission"].map((value) => <Button key={value} variant={action === value ? "primary" : "secondary"} onClick={() => setAction(value)}>{value.replaceAll("_", " ")}</Button>)}</div>{["reject", "flag"].includes(action) ? <div className="mt-5"><Field label={action === "reject" ? "Rejection reason" : "Flag reason"}><textarea className={textareaClass} required value={reason} onChange={(event) => setReason(event.target.value)} /></Field></div> : null}{action === "request_resubmission" ? <div className="mt-5 grid gap-4"><Field label="Requested changes"><textarea className={textareaClass} required value={changes} onChange={(event) => setChanges(event.target.value)} /></Field><Field label="Resubmission deadline"><input className={inputClass} type="datetime-local" required value={deadline} onChange={(event) => setDeadline(event.target.value)} /></Field><Field label="Optional note"><textarea className={textareaClass} value={note} onChange={(event) => setNote(event.target.value)} /></Field></div> : null}{message ? <p className="mt-4 text-sm text-red-200" role="alert">{message}</p> : null}<div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button onClick={() => void onConfirm()} disabled={saving || action === "view"}>{saving ? "Saving..." : "Confirm Review"}</Button></div></Card></div>; }
function ReasonDialog({ title, reasonRequired, reason, setReason, message, onClose, onConfirm }: { title: string; reasonRequired: boolean; reason: string; setReason: (value: string) => void; message: string; onClose: () => void; onConfirm: () => Promise<void> }) { return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/75 p-3 sm:items-center" role="dialog" aria-modal="true" aria-labelledby="participant-action-title" onKeyDown={(event) => { if (event.key === "Escape") onClose(); }}><Card className="w-full max-w-xl p-6"><h2 id="participant-action-title" className="text-2xl font-black">{title}</h2>{reasonRequired ? <div className="mt-5"><Field label="Reason"><textarea autoFocus className={textareaClass} required value={reason} onChange={(event) => setReason(event.target.value)} /></Field></div> : null}{message ? <p className="mt-4 text-sm text-red-200">{message}</p> : null}<div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button autoFocus={!reasonRequired} onClick={() => void onConfirm()}>Confirm</Button></div></Card></div>; }
function formatDate(value: unknown) { const date = new Date(String(value ?? "")); return Number.isFinite(date.getTime()) ? date.toLocaleString() : "Not recorded"; }
function capitalize(value: string) { return value.charAt(0).toUpperCase() + value.slice(1); }
