import { z } from "zod";
import { getAdminDb } from "@/lib/firebase/admin";
import { getStripe } from "@/lib/stripe";
import { writeAuditLog } from "@/lib/server/audit";
import { requireAdminPermission, requireRecentAdminAuthentication } from "@/lib/server/auth";
import { fail, ok, readJson, serverError, serverUnavailable, validationError } from "@/lib/server/responses";

const schema = z.object({ disputeId: z.string().min(1), chargebackCaseId: z.string().min(1), reason: z.string().trim().min(8).max(1000), evidence: z.object({ customerName: z.string().trim().min(2).max(120), customerEmail: z.string().trim().email(), productDescription: z.string().trim().min(10).max(500), customerCommunication: z.string().trim().min(1).max(10000).optional() }) });
export async function GET(request: Request) { const { response } = await requireAdminPermission(request, "chargebacks.review"); if (response) return response; const db = getAdminDb(); if (!db) return serverUnavailable("Chargebacks"); const snap = await db.collection("chargebackCases").orderBy("createdAt", "desc").limit(200).get(); return ok({ chargebacks: snap.docs.map((doc) => ({ id: doc.id, ...doc.data() })) }); }
export async function POST(request: Request) { const { user, response } = await requireRecentAdminAuthentication(request, "chargebacks.submitProvider"); if (response) return response; const db = getAdminDb(); if (!db) return serverUnavailable("Chargebacks"); const body = await readJson(request); if (body.response) return body.response; const parsed = schema.safeParse(body.body); if (!parsed.success) return validationError({ request: parsed.error.issues[0]?.message ?? "Complete the required dispute evidence." }); const stripe = getStripe(); if (!stripe) return fail("Stripe dispute provider is not connected.", 503, undefined, "PROVIDER_NOT_CONFIGURED"); try { const ref = db.collection("chargebackCases").doc(parsed.data.chargebackCaseId); const snap = await ref.get(); if (!snap.exists) return fail("Chargeback case not found.", 404); if (snap.data()?.providerSubmissionId) return ok({ id: ref.id, providerSubmissionId: snap.data()?.providerSubmissionId }, "Existing provider submission returned."); const result = await stripe.disputes.update(parsed.data.disputeId, { evidence: { customer_name: parsed.data.evidence.customerName, customer_email_address: parsed.data.evidence.customerEmail, product_description: parsed.data.evidence.productDescription, customer_communication: parsed.data.evidence.customerCommunication }, submit: true }, { idempotencyKey: `challenge-suite-dispute-${ref.id}` }); const now = new Date().toISOString(); await ref.set({ status: "provider_submitted", providerSubmissionId: result.id, providerStatus: result.status, submittedBy: user!.uid, submittedAt: now, reason: parsed.data.reason, exposedFundsFrozen: true, updatedAt: now }, { merge: true }); await writeAuditLog({ actorId: user!.uid, actorType: "admin", action: "chargeback.provider_submitted", targetType: "dispute", targetId: ref.id, reason: parsed.data.reason, metadata: { providerDisputeId: result.id } }, db); return ok({ id: ref.id, providerSubmissionId: result.id, status: result.status }, "Chargeback evidence submitted to provider."); } catch (error) { return serverError("Chargeback evidence could not be submitted.", error instanceof Error ? error.message : error); } }
