import { z } from "zod";
import { getAdminDb } from "@/lib/firebase/admin";
import { operationalTaskId, safetyTriage, taskDeadline } from "@/lib/server/admin-operations";
import { requireRequestUser } from "@/lib/server/auth";
import { ok, readJson, serverError, serverUnavailable, validationError } from "@/lib/server/responses";

const schema = z.object({ category: z.enum(["account", "challenge", "payment", "payout", "refund", "submission", "voting", "sponsor", "event", "tournament", "technical_issue", "safety_concern", "other"]), subject: z.string().trim().min(5).max(160), description: z.string().trim().min(20).max(5000), relatedType: z.string().trim().max(40).optional(), relatedId: z.string().trim().max(160).optional(), prioritySuggestion: z.enum(["low", "normal", "high", "urgent"]).default("normal"), attachmentPaths: z.array(z.string().trim().max(500)).max(5).default([]), contactPreference: z.enum(["in_app", "email"]).default("in_app") });
function safeAttachment(userId: string, path: string) { return path.startsWith(`users/${userId}/support/`) && !/^https?:/i.test(path) && !path.includes(".."); }

export async function GET(request: Request) { const { user, response } = await requireRequestUser(request); if (response) return response; const db = getAdminDb(); if (!db) return serverUnavailable("Support tickets"); const snap = await db.collection("supportTickets").where("userId", "==", user!.uid).limit(100).get(); return ok({ tickets: snap.docs.map((doc) => ({ id: doc.id, ...doc.data() })) }); }
export async function POST(request: Request) {
  const { user, response } = await requireRequestUser(request); if (response) return response; const db = getAdminDb(); if (!db) return serverUnavailable("Support tickets"); const body = await readJson(request); if (body.response) return body.response; const parsed = schema.safeParse(body.body); if (!parsed.success) return validationError({ request: parsed.error.issues[0]?.message ?? "Invalid ticket." });
  if (parsed.data.attachmentPaths.some((path) => !safeAttachment(user!.uid, path))) return validationError({ attachmentPaths: "Attachments must be native uploads from your support folder." });
  try { const now = new Date().toISOString(); const ref = db.collection("supportTickets").doc(); const triage = parsed.data.category === "safety_concern" ? safetyTriage("safety_concern") : { priority: parsed.data.prioritySuggestion, immediateEscalationRequired: false }; const taskId = operationalTaskId("support_ticket", ref.id); const batch = db.batch(); batch.set(ref, { id: ref.id, userId: user!.uid, ...parsed.data, status: "submitted", priority: triage.priority, acknowledgedAt: now, slaDueAt: taskDeadline("support_ticket", now), createdAt: now, updatedAt: now }); batch.set(db.collection("adminActionTasks").doc(taskId), { id: taskId, sourceType: "support_ticket", sourceCollection: "supportTickets", sourceId: ref.id, title: parsed.data.subject, reason: "A user submitted a support ticket.", state: "unassigned", priority: triage.priority, slaDueAt: taskDeadline("support_ticket", now), createdAt: now, updatedAt: now }); await batch.commit(); return ok({ ticketId: ref.id, status: "submitted" }, "Support ticket submitted and acknowledged."); } catch (error) { return serverError("Support ticket could not be created.", error instanceof Error ? error.message : error); }
}
