export type CanonicalControlType = "text" | "textarea" | "email" | "password" | "phone" | "url" | "number" | "currency" | "percentage" | "choice-cards" | "segmented-control" | "single-select" | "search-select" | "multi-select" | "entity-picker" | "multi-entity-picker" | "toggle" | "checkbox" | "date-picker" | "time-picker" | "datetime-picker" | "date-range-picker" | "duration-select" | "location-picker" | "media-picker" | "system-value" | "system-status";
export type CanonicalEntityType = "user" | "challenge" | "sponsor" | "judge" | "enterprise_staff" | "team_member" | "winner_candidate" | "payout_destination" | "tournament" | "submission";
export interface CanonicalFieldRule { control: CanonicalControlType; reason: string; source?: string; entityType?: CanonicalEntityType; multiple?: boolean; forbidFreeText?: boolean; systemControlled?: boolean }
const controlled = (control: CanonicalControlType, source: string, reason: string, extra: Partial<CanonicalFieldRule> = {}): CanonicalFieldRule => ({ control, source, reason, forbidFreeText: true, ...extra });
const entity = (entityType: CanonicalEntityType, multiple = false): CanonicalFieldRule => controlled(multiple ? "multi-entity-picker" : "entity-picker", `${entityType}Search`, "References must resolve to an authorized canonical entity ID.", { entityType, multiple });
export const FIELD_CONTROL_REGISTRY: Record<string, CanonicalFieldRule> = {
  accountType: controlled("choice-cards", "accountTypes", "Account types are canonical platform values."), plan: controlled("choice-cards", "plans", "Plans are canonical entitlements."),
  country: controlled("search-select", "countries", "Countries store canonical country codes."), countries: controlled("multi-select", "countries", "Country restrictions store canonical country codes.", { multiple: true }), stateRegion: controlled("search-select", "regionsByCountry", "Regions depend on the selected country."), language: controlled("search-select", "supportedLanguages", "Languages are platform-supported values."), timezone: controlled("search-select", "ianaTimezones", "Timezones store valid IANA values."),
  challengeType: controlled("choice-cards", "challengeTypes", "Challenge types are canonical values."), category: controlled("search-select", "challengeCategories", "Challenge categories use the shared taxonomy."), subcategory: controlled("search-select", "challengeSubcategoriesByCategory", "Subcategories depend on category."), eligibilityMode: controlled("choice-cards", "eligibilityModes", "Eligibility behavior is controlled."), geographicEligibility: controlled("choice-cards", "geographicEligibilityModes", "Geographic eligibility uses known modes."), participantListVisibility: controlled("segmented-control", "participantVisibilityOptions", "Visibility is controlled."), capacityMode: controlled("choice-cards", "capacityModes", "Capacity is limited or unlimited."), capacity: controlled("number", "capacityRules", "Capacity is a bounded whole number."), waitlistEnabled: controlled("toggle", "boolean", "Waitlist state is boolean."),
  preferredSponsorCategories: controlled("multi-select", "sponsorCategories", "Sponsor categories store stable slugs.", { multiple: true }), fundingPurpose: controlled("single-select", "fundingPurposes", "Payment purpose drives server-authoritative processing."),
  tournamentParticipationType: controlled("choice-cards", "tournamentParticipationTypes", "Tournament participation type is controlled."), tournamentEliminationType: controlled("choice-cards", "tournamentEliminationTypes", "Tournament elimination type is controlled."), tournamentBracketSize: controlled("single-select", "tournamentBracketSizes", "Only supported bracket sizes may be selected."),
  judge: entity("judge"), judges: entity("judge", true), challenge: entity("challenge"), sponsor: entity("sponsor"), challengeLead: entity("enterprise_staff"), internalTeam: entity("enterprise_staff", true), winner: entity("winner_candidate"), savedPayoutDestination: entity("payout_destination"),
  payoutMethod: controlled("single-select", "payoutMethods", "Payout methods are provider-supported values."), payoutCurrency: controlled("single-select", "payoutCurrencies", "Payout currency must be supported."), startDate: controlled("date-picker", "calendar", "Dates use a calendar control."), submissionOpensAt: controlled("datetime-picker", "challengeTimeline", "Lifecycle times use canonical date-time values."), submissionClosesAt: controlled("datetime-picker", "challengeTimeline", "Lifecycle times use canonical date-time values."), votingOpensAt: controlled("datetime-picker", "challengeTimeline", "Lifecycle times use canonical date-time values."), votingClosesAt: controlled("datetime-picker", "challengeTimeline", "Lifecycle times use canonical date-time values."), resultsAt: controlled("datetime-picker", "challengeTimeline", "Lifecycle times use canonical date-time values."),
  challengeStatus: { control: "system-status", reason: "Lifecycle state changes only through authorized domain actions.", forbidFreeText: true, systemControlled: true }, participantStatus: { control: "system-status", reason: "Participant state changes only through authorized domain actions.", forbidFreeText: true, systemControlled: true }, submissionStatus: { control: "system-status", reason: "Submission state changes only through authorized domain actions.", forbidFreeText: true, systemControlled: true }, payoutStatus: { control: "system-status", reason: "Payout state is provider and admin controlled.", forbidFreeText: true, systemControlled: true }
};
export const GLOBAL_FORM_RULE = { searchQueries: "text", knownTaxonomies: "selector", booleans: "toggle", entities: "entity-picker", dates: "date/datetime-picker", money: "currency-input", boundedNumbers: "number-input", systemState: "system-controlled", authoredContent: "text/textarea" } as const;
export const FREEFORM_AUTHORING_FIELDS = ["title", "shortDescription", "fullDescription", "challengeRules", "ruleText", "submissionInstructions", "submissionDescription", "bio", "displayName", "username", "announcementTitle", "announcementBody", "comment", "reply", "message", "requestChangesReason", "rejectionReason", "disqualificationReason", "cancellationReason", "reportDetails", "appealExplanation", "supportSubject", "supportBody", "internalNote", "reviewNote", "proposalMessage", "deliverableTitle", "deliverableDescription", "deliverableInstructions", "campaignCopy", "ctaText", "teamName", "teamDescription", "eventTitle", "eventDescription", "eventInstructions", "tournamentName", "tournamentDescription", "internalReference"] as const;
export function assertCorrectFieldControl(semanticField: string, renderedControl: CanonicalControlType) { if (process.env.NODE_ENV === "production") return; const rule = FIELD_CONTROL_REGISTRY[semanticField]; if (rule?.forbidFreeText && (renderedControl === "text" || renderedControl === "textarea")) console.warn(`[Form Policy] "${semanticField}" must not use free text. Expected "${rule.control}".`); }
