import { z } from "zod";
import { getAdminDb } from "@/lib/firebase/admin";
import { getStripe } from "@/lib/stripe";
import { writeAuditLog } from "@/lib/server/audit";
import { requireAdminPermission, requireRecentAdminAuthentication } from "@/lib/server/auth";
import { conflict, fail, ok, readJson, serverError, serverUnavailable, validationError } from "@/lib/server/responses";

const PAYMENT_COLLECTIONS = ["challengeEntryPayments", "paidVotePurchases", "sponsorContributions", "predictionPayments", "doroCoinPurchases"] as const;
const createSchema = z.object({ paymentCollection: z.enum(PAYMENT_COLLECTIONS), paymentId: z.string().min(1).max(180), reason: z.string().trim().min(8).max(1000) });
const executeSchema = z.object({ refundCaseId: z.string().min(1), action: z.enum(["approve", "reject", "execute"]), reason: z.string().trim().min(8).max(1000) });

export async function GET(request: Request) { const { response } = await requireAdminPermission(request, "refunds.request"); if (response) return response; const db = getAdminDb(); if (!db) return serverUnavailable("Refunds"); const snap = await db.collection("refundCases").orderBy("createdAt", "desc").limit(200).get(); return ok({ refunds: snap.docs.map((doc) => ({ id: doc.id, ...doc.data() })), partialRefundsEnabled: false }); }

export async function POST(request: Request) {
  const { user, response } = await requireAdminPermission(request, "refunds.request"); if (response) return response; const db = getAdminDb(); if (!db) return serverUnavailable("Refunds"); const body = await readJson(request); if (body.response) return body.response; const parsed = createSchema.safeParse(body.body); if (!parsed.success) return validationError({ request: parsed.error.issues[0]?.message ?? "Invalid refund case." });
  try { const paymentRef = db.collection(parsed.data.paymentCollection).doc(parsed.data.paymentId); const payment = await paymentRef.get(); if (!payment.exists) return fail("Payment record not found.", 404); const data = payment.data() ?? {}; if (!["paid", "confirmed", "succeeded"].includes(String(data.status ?? data.paymentStatus))) return conflict("Only provider-confirmed payments can be refunded."); const id = `refund_${parsed.data.paymentCollection}_${parsed.data.paymentId}`; const ref = db.collection("refundCases").doc(id); const existing = await ref.get(); if (existing.exists) return ok({ id, ...existing.data() }, "Existing refund case returned."); const amountCents = Number(data.amountCents ?? data.grossAmountCents ?? data.amountMinor ?? 0); const now = new Date().toISOString(); const record = { id, paymentCollection: parsed.data.paymentCollection, paymentId: parsed.data.paymentId, userId: data.userId ?? null, amountCents, fullRefundAmountCents: amountCents, currency: data.currency ?? "USD", provider: data.provider ?? "stripe", providerPaymentIntentId: data.stripePaymentIntentId ?? data.paymentIntentId ?? null, status: "pending_review", reason: parsed.data.reason, partialRefundsEnabled: false, createdBy: user!.uid, createdAt: now, updatedAt: now }; await ref.create(record); await writeAuditLog({ actorId: user!.uid, actorType: "admin", action: "refund.case_created", targetType: "refund", targetId: id, reason: parsed.data.reason, after: record }, db); return ok(record, "Full refund case created for review."); } catch (error) { return serverError("Refund case could not be created.", error instanceof Error ? error.message : error); }
}

export async function PATCH(request: Request) {
  const { user, response } = await requireRecentAdminAuthentication(request, "refunds.approve"); if (response) return response; const db = getAdminDb(); if (!db) return serverUnavailable("Refunds"); const body = await readJson(request); if (body.response) return body.response; const parsed = executeSchema.safeParse(body.body); if (!parsed.success) return validationError({ request: parsed.error.issues[0]?.message ?? "Invalid refund decision." });
  try { const ref = db.collection("refundCases").doc(parsed.data.refundCaseId); const snap = await ref.get(); if (!snap.exists) return fail("Refund case not found.", 404); const record = snap.data() ?? {}; if (["succeeded", "rejected"].includes(String(record.status))) return ok({ id: ref.id, ...record }, "Existing refund outcome returned."); const now = new Date().toISOString(); if (parsed.data.action !== "execute") { const status = parsed.data.action === "approve" ? "approved" : "rejected"; await ref.set({ status, reviewedBy: user!.uid, reviewedAt: now, reviewReason: parsed.data.reason, updatedAt: now }, { merge: true }); await writeAuditLog({ actorId: user!.uid, actorType: "admin", action: `refund.${status}`, targetType: "refund", targetId: ref.id, reason: parsed.data.reason }, db); return ok({ id: ref.id, status }, `Refund ${status}.`); }
    if (record.status !== "approved") return conflict("Refund must be approved before provider execution."); const permission = await requireRecentAdminAuthentication(request, "refunds.execute"); if (permission.response) return permission.response; const stripe = getStripe(); if (!stripe) return fail("Stripe refund provider is not connected.", 503, undefined, "PROVIDER_NOT_CONFIGURED"); const paymentIntent = String(record.providerPaymentIntentId ?? ""); if (!paymentIntent) return conflict("Confirmed provider payment reference is missing."); const result = await stripe.refunds.create({ payment_intent: paymentIntent, reason: "requested_by_customer", metadata: { refundCaseId: ref.id, adminReason: parsed.data.reason.slice(0, 450) } }, { idempotencyKey: `challenge-suite-refund-${ref.id}` }); const status = result.status === "succeeded" ? "succeeded" : "processing"; const batch = db.batch(); batch.set(ref, { status, providerRefundId: result.id, providerStatus: result.status, executedBy: user!.uid, executedAt: now, updatedAt: now }, { merge: true }); batch.set(db.collection("cashLedger").doc(`refund_${ref.id}`), { id: `refund_${ref.id}`, transactionType: "refund", sourceType: "refund", sourceId: ref.id, amountCents: Number(record.amountCents ?? 0), currency: record.currency ?? "USD", direction: "debit", status: status === "succeeded" ? "posted" : "pending", immutable: true, providerReference: result.id, idempotencyKey: `refund_${ref.id}`, createdAt: now }); await batch.commit(); await writeAuditLog({ actorId: user!.uid, actorType: "admin", action: "refund.provider_executed", targetType: "refund", targetId: ref.id, reason: parsed.data.reason, metadata: { providerRefundId: result.id, providerStatus: result.status } }, db); return ok({ id: ref.id, status, providerRefundId: result.id }, "Provider refund submitted.");
  } catch (error) { return serverError("Refund action failed.", error instanceof Error ? error.message : error); }
}
