"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { CalendarCheck, FileCheck2, FileText, ReceiptText, Scale, Search, WalletCards } from "lucide-react";
import { SponsorShell, type SponsorShellProfile } from "@/components/sponsor/sponsor-shell";
import { Button, Card, EmptyState, LinkButton, inputClass } from "@/components/ui";
import { apiRequest } from "@/lib/api/client";
import { campaignFundingDisclaimer, contractStatuses, formatMoney, invoiceStatuses, label, legalDisclaimer, milestoneStatuses } from "@/lib/sponsor-finance";

type Item = Record<string, any>;

type LoadState = { profile: SponsorShellProfile | null; loading: boolean; error: string };
function useSponsorProfile(): [LoadState, (patch: Partial<LoadState>) => void] {
  const [state, setState] = useState<LoadState>({ profile: null, loading: true, error: "" });
  useEffect(() => { void apiRequest<{ sponsorProfile: SponsorShellProfile }>("/api/sponsor/profile").then((result) => setState((current) => ({ ...current, profile: result.ok ? result.data?.sponsorProfile ?? null : null, error: result.ok ? current.error : result.message || "Sponsor profile could not be loaded." }))); }, []);
  return [state, (patch) => setState((current) => ({ ...current, ...patch }))];
}
function Info({ title, value }: { title: string; value: any }) { return <div className="rounded-[8px] border border-slate-200 bg-slate-50 p-3"><p className="text-[11px] font-black uppercase tracking-[0.14em] text-slate-500">{title}</p><p className="mt-1 break-words font-bold text-slate-950">{value || "Not available yet"}</p></div>; }
function Notice({ children }: { children: React.ReactNode }) { return <Card className="border-[var(--gold)]/30 bg-yellow-950/10 p-5 text-sm leading-6 text-slate-200">{children}</Card>; }
function ErrorCard({ message }: { message: string }) { return message ? <Card className="mt-6 border-red-500/20 border border-red-200 bg-red-50 p-5 text-red-800">{message}</Card> : null; }
function LoadingGrid() { return <div className="mt-8 grid gap-5 lg:grid-cols-3">{[0,1,2].map((item) => <Card key={item} className="h-56 animate-pulse bg-slate-100" />)}</div>; }

export function SponsorContractsPage() {
  const [base, setBase] = useSponsorProfile(); const [contracts, setContracts] = useState<Item[]>([]); const [status, setStatus] = useState("all"); const [query, setQuery] = useState("");
  useEffect(() => { void apiRequest<{ contracts: Item[] }>("/api/sponsor/contracts").then((result) => { if (result.ok) setContracts(result.data?.contracts ?? []); else setBase({ error: result.message || "Contracts could not be loaded." }); setBase({ loading: false }); }); }, []);
  const filtered = useMemo(() => contracts.filter((item) => (status === "all" || item.status === status) && (!query || [item.title, item.linkedCampaignId, item.linkedProposalId, item.creatorOrHostContext].some((value) => String(value ?? "").toLowerCase().includes(query.toLowerCase())))), [contracts, query, status]);
  return <SponsorShell profile={base.profile}><div className="mx-auto max-w-7xl"><Header eyebrow="Contract Center" title="Sponsor contracts" body="Track contract records, review terms, signature readiness, and legal review status before any campaign funding can begin." action={<LinkButton href="/sponsor/contracts/templates">View Templates</LinkButton>} /><Notice>{legalDisclaimer}</Notice><FilterRow query={query} setQuery={setQuery} status={status} setStatus={setStatus} statuses={contractStatuses} placeholder="Search contracts" /><ErrorCard message={base.error} />{base.loading ? <LoadingGrid /> : filtered.length === 0 ? <EmptyState icon={<FileCheck2 />} title="No contracts yet." body="Accepted proposals will be converted into contracts before funding or campaign launch." action={<LinkButton href="/sponsor/proposals">Review Proposals</LinkButton>} /> : <div className="mt-8 grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{filtered.map((contract) => <Card key={contract.id} className="p-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-[var(--gold)]">{label(contract.status)}</p><h2 className="mt-3 text-2xl font-black">{contract.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">Signature status: {label(contract.signatureStatus)}</p><div className="mt-5 grid gap-3 text-sm"><Info title="Proposal" value={contract.linkedProposalId} /><Info title="Campaign" value={contract.linkedCampaignId} /><Info title="Value" value={formatMoney(contract.contractValueCents, contract.currency)} /><Info title="Next Action" value={contract.legalReviewNeeded ? "Legal review recommended" : "Review terms"} /></div><div className="mt-5"><LinkButton href={`/sponsor/contracts/${contract.id}`} variant="secondary">View Contract</LinkButton></div></Card>)}</div>}</div></SponsorShell>;
}

export function SponsorContractDetailPage() {
  const params = useParams<{ contractId: string }>(); const [base, setBase] = useSponsorProfile(); const [contract, setContract] = useState<Item | null>(null);
  useEffect(() => { if (!params?.contractId) return; void apiRequest<{ contract: Item }>(`/api/sponsor/contracts/${params.contractId}`).then((result) => { if (result.ok) setContract(result.data?.contract ?? null); else setBase({ error: result.message || "Contract could not be loaded." }); setBase({ loading: false }); }); }, [params?.contractId]);
  return <SponsorShell profile={base.profile}><div className="mx-auto max-w-6xl"><Header eyebrow="Contract Detail" title={contract?.title || "Sponsor contract"} body="Review terms, signature readiness, legal review notes, revisions, and activity history. Signature and funding actions remain disabled until secure provider workflows are connected." action={<LinkButton href="/sponsor/contracts" variant="secondary">Back to Contracts</LinkButton>} /><Notice>{legalDisclaimer}</Notice><ErrorCard message={base.error} />{base.loading ? <LoadingGrid /> : !contract ? <EmptyState icon={<FileText />} title="Contract not found." body="This contract may not exist or may not belong to your sponsor account." /> : <div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card className="p-6"><h2 className="text-2xl font-black">Terms</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info title="Status" value={label(contract.status)} /><Info title="Linked proposal" value={contract.linkedProposalId} /><Info title="Linked campaign" value={contract.linkedCampaignId} /><Info title="Contract value" value={formatMoney(contract.contractValueCents, contract.currency)} /><Info title="Signature" value={label(contract.signatureStatus)} /><Info title="Payment release" value="Not active" /></div><div className="mt-6 space-y-4 text-sm leading-6 text-slate-600"><p><strong className="text-slate-950">Payment terms:</strong> {contract.paymentTermsFoundation || "Payment terms not available yet."}</p><p><strong className="text-slate-950">Usage rights:</strong> {contract.contentUsageRightsFoundation || "Usage rights not available yet."}</p><p><strong className="text-slate-950">Confidentiality:</strong> {contract.confidentialityFoundation || "Confidentiality terms not available yet."}</p><p><strong className="text-slate-950">Disputes:</strong> {contract.disputeResolutionFoundation || "Dispute resolution terms not available yet."}</p></div></Card><Card className="p-6"><h2 className="text-2xl font-black">Available actions</h2><div className="mt-5 grid gap-3"><Button disabled variant="secondary">Send for Review</Button><Button disabled variant="ghost">PDF not available yet</Button><Button disabled variant="ghost">Mark Legal Review Needed</Button><Button disabled variant="ghost">Archive</Button></div><p className="mt-5 text-sm leading-6 text-slate-500">These actions are disabled until secure signature, funding, and legal review workflows are connected. No campaign launch or payment release is activated.</p></Card></div>}</div></SponsorShell>;
}

export function SponsorContractTemplatesPage() {
  const [base, setBase] = useSponsorProfile(); const [templates, setTemplates] = useState<Item[]>([]);
  useEffect(() => { void apiRequest<{ templates: Item[] }>("/api/sponsor/contracts/templates").then((result) => { if (result.ok) setTemplates(result.data?.templates ?? []); else setBase({ error: result.message || "Templates could not be loaded." }); setBase({ loading: false }); }); }, []);
  return <SponsorShell profile={base.profile}><div className="mx-auto max-w-7xl"><Header eyebrow="Legal Templates" title="Contract templates" body="Reusable workflow templates for sponsorship operations. These are not legal advice or binding e-signature flows." action={<LinkButton href="/sponsor/contracts" variant="secondary">Contract Center</LinkButton>} /><Notice>{legalDisclaimer}</Notice><ErrorCard message={base.error} />{base.loading ? <LoadingGrid /> : <div className="mt-8 grid gap-5 lg:grid-cols-3">{templates.map((template) => <Card key={template.id} className="p-5"><Scale className="text-[var(--gold)]" /><h2 className="mt-3 text-2xl font-black">{template.name}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{template.intendedUse}</p><div className="mt-4 flex flex-wrap gap-2">{(template.sections ?? []).map((section: string) => <span key={section} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{section}</span>)}</div><Button className="mt-5 w-full" disabled>Use Template</Button></Card>)}</div>}</div></SponsorShell>;
}

export function SponsorWalletPage() {
  const [base, setBase] = useSponsorProfile(); const [wallet, setWallet] = useState<Item | null>(null); const [transactions, setTransactions] = useState<Item[]>([]); const [commitments, setCommitments] = useState<Item[]>([]);
  useEffect(() => { void apiRequest<{ wallet: Item; transactions: Item[]; commitments: Item[] }>("/api/sponsor/wallet").then((result) => { if (result.ok) { setWallet(result.data?.wallet ?? null); setTransactions(result.data?.transactions ?? []); setCommitments(result.data?.commitments ?? []); } else setBase({ error: result.message || "Wallet could not be loaded." }); setBase({ loading: false }); }); }, []);
  return <SponsorShell profile={base.profile}><div className="mx-auto max-w-7xl"><Header eyebrow="Sponsor Wallet" title="Wallet and campaign commitments" body="Track sponsor funding readiness, reserved funding states, transaction states, and campaign commitments separate from user DoroCoin wallets." action={<LinkButton href="/sponsor/wallet/fund-campaign">Funding Setup</LinkButton>} /><Notice>{campaignFundingDisclaimer}</Notice><ErrorCard message={base.error} />{base.loading ? <LoadingGrid /> : <><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Info title="Available balance" value={formatMoney(wallet?.availableBalanceCents, wallet?.currency)} /><Info title="Reserved funds" value={formatMoney(wallet?.reservedFundsCents, wallet?.currency)} /><Info title="Pending transactions" value={formatMoney(wallet?.pendingTransactionsCents, wallet?.currency)} /><Info title="Total spend" value={formatMoney(wallet?.totalSpendCents, wallet?.currency)} /></div><div className="mt-8 grid gap-6 lg:grid-cols-2"><ListCard title="Recent transactions" items={transactions} empty="No wallet transactions yet." href="/sponsor/wallet/transactions" /><ListCard title="Campaign commitments" items={commitments} empty="No campaign commitments yet." href="/sponsor/wallet/fund-campaign" /></div></>}</div></SponsorShell>;
}

export function SponsorFundCampaignPage() {
  const [base, setBase] = useSponsorProfile(); const [message, setMessage] = useState("");
  useEffect(() => { setBase({ loading: false }); }, []);
  async function submit() { const result = await apiRequest("/api/sponsor/wallet/fund-campaign-setup", { method: "POST", body: JSON.stringify({ campaignId: "", amount: 0 }) }); setMessage(result.message || "Funding setup required. No payment was processed."); }
  return <SponsorShell profile={base.profile}><div className="mx-auto max-w-5xl"><Header eyebrow="Campaign Funding" title="Campaign funding setup" body="Review funding requirements before provider-backed payment flows are configured." /><Notice>{campaignFundingDisclaimer}</Notice><Card className="mt-8 p-6"><div className="grid gap-4 md:grid-cols-2"><Info title="Contract requirement" value="Required before funding" /><Info title="Business verification" value="Required before funding" /><Info title="Payment provider" value="Setup required" /><Info title="Frontend payment status" value="Never trusted" /></div><Button className="mt-6" onClick={submit}>Record Setup-Required Funding Check</Button>{message ? <p className="mt-4 text-sm font-bold text-[var(--gold)]">{message}</p> : null}<p className="mt-4 text-sm leading-6 text-slate-500">This action records a setup-required status only. It does not charge a card, mark a campaign funded, reserve real money, or release funds.</p></Card></div></SponsorShell>;
}

export function SponsorMilestonesPage({ campaignScoped = false }: { campaignScoped?: boolean }) {
  const params = useParams<{ campaignId?: string }>(); const [base, setBase] = useSponsorProfile(); const [milestones, setMilestones] = useState<Item[]>([]);
  useEffect(() => { void apiRequest<{ milestones: Item[] }>("/api/sponsor/milestones").then((result) => { if (result.ok) setMilestones((result.data?.milestones ?? []).filter((item) => !campaignScoped || item.relatedCampaignId === params?.campaignId)); else setBase({ error: result.message || "Milestones could not be loaded." }); setBase({ loading: false }); }); }, [campaignScoped, params?.campaignId]);
  return <SponsorShell profile={base.profile}><div className="mx-auto max-w-6xl"><Header eyebrow="Milestones" title={campaignScoped ? "Campaign milestones" : "Sponsor milestones"} body="Track proposal, campaign, and delivery stages without marking payment releases complete." /><ErrorCard message={base.error} />{base.loading ? <LoadingGrid /> : milestones.length === 0 ? <EmptyState icon={<CalendarCheck />} title="No milestones yet." body="Milestones will appear after real campaign or proposal workflow stages exist." /> : <div className="mt-8 space-y-4">{milestones.map((item, index) => <Card key={item.id} className="p-5"><div className="grid gap-4 md:grid-cols-[56px_1fr_auto] md:items-center"><div className="flex h-12 w-12 items-center justify-center rounded-full border border-[var(--gold)]/40 bg-[var(--gold)]/10 text-sm font-black text-[var(--gold)]">{index + 1}</div><div><p className="text-xs font-black uppercase tracking-[0.16em] text-[var(--gold)]">{label(item.status)}</p><h2 className="mt-2 text-xl font-black">{item.title || "Milestone"}</h2><p className="mt-1 text-sm text-slate-500">{item.releaseCondition || "Next stage depends on real campaign status."}</p></div><div className="grid gap-3 text-sm sm:grid-cols-2 md:min-w-[320px]"><Info title="Due date" value={item.dueDate} /><Info title="Amount" value={formatMoney(item.amountCents, item.currency)} /></div></div></Card>)}</div>}</div></SponsorShell>;
}
export function SponsorBillingPage() {
  const [base, setBase] = useSponsorProfile(); const [billing, setBilling] = useState<Item | null>(null); const [invoices, setInvoices] = useState<Item[]>([]); const [transactions, setTransactions] = useState<Item[]>([]); const [tab, setTab] = useState("current_plan");
  useEffect(() => { void Promise.all([apiRequest<{ billing: Item; invoices: Item[] }>("/api/sponsor/billing"), apiRequest<{ transactions: Item[] }>("/api/sponsor/wallet/transactions")]).then(([billingResult, transactionResult]) => { if (billingResult.ok) { setBilling(billingResult.data?.billing ?? null); setInvoices(billingResult.data?.invoices ?? []); } else setBase({ error: billingResult.message || "Billing could not be loaded." }); if (transactionResult.ok) setTransactions(transactionResult.data?.transactions ?? []); setBase({ loading: false }); }); }, []);
  const tabs = [
    ["current_plan", "Current Plan"], ["payment_methods", "Payment Methods"], ["sponsor_funds", "Sponsor Funds"], ["invoices_receipts", "Invoices & Receipts"], ["billing_history", "Billing History"]
  ];
  return <SponsorShell profile={base.profile}><div className="mx-auto max-w-7xl"><Header eyebrow="Billing & Plan" title="Billing & Plan" body="Manage sponsor access, payment readiness, confirmed sponsor funds, invoices, and billing history in one place." /><Notice>Sponsor subscriptions unlock workspace tools. Campaign funding remains a separate provider-confirmed transaction.</Notice><ErrorCard message={base.error} />
    <div className="mt-6 flex gap-2 overflow-x-auto pb-2" role="tablist" aria-label="Billing and plan sections">{tabs.map(([key, labelText]) => <Button key={key} variant={tab === key ? "primary" : "secondary"} onClick={() => setTab(key)}>{labelText}</Button>)}</div>
    {base.loading ? <LoadingGrid /> : <div className="mt-8">
      {tab === "current_plan" ? <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="p-6"><h2 className="text-2xl font-black">Current plan</h2><div className="mt-5 grid gap-3"><Info title="Plan" value={billing?.currentPlan || "No active plan"} /><Info title="Billing status" value={friendlyProviderState(billing?.subscriptionStatus)} /><Info title="Renewal date" value={billing?.nextRenewalDate || "No renewal scheduled"} /></div><LinkButton href="/sponsor/plans" variant="secondary" className="mt-5 w-full">Review Available Plans</LinkButton></Card><Card className="p-6"><h2 className="text-2xl font-black">Plan benefits</h2><p className="mt-3 text-sm leading-6 text-slate-600">Your active plan and verified provider events determine which sponsor tools are available. Unavailable plans remain disabled without exposing provider configuration details.</p></Card></div> : null}
      {tab === "payment_methods" ? <Card className="p-6"><h2 className="text-2xl font-black">Payment methods</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info title="Status" value={friendlyProviderState(billing?.paymentMethodStatus)} /><Info title="Billing cycle" value={billing?.billingCycle || "Unavailable"} /></div><p className="mt-5 text-sm text-slate-600">Payment method changes are available only through a configured secure billing flow.</p></Card> : null}
      {tab === "sponsor_funds" ? <Card className="p-6"><h2 className="text-2xl font-black">Sponsor funds</h2><p className="mt-3 text-sm leading-6 text-slate-600">Only provider-confirmed funding records appear in the sponsor wallet. Pending or failed payments are never shown as available funds.</p><LinkButton href="/sponsor/wallet" variant="secondary" className="mt-5">Open Sponsor Funds</LinkButton></Card> : null}
      {tab === "invoices_receipts" ? (invoices.length === 0 ? <EmptyState icon={<ReceiptText />} title="No invoices or receipts yet" body="Invoices and receipts will appear after a successful provider-confirmed payment." /> : <div className="grid gap-3">{invoices.map((invoice) => <Card key={invoice.id} className="grid gap-3 p-5 md:grid-cols-[1fr_150px_150px_150px_auto] md:items-center"><div><p className="font-black">{invoice.invoiceNumber || "Invoice"}</p><p className="text-sm text-slate-500">{label(invoice.type)}</p></div><Info title="Date" value={invoice.issueDate} /><Info title="Amount" value={formatMoney(invoice.amountCents, invoice.currency)} /><Info title="Status" value={label(invoice.status)} /><LinkButton href={`/sponsor/billing/invoices/${invoice.id}`} variant="secondary">View</LinkButton></Card>)}</div>) : null}
      {tab === "billing_history" ? (transactions.length === 0 ? <EmptyState icon={<ReceiptText />} title="No billing history yet" body="Confirmed sponsor subscription and funding transactions will appear here." /> : <div className="grid gap-3">{transactions.slice(0, 50).map((transaction) => <Card key={transaction.id} className="grid gap-3 p-5 sm:grid-cols-3"><Info title="Type" value={label(transaction.type)} /><Info title="Amount" value={formatMoney(transaction.amountCents, transaction.currency)} /><Info title="Status" value={label(transaction.status)} /></Card>)}</div>) : null}
    </div>}
  </div></SponsorShell>;
}
function friendlyProviderState(value: unknown) { const normalized = String(value || "").toLowerCase(); if (!normalized || ["not_configured", "foundation_only", "unavailable"].includes(normalized)) return "Currently unavailable"; return label(value); }
export function SponsorInvoicesPage() {
  const [base, setBase] = useSponsorProfile(); const [invoices, setInvoices] = useState<Item[]>([]); const [status, setStatus] = useState("all");
  useEffect(() => { void apiRequest<{ invoices: Item[] }>("/api/sponsor/billing/invoices").then((result) => { if (result.ok) setInvoices(result.data?.invoices ?? []); else setBase({ error: result.message || "Invoices could not be loaded." }); setBase({ loading: false }); }); }, []);
  const filtered = invoices.filter((item) => status === "all" || item.status === status);
  return <SponsorShell profile={base.profile}><div className="mx-auto max-w-7xl"><Header eyebrow="Invoices" title="Invoices and receipts" body="Track subscription invoices, campaign invoices, receipts, adjustments, and refund notes as records." /><FilterRow query="" setQuery={() => {}} status={status} setStatus={setStatus} statuses={invoiceStatuses} placeholder="" hideSearch /><ErrorCard message={base.error} />{base.loading ? <LoadingGrid /> : filtered.length === 0 ? <EmptyState icon={<ReceiptText />} title="No invoices yet." body="Subscription and campaign invoices will appear here when issued through secure server flows." /> : <div className="mt-8 grid gap-5 lg:grid-cols-3">{filtered.map((invoice) => <Card key={invoice.id} className="p-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-[var(--gold)]">{label(invoice.status)}</p><h2 className="mt-3 text-2xl font-black">{invoice.invoiceNumber || "Invoice"}</h2><Info title="Type" value={label(invoice.type)} /><Info title="Amount" value={formatMoney(invoice.amountCents, invoice.currency)} /><Info title="Issue date" value={invoice.issueDate} /><LinkButton className="mt-5" href={`/sponsor/billing/invoices/${invoice.id}`} variant="secondary">View Invoice</LinkButton></Card>)}</div>}</div></SponsorShell>;
}

export function SponsorInvoiceDetailPage() {
  const params = useParams<{ invoiceId: string }>(); const [base, setBase] = useSponsorProfile(); const [invoice, setInvoice] = useState<Item | null>(null);
  useEffect(() => { if (!params?.invoiceId) return; void apiRequest<{ invoice: Item }>(`/api/sponsor/billing/invoices/${params.invoiceId}`).then((result) => { if (result.ok) setInvoice(result.data?.invoice ?? null); else setBase({ error: result.message || "Invoice could not be loaded." }); setBase({ loading: false }); }); }, [params?.invoiceId]);
  return <SponsorShell profile={base.profile}><div className="mx-auto max-w-5xl"><Header eyebrow="Invoice Detail" title={invoice?.invoiceNumber || "Invoice"} body="Review invoice metadata. PDF generation and paid status must come from secure server/provider workflows." action={<LinkButton href="/sponsor/billing/invoices" variant="secondary">Back to Invoices</LinkButton>} /><ErrorCard message={base.error} />{base.loading ? <LoadingGrid /> : !invoice ? <EmptyState icon={<ReceiptText />} title="Invoice not found." body="This invoice may not exist or may not belong to your sponsor account." /> : <Card className="mt-8 p-6"><div className="grid gap-3 md:grid-cols-2"><Info title="Type" value={label(invoice.type)} /><Info title="Status" value={label(invoice.status)} /><Info title="Amount" value={formatMoney(invoice.amountCents, invoice.currency)} /><Info title="Linked campaign/subscription" value={invoice.relatedCampaignId || invoice.relatedSubscriptionId} /><Info title="Issue date" value={invoice.issueDate} /><Info title="Due date" value={invoice.dueDate} /></div><Button className="mt-6" disabled>PDF not available yet</Button></Card>}</div></SponsorShell>;
}

export function SponsorTransactionsPage() {
  const [base, setBase] = useSponsorProfile(); const [transactions, setTransactions] = useState<Item[]>([]);
  useEffect(() => { void apiRequest<{ transactions: Item[] }>("/api/sponsor/wallet/transactions").then((result) => { if (result.ok) setTransactions(result.data?.transactions ?? []); else setBase({ error: result.message || "Transactions could not be loaded." }); setBase({ loading: false }); }); }, []);
  return <SponsorShell profile={base.profile}><div className="mx-auto max-w-7xl"><Header eyebrow="Wallet Transactions" title="Sponsor transaction history" body="Review campaign funding, reservations, platform fees, adjustments, refunds, and failed payment records." /><ErrorCard message={base.error} />{base.loading ? <LoadingGrid /> : transactions.length === 0 ? <EmptyState icon={<WalletCards />} title="No wallet transactions yet." body="Campaign funding activity will appear here once provider-backed payments are configured." /> : <div className="mt-8 grid gap-4">{transactions.map((item) => <Card key={item.id} className="grid gap-3 p-5 md:grid-cols-5"><Info title="Date" value={item.createdAt} /><Info title="Type" value={label(item.type)} /><Info title="Amount" value={formatMoney(item.amountCents, item.currency)} /><Info title="Status" value={label(item.status)} /><Info title="Reference" value={item.reference} /></Card>)}</div>}</div></SponsorShell>;
}

function Header({ eyebrow, title, body, action }: { eyebrow: string; title: string; body: string; action?: React.ReactNode }) { return <div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm font-black uppercase tracking-[0.2em] text-[var(--gold)]">{eyebrow}</p><h1 className="mt-3 text-4xl font-black md:text-5xl">{title}</h1><p className="mt-3 max-w-3xl leading-7 text-slate-600">{body}</p></div>{action}</div>; }
function FilterRow({ query, setQuery, status, setStatus, statuses, placeholder, hideSearch = false }: { query: string; setQuery: (value: string) => void; status: string; setStatus: (value: string) => void; statuses: readonly string[]; placeholder: string; hideSearch?: boolean }) { return <Card className="mt-6 p-4"><div className={`grid gap-3 ${hideSearch ? "lg:grid-cols-1" : "lg:grid-cols-[1fr_260px]"}`}>{hideSearch ? null : <div className="relative"><Search className="pointer-events-none absolute left-3 top-3.5 text-slate-500" size={18} /><input className={`${inputClass} pl-10`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder={placeholder} /></div>}<select className={inputClass} value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></div></Card>; }
function ListCard({ title, items, empty, href }: { title: string; items: Item[]; empty: string; href: string }) { return <Card className="p-6"><div className="flex items-center justify-between gap-3"><h2 className="text-2xl font-black">{title}</h2><LinkButton href={href} variant="ghost">Open</LinkButton></div>{items.length === 0 ? <p className="mt-5 rounded-[8px] border border-slate-200 bg-slate-50 p-4 text-sm leading-6 text-slate-500">{empty}</p> : <div className="mt-5 grid gap-3">{items.slice(0, 5).map((item) => <div key={item.id} className="rounded-[8px] border border-slate-200 bg-slate-50 p-4"><p className="font-bold">{item.title || item.invoiceNumber || item.reference || item.status || "Setup record"}</p><p className="mt-1 text-sm text-slate-500">{label(item.status)} {item.amountCents ? ` / ${formatMoney(item.amountCents, item.currency)}` : ""}</p></div>)}</div>}</Card>; }




